### ISSUE TITLE
jsonp support for monitoring routes?

### ISSUE THREAD

**Issue by cmfatih** [nats-io/gnatsd#100]
@derekcollison : Would you mind if I add JSONP support to monitoring routes and make a PR? That would help me to improve the [tool](https://github.com/cmfatih/natsboard) that I'm working on... I didn't want to waste time if you are not okay with it.

Update: Note that I want to put more stuff to client side but can't do it due to CORS. That's the reason for JSONP.

**Comment by derekcollison** [comment]
Just to /routez?






On Wed, Aug 12, 2015 at 5:15 PM -0700, "Fatih Cetinkaya" <notifications@github.com> wrote:












@derekcollison : Would you mind if I add jsonp support to monitoring routes and make a PR? That would help me to improve the tool that I'm working on... I didn't want to waste time if you are not okay with it.

**Comment by cmfatih** [comment]
All routes; `/varz`, `/connz`, `/routez` and `/subscriptionsz`

**Comment by derekcollison** [comment]
Send a PR, sounds fine to me.. What application is this for?

**Comment by cmfatih** [comment]
Cool, will send a PR in a few days. It is for the tool that I'm working on. https://github.com/cmfatih/natsboard

**Comment by repejota** [comment]
+1

**Comment by derekcollison** [comment]
Nice!

**Comment by pkieltyka** [comment]
Have a look at https://github.com/pressly/gohttpware/tree/master/jsonp for a Jsonp middleware that stays out of the way and is triggered by the content type. It's my code, feel free to copy / augment if it helps

**Comment by cmfatih** [comment]
@pkieltyka : It would be awesome if you take over this task and deliver since you have already experience with it. What you say? :)

**Comment by pkieltyka** [comment]
Sure, no prob. I'll submit PR tomm

**Comment by cmfatih** [comment]
Sound awesome to me :+1:

**Comment by cmfatih** [comment]
@pkieltyka : I just made a PR for it. It was more easier than I thought. Somehow I always hesitate about my golang skills :)

Can you check it and let me know whether I'm naif or not? https://github.com/nats-io/gnatsd/pull/103/files

I locally test it and it works for;

```javascript
$.getJSON('http://localhost:8222/connz?callback=?', function(data) { console.log(data); });

or

$.ajax({
  url: 'http://localhost:8222/connz',
  dataType: 'jsonp',
  jsonpCallback: 'callback',
  success: function(data) {
    console.log(data);
  }
});
```
