### ISSUE TITLE
proposal: gnatsd as embedded package for my Go services

### ISSUE THREAD

**Issue by pkieltyka** [nats-io/gnatsd#106]
Hi guys,

Have you considered supporting `gnatsd` to be compiled into a Go web service as a package, in addition to currently as a standalone server? Here are my reasons:

1. The simplicity and lightweighted-ness of gnatsd makes it a perfect toolkit for building distributed systems out of many services inter-communicating over a network-wide CSP. I believe like a service takes HTTP as first class, and a service is effectively an HTTP server, I think services should be NATS servers working in the network.
2. If each service is a NATS server, then there is greater distribution and easier to achieve goal of always-on "dial-tone".
3. Deployment is easier
4. Standalone gnatsd servers will still work with NATS service nodes (obviously).
5. From the TODO.md, I see you guys want to have Gossip-based service discovery (thank you!), this again will be awesome for the embedded use case to form a cluster of services, including heartbeats, etc.

-- 

In order to support this to experiment, the first step is easy. Just move the `main` package to a CLI package at `github.com/nats-io/gnatsd/cmd/gnatsd`. This is common practice and then the `github.com/nats-io/gnatsd` package is used to start/setup/stop the server, which is in-turn used by `cmd/gnatsd`. If you guys are interested in this, I'd be happy to submit a PR -- but, if you don't intend to merge it then just tell me before I work on it, would rather discuss in proposal stage then.

**Comment by derekcollison** [comment]
We already support this today. If you look at the tests for the Go client
inside of gnatsd repo, you see how we embed the server as a Goroutine
inside of the test quite. You still connect via TCP currently, but it is
running inside of a single process.

https://github.com/nats-io/gnatsd/blob/master/test/test.go#L46

Its essentially Start() and Shutdown(), just do the start inside a new Go
routine.

**Comment by pkieltyka** [comment]
ah, good to hear. I prefer the `cmd/` pattern for cli binaries and having the core package at the root, but thats just subjective stuff. I'll give it a shot, thanks.

**Comment by krobertson** [comment]
To build on @derekcollison's comment, we also do this in all our internal test suites that use NATS, and some of our own tooling that is a single process also embeds gnatsd as a simple way for separate packages to cross communicate.

**Comment by pkieltyka** [comment]
right on! :metal:

**Comment by derekcollison** [comment]
Happy to take a PR on the cmd/ pattern..

**Comment by nkev** [comment]
@derekcollison I want to build a modular application structure employing an embedded GNATSD server  as an event emitter to communicate between modules within the same process. Later when scaling, some modules can be moved to a different server but maintain exactly the same code for event emission. My concern is this comment you made above:

>You still connect via TCP currently, but it is running inside of a single process.

How much of a performance penalty would that impose for clients connecting within the same process?

**Comment by pkieltyka** [comment]
@nkev why not just use goroutines/channels if its within the same process?

**Comment by pkieltyka** [comment]
@nkev a good practice that's been helping me over recent years is to iterate towards the end vision. So instead of looking ahead and starting with many abstractions that you "know" you'll need one day, better to write the first version so its clear, explicit and solves the stage of the problem you need. Then as you iterate, you also refactor and if you follow good design, like in this case, you could extend those channels to connect to NATS when you scale out.

**Comment by derekcollison** [comment]
Fairly easy to do, look here for an example: https://github.com/nats-io/nats/blob/master/test/test.go

There is another PR to make this cleaner and easier which I will look at soon since we will be embedding the server inside some stuff as well.

**Comment by nkev** [comment]
@pkieltyka:
>why not just use goroutines/channels if its within the same process?

Thanks, I'm thinking why reinvent the wheel when NATS already has the wildcard based pub-sub that I need? My project requires both in-process and external process modules out of the box and if I can achieve this with a single pub-sub codebase, that will make it more elegant and maintainable.

@derekcollison:
>Fairly easy to do, look here for an example: https://github.com/nats-io/nats/blob/master/test/test.go

Thanks, I saw that in your previous post but my question is how much of a performance overhead would connecting to localhost for both client and server pubs operations (all in a single process) compared to a separate in-process event emission package like [this one](https://github.com/chuckpreslar/emission) (which I would have to modify to allow wildcard subscriptions). It would be nice to use NATS for both in-process and externally for module events but I'm not sure if that's the way to go.

**Comment by derekcollison** [comment]
I don't think the performance impact will bother you unless you are looking
at > 1M msgs/sec requirements.

**Comment by nkev** [comment]
Thank you, that's the kind of info I needed to hear. I figure if I'm hitting >1M msgs/sec on a single server, then it's time to move the busiest modules to other servers.Is there scope to create a "memory" transport for NATS (for in process server and clients)?

**Comment by derekcollison** [comment]
Possibly, but just embed a server for now.

**Comment by nkev** [comment]
I just had a brain freeze moment... I remember reading that GNATSD server is capable of 6-8M msgs/sec when running as a separate process. Are you saying that running the GNATSD server as a separate process would be faster than embedding?

**Comment by derekcollison** [comment]
No not at all.

**Comment by bjflanne** [comment]
@nkev -- if you're interested, be great to also have you in the NATS Slack community...great area for synchronous exchange around NATS - good group in there, and I'd also be curious to discuss what you're trying to build further...just fill out this form (http://bit.ly/1OyNc9W) and I'll shoot you an invite.

**Comment by joeblew99** [comment]
Did anyone work out a way to not be forced to use TCP when embedded ?

I imagine the client and server could use bgo routines to connect to each other but not sure if it's easy to adjust the current code base

**Comment by derekcollison** [comment]
The loopback interfaces are fairly well optimized so not sure you will see a significant change in performance if you avoided sockets.
