### ISSUE TITLE
add AllClients functions to show all clients 

### ISSUE THREAD

**Issue by lostz** [nats-io/gnatsd#107]
func (s *Server) AllClients() map[uint64]*client {
	s.mu.Lock()
	defer s.mu.Unlock()
	return s.clients
}

func (c *client) Addr() string {
	return c.nc.RemoteAddr().String()

}

add those functions to show client detail as monitor

**Comment by derekcollison** [comment]
Not following, does /connz not do what you need?

**Comment by derekcollison** [comment]
lmk if I am misunderstanding. Thanks..
