### ISSUE TITLE
node discovery

### ISSUE THREAD

**Issue by pkieltyka** [nats-io/gnatsd#108]
I've seen in TODO you guys are planning to add gossip-based node discovery. Have a look at: https://github.com/hashicorp/memberlist  .. this is used in serf and consul for a while now

**Comment by derekcollison** [comment]
I am aware of that algorithm that they use, I have some ideas on how we will accomplish what we need both from a server to server perspective and then utilizing updating INFO messages to the clients as well.

**Comment by pkieltyka** [comment]
Solid

**Comment by mcqueary** [comment]
Closing in favor of #126. Please add comments there.
