### ISSUE TITLE
Escape/special characters disrupting gnatsd

### ISSUE THREAD

**Issue by cosmicnag** [nats-io/gnatsd#114]
(reponse meant for request1)
    MSG _INBOX.630146017521313532193872803 259 564
    (response meant for request2)

Cant pinpoint what it is, but could be some special/escape characters that are disrupting the text protocol of gnatsd, causing spillover of another request's reponse into a response with that MSG_INBOX string in it.
To explain,
Request1 -> Reponse1+"MSG_INBOX....."+Response2

Hence the response to request1 contains a concatenation of the MSG_INBOX text as well as the reponse of another request. (JSON parsing obviously fails because of this) This has a disastrous effect as it disrupts all coordination of NATS. It seems I have to restart the client node process to get everything working again.

I'm on node-nats 0.3.0 and gnatsd 0.6.6

Thanks.

**Comment by cosmicnag** [comment]
Woah... looks like it got resolved by updating node-nats to 0.4.2

**Comment by derekcollison** [comment]
ok great!

**Comment by derekcollison** [comment]
Just released 0.4.4 which is recommended. Had a very rare edge condition
bug that was fixed.

**Comment by cosmicnag** [comment]
cool thanks will definitely update right away
