### ISSUE TITLE
ROUTE connection do not reconnect.

### ISSUE THREAD

**Issue by rexxar-liang** [nats-io/gnatsd#119]
Our team found ROUTE connection do not reconnect after connection disconnected.
1.Our cluster environment:
Two physical machine,A and B, each of them deploy one gnats on it.
2.Trigger:
Disconnect the network cable between A and B. after 10 minutes, recover the network cable between A and B.
3.expect result:
ROUTE connection between 2 gnats expect to be reconnect after network is recovered.
4.actual result:
ROUTE connection between 2 gnats do not reconnect.

I have go though the code and found:
1.server side
   The connection closed in [closeconnection](https://github.com/nats-io/gnatsd/blob/master/server/client.go#L920)
   and this ROUTE connection is not "Solicited Route", so it will not try to [reconnect](https://github.com/nats-io/gnatsd/blob/master/server/client.go#L957)
2.client side
   The connection [cleared](https://github.com/nats-io/gnatsd/blob/master/server/client.go#L834) after ping reach MaxPingsOut, although the connection is "Solicited Route"

Can anyone help?
Thanks very much.

**Comment by derekcollison** [comment]
It seems like there could be an issue with the route connection not being tried after the MaxPingsOut happens. I will take a look.

cc @krobertson @olegshaldybin

**Comment by rexxar-liang** [comment]
@derekcollison 
Thanks for your reply, I have figure out the reason and fix it.
I use an old version which have this issue, after upgrading to a new one, gnatsd works perfactlly.
