### ISSUE TITLE
Connection information via server.ClientAuth, clientOpts

### ISSUE THREAD

**Issue by sheenobu** [nats-io/gnatsd#120]
I'm currently embedding gnatsd into an application and providing custom auth. I am able to grab user-supplied details, however there is no way to get connection information from server.ClientAuth. This is the closest I have gotten:

	str := client.(fmt.Stringer).String()
	tokens := strings.Split(str, ":")
	ip := tokens[0]

This does get me the IP address (and eventually port). I noticed the String() method returns ncs (ip:port - cid:Number) . Can this method be relied upon, and/or does ClientAuth or clientOpts need a visible API to access connection information?

**Comment by derekcollison** [comment]
Possibly the monitoring API (/connz specifically) can be helpful. https://github.com/nats-io/gnatsd#monitoring.

**Comment by sheenobu** [comment]
@derekcollison Thank you. Does not look like their is a way to drop connections but a combination may work. That said... we ended up going with token based authentication instead.
