### ISSUE TITLE
Authentication vs. Authorization

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#122]
`gnatsd` does client **authentication**, but not **authorization**. The code seems to use these words interchangeably, which makes the use of the **`auth`** abbreviation in the naming pretty ambiguous.

- **Authentication** is the process of ascertaining that somebody really is who he claims to be.
- **Authorization** refers to rules that determine who is allowed to do what. 
e.g. Larry is authorized to create routes, and publish to and subscribe to subjects matching `foo.*`, and Colin is only authorized to subscribe to subjects matching `foo.*`.

We should be more specific/explicit when using these terms in function and variable naming and comments.

**Comment by ColinSullivan1** [comment]
This should also apply to monitoring - the same credentials can be used to secure the monitoring interface.

**Comment by mcqueary** [comment]
We will address this in #129
