### ISSUE TITLE
HTTP support

### ISSUE THREAD

**Issue by rexxar-liang** [nats-io/gnatsd#123]
currently gnats route is like this "nats-route://user:pass@IP:PORT" ,
whether we will consider to support http/https connection, like "nats-route://user:pass@DOMAIN:PORT"

**Comment by derekcollison** [comment]
We will support TLS alongside TLS for client connections. The route protocol is a text based protocol and is not HTTP based, but we are committed to secure connections.

/cc @mcqueary

**Comment by rexxar-liang** [comment]
Hi @derekcollison ,
    Good idea, We are looking forward to TLS feature.
    By the way, is there any roadmap or timeline for this feature?

**Comment by derekcollison** [comment]
It;s the next major item on our roadmap. Actively working on it now.

**Comment by derekcollison** [comment]
TLS support is now in master.
