### ISSUE TITLE
TLS/SSL support

### ISSUE THREAD

**Issue by smithwinston** [nats-io/gnatsd#124]
It seems there's an `ssl_required` config option but no actual TLS/SSL support?  Ideally, the configuration would allow for Certificates, RootCA, CipherSuites, ServerName, InsecureSkipVerify and MinVersion (TLS) to be configured.

**Comment by derekcollison** [comment]
Yes that is the plan! Coming soon.

**Comment by pires** [comment]
This is closed as well, https://github.com/nats-io/gnatsd/commit/850da72adcf544d434f93cccdf909ee744ffac79.
