### ISSUE TITLE
Get JSON config from URL

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#125]
To ease integration with directory services and other configuration sources, `gnatsd` should accept a configuration URL that points to a valid server config.

example:
`gnatsd -c http://configserver.example.com:8181/nats?node=mynodename`

The config can be read using cURL or similar.

**Comment by derekcollison** [comment]
Agree, but this will not be all inclusive. Closing for now but this will be implemented, just not exactly like this.
