### ISSUE TITLE
Server graph auto-discovery and announcement

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#126]
Cloud deployment requires elastic scaling of server clusters. Doing this should be simple and dynamic, not requiring `gnatsd` or clients to restart in the event of graph changes.

This implementation should, at a minimum, achieve the following:

1. Allow any `gnatsd` instance to connect to any already-running `gnatsd` instance, discover its graph, and connect to its graph.
2. Allow any client to connect to any already-running `gnatsd` instance, discover its graph, and build a URL list.
3. Allow updates concerning the graph to be pushed to clients, e.g. via the INFO message

**Comment by joeblew99** [comment]
+1
Will make things .uch easier on kubernetes for me.

**Comment by derekcollison** [comment]
You will still need to know 'one' server for new servers or clients, just FYI.

**Comment by yonah-codefresh** [comment]
+1

**Comment by pkieltyka** [comment]
awesome guys! can you add to the docs as to how its designed / works? (without having to read all the code)

**Comment by derekcollison** [comment]
Yes, of course..

**Comment by pires** [comment]
Seems this is part of 0.8.0.

**Comment by kozlovic** [comment]
@pires Not the client part though.

**Comment by pires** [comment]
Makes sense 👍

**Comment by kozlovic** [comment]
I believe this is now fully addressed with following merged PRs: server: https://github.com/nats-io/gnatsd/pull/314, go client: https://github.com/nats-io/nats/pull/209
