### ISSUE TITLE
Don't store passwords in clear text

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#128]
Basic user/pass authentication module should store passwords hashed using e.g. [bcrypt](http://godoc.org/golang.org/x/crypto/bcrypt).

@ColinSullivan1 says this is a good idea. Millions of users agree :)

**Comment by derekcollison** [comment]
I agree..

**Comment by pires** [comment]
Isn't this fixed by https://github.com/nats-io/gnatsd/commit/6fc9927f52b1654c5431f5aa53503c044dcb71e3?

**Comment by derekcollison** [comment]
Yes, correct.
