### ISSUE TITLE
Multi-user subject authorization

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#129]
To use NATS within multi-tenant environments or within security constraints of enterprise environments requires the ability to authorize users to perform actions on potentially sensitive or privileged objects.

In the current NATS implementation, the authorizable actions include:
- Connect to a node/cluster
- Publish to a subject
- Subscribe to a subject

Authorization can be based on a number of factors, individually or in combination, for example:
- Distinguished name (LDAP DN)
- Common Name (SSL CN)
- Simple username
- IP address (or network)
- Role
- Access Control Lists (ACLs)

An extensible authorization interface will provide an easy mechanism for implementing, adding or integrating authorization services, contexts, and access control lists (ACLs).

EDIT: See also #182 regarding multiple admin user stanzas (for rolling upgrade use case)

/cc @nats-io/dev

**Comment by mcqueary** [comment]
See also #122 -- need to clean up references to _Authorization_ in `gnatsd` that actually mean _Authentication_

**Comment by dramdass** [comment]
It'd be useful to also authorize on the client TLS x509 cert - for example, based on the cert serial number or values of certain cert extensions

**Comment by MikaelSmith** [comment]
This is an area I'm interested in as well. It's a little more complex, but you might find [trapperkeeper-authorization](https://github.com/puppetlabs/trapperkeeper-authorization/blob/master/doc/authorization-config.md) an interesting example of authorization rules.

**Comment by mcqueary** [comment]
This was closed in large part by #300. The "extensible" part will be addressed via #428 / #434
