### ISSUE TITLE
Support message persistence

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#130]
The NATS ecosystem (and not necessarily `gnatsd` itself) should support the ability to persist messages such that a client may receive messages that have been published to subjects of interest while that client was not connected to `gnatsd`.

**Comment by derekcollison** [comment]
As you know, I believe the larger NATS ecosystem should provide this, but I do not believe this should be core to gnatsd.

**Comment by mcqueary** [comment]
@derekcollison Sorry for creating confusion. My intent wasn't to imply that `gnatsd` itself should have this functionality as core. By popular community request, we are trying to use GitHub to track the NATS project roadmap. For the moment, we're using this repository as the master Issue Tracker for that purpose. Granted, that artificially *bends* Issue Tracker a little bit for this repo, especially when discussing things that might not exist yet, and might not (or will not) exist in `gnatsd`. 

Another solution would be to create a 'nats-io/roadmap' repo, which would also be somewhat artificial, in that it would only exist to hold issues and milestones that point at Issues and Milestones that live in other repositories.

**Comment by mcqueary** [comment]
Issue description edited to reflect @derekcollison comment.

**Comment by rexxar-liang** [comment]
So, are we going to support this feature(message persistence) in our roadmap?

**Comment by derekcollison** [comment]
yes.

**Comment by sachinwalia2k8** [comment]
Hi @derekcollison / @mcqueary any estimate when this may be implemented.

**Comment by mcqueary** [comment]
I think we should have something usable by around  the end of March. What
client language are you interested in?

On Friday, February 12, 2016, Sachin Walia <notifications@github.com> wrote:

> Hi @derekcollison <https://github.com/derekcollison> / @mcqueary
> <https://github.com/mcqueary> any estimate when this may be implemented.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/gnatsd/issues/130#issuecomment-183456657>.
>


-- 
*Larry McQueary* | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary

**Comment by sachinwalia2k8** [comment]
I am using Java 8. So far I have been using Java client built by tyagihashi. However contemplating moving to the official jnats client.

**Comment by pires** [comment]
Java and Go here!

**Comment by mcqueary** [comment]
Sachin let me know if you need assistance making the move. I have not
compared jnats to Teppei's client but they should be quite similar other
than minor details. We'd like to identify anything that will ease adoption
and make sure we address it.

On Friday, February 12, 2016, Sachin Walia <notifications@github.com> wrote:

> I am using Java 8. So far I have been using Java client built by
> tyagihashi. However contemplating moving to the official jnats client.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/gnatsd/issues/130#issuecomment-183460170>.
>


-- 
*Larry McQueary* | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary

**Comment by sachinwalia2k8** [comment]
Thanks I'll try to implement jnats and see if i hit any problem.

**Comment by glycerine** [comment]
I have a library that shows how to write a nats client that does persistence for selected topics.

https://github.com/glycerine/tmframe/tree/master/archiver

**Comment by mcqueary** [comment]
Nice, Jason! 

/cc @bjflanne

**Comment by mcqueary** [comment]
This issue is generally resolved by "Project STAN" and will be specifically addressed in nats-io/stan#40. More information will be announced next week.

**Comment by chrismcv** [comment]
404?

**Comment by mcqueary** [comment]
Apologies, that repo is not public yet. Stay tuned!

On Sunday, March 20, 2016, Chris McVittie <notifications@github.com> wrote:

> 404?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/gnatsd/issues/130#issuecomment-199026262>
>


-- 
*Larry McQueary* | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary

**Comment by chrismcv** [comment]
@mcqueary any updates on this or an eta?

**Comment by mcqueary** [comment]
@chrismcv it's in-flight right now and should be in the MVP, which should be when all this is made public. We're working out the date right now. Are you on our Slack team? DM me your email address on Twitter and I can send you an invite.

**Comment by derekcollison** [comment]
This will be covered by STAN, not the core nats-server.
