### ISSUE TITLE
Windows release ?

### ISSUE THREAD

**Issue by asafyish** [nats-io/gnatsd#134]
Hi,

I saw there is no official windows binary, but people still using it on windows, does it mean they compile from source ?

**Comment by ColinSullivan1** [comment]
Hi Asaf,

Yes, NATS compiles directly from the source - the instructions to build  apply to Windows as well.  What clients are you interested in?

Thanks,
Colin

**Comment by asafyish** [comment]
We are using node.js and python clients.
Thanks for the quick response !

**Comment by xogeny** [comment]
Any particular reason *why* there's no Windows release?

I've used NATS in the past and thought it would be good for a project I'm now working on. But when I saw no Windows download on nats.io and no release here, I assumed there was some issue that prevented it from running on Windows (cgo, posix, etc.).  I think that is a reasonable assumption and I suspect many people would jump to that conclusion.

So I'm surprised to find out that it *does* run on Windows.  Why not create a build?  Do you really expect people to download the Go dev tools and build their own?  Seems almost punitive to me (especially if they aren't even interested in Go and plan on using non-Go clients) and not very good marketing.

**Comment by kozlovic** [comment]
@xogeny Thanks for the feedback! We are planning on providing a build for Windows in our upcoming release (very soon).

**Comment by ColinSullivan1** [comment]
@xogeny, Thank you for bringing this issue up.  @kozlovic beat me to the response here.  There's no reason a windows download isn't there, other than that we've been working hard on other features.  I've run the NATS server extensively in my testing with the NATS C# .NET client and it has performed well.

**Comment by sixlettervariables** [comment]
I'll throw in my +1 for a Windows build. Because of our secure development environment, it has become basically impossible to build go projects with more than a handful of external dependencies. We really (really) want to evaluate nats as our ServiceBus replacement.

**Comment by mcqueary** [comment]
@sixlettervariables This is definitely something we're going to do... thanks for weighing in!

**Comment by bjflanne** [comment]
@sixlettervariables I see you are (relatively) local; I am in the RDU area. Be great to sync up sometime, will drop you a quick email.

**Comment by kozlovic** [comment]
@sixlettervariables As @mcqueary stated, this is coming and probably very soon when we issue a new release. We were thinking about providing the 64bit version only. Would that work for you?

**Comment by sixlettervariables** [comment]
Absolutely. Our current environment is 2012 R2 64-bit.

On Wed, Mar 30, 2016 at 4:22 PM, Ivan Kozlovic <notifications@github.com>
wrote:

> @sixlettervariables <https://github.com/sixlettervariables> As @mcqueary
> <https://github.com/mcqueary> stated, this is coming and probably very
> soon when we issue a new release. We were thinking about providing the
> 64bit version only. Would that work for you?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/gnatsd/issues/134#issuecomment-203615712>
>



-- 
Christopher A. Watford
christopher.watford@gmail.com

**Comment by derekcollison** [comment]
This is now enabled on master via 0db7adb6b190143ab1d69ec921cf0612ae9e0c28

**Comment by derekcollison** [comment]
Will provide prebuilt windows binaries in next release which is next week (scheduled).
