### ISSUE TITLE
gnatsd crashes on Windows i386 (and probably on any Intel 32bit platform)

### ISSUE THREAD

**Issue by raff** [nats-io/gnatsd#14]
The crash happens as soon as a client connects, and it's a null pointer exception on the atomic add:

// Lock should be held
func (c *client) initClient() {
        s := c.srv
        c.cid = atomic.AddUint64(&s.gcid, 1) //////// crash here

There are no null pointers but AddUint64() crashes if the pointer is not 64bit aligned ("fix" added on March 12: https://code.google.com/p/go/source/detail?r=09cc9661f4ee29dca7da92ae8916cefded775bb5&path=/src/pkg/sync/atomic/asm_386.s)

Suggestion: align the pointer or make s.gcid (and c.cid) int32 ?

**Comment by mcqueary** [comment]
Seems to be closed by #78. Please let us know if not.
