### ISSUE TITLE
tls handshake is fine with go1.5.1 but not with go 1.4.2

### ISSUE THREAD

**Issue by SrinivasChilveri** [nats-io/gnatsd#144]
The certificates are generated accrding to the explaination from the below link...
https://docs.docker.com/engine/articles/https/

Logs & conf from NatsNode1:
cluster {
  host: "9.XX.XX.15"
  port: 4223

  authorization {
    user: "nats"
    password: "pass"
    timeout: 60
  }

  routes = [
  nats-route://nats:pass@9.91.17.102:4223
  ]
  tls {
        # Server cert
        cert_file: "/root/tlscerts/server-cert.pem"
        # Server private key
        key_file: "/root/tlscerts/server-key.pem"
        # Optional certificate authority for clients
        ca_file: "/root/tlscerts/ca.pem"
        # Require a client certificate
        verify: true
       }
}

2015/11/25 19:28:44 ["Route connection created", [X.XX.XX.102, 42821], 1]
2015/11/25 19:28:44 ["Starting TLS route server handshake: 
2015/11/25 19:28:45 ["TLS route handshake error: tls: client's certificate's extended key usage doesn't permit it to be used for client authentication , {0 false false 0  false  [] [] []}"]
2015/11/25 19:28:45 ["Router connection closed", [9.XX.XX.102, 42821], 1]
 tls: client's certificate's extended key usage doesn't permit it to be used for client authentication"]
2015/11/25 19:28:45 ["Trying to connect to route on X.XX.XX.102:4223"]
2015/11/25 19:28:45 ["Route connection created", [X.XX.XX.102, 4223], 2]
2015/11/25 19:28:45 ["Starting TLS route client handshake: 2015/11/25 19:28:45 ["TLS route handshake error: remote error: handshake failure , {0 false false 0  false  [] [] []}"]
2015/11/25 19:28:45 ["Router connection closed", [9.91.17.102, 4223], 2]
2015/11/25 19:28:45 ["Attempting reconnect for solicited route", 2]

Logs from Node2:

2015/11/25 14:29:14 ["Trying to connect to route on 9.XX.XX.15:4223"]
2015/11/25 14:29:14 ["Route connection created", [9.XX.XX.15, 4223], 1]
2015/11/25 14:29:14 ["Starting TLS route client handshake: 2015/11/25 14:29:14 ["TLS route handshake error: remote error: handshake failure , {0 false false 0  false  [] [] []}"]
2015/11/25 14:29:14 ["Router connection closed", [9.XX.XX.15, 4223], 1]
2015/11/25 14:29:14 ["Attempting reconnect for solicited route", 1]

2015/11/25 14:29:14 ["Route connection created", [9.XX.XX.15, 55845], 2]
2015/11/25 14:29:14 ["Starting TLS route server handshake: 2015/11/25 14:29:14 ["TLS route handshake error: tls: client's certificate's extended key usage doesn't permit it to be used for client authentication , {0 false false 0  false  [] [] []}"]
2015/11/25 14:29:14 ["Router connection closed", [9.XX.XX.15, 55845], 2]

The main issue is if i build with go version go1.4.2 linux/amd64
 the above handshake failure is happening but with same code & same certs if i build with go version go1.5.1 linux/amd64 the handshake is proper & nats cluster communication is proper.

does the certification verification of tls evolved from go1.4.2 to go 1.5.1?  but i have seen go 1.4 is enough for nats any info is appreciated...

Thanks & Regards,
SriniCH

**Comment by derekcollison** [comment]
The certs used for routes in my testing have client and server extensions. Take a look at srva-cert.pem

```
X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:localhost, IP Address:127.0.0.1
            X509v3 Extended Key Usage: 
                TLS Web Client Authentication, TLS Web Server Authentication
```
