### ISSUE TITLE
The first line of config file is parsed error 

### ISSUE THREAD

**Issue by wustrong** [nats-io/gnatsd#145]
version:0.5.2

can't get the first properties correctly, others are right.
the configuration in nats.conf is:
  1 net:"10.62.X.X"
  2 port: 50021

print the mapping in parse:
![image](https://cloud.githubusercontent.com/assets/5350907/11425215/36f473fc-948e-11e5-870b-80aad727c13e.png)

but the gnatsd doesn't listen the configured IP(use default IP0.0.0.0).
SZX1000023942:/opt/wsz/nats/install/nats/bin # lsof -i:50021
COMMAND   PID USER   FD   TYPE   DEVICE SIZE/OFF NODE NAME
gnatsd  38251 root    8u  IPv6 23170710      0t0  TCP *:50021 (LISTEN)

**Comment by derekcollison** [comment]
In general it expects a hostname, but I agree a direct IP should work.

**Comment by wustrong** [comment]
when add 1 line at the top of nats.config:

**Comment by derekcollison** [comment]
I will take a look, thanks for the report.

**Comment by derekcollison** [comment]
If the IP is quoted it should work.

e.g.

```
net: '10.39.156.19'
```

Do you use the one listed above with the 'X's? e.g. '10.62.X.X'?

**Comment by wustrong** [comment]
net: "10.39.156.19"

**Comment by derekcollison** [comment]
Can you try https://github.com/nats-io/gnatsd/releases/tag/v0.6.8 and let me know the results?

**Comment by wustrong** [comment]
the first line is not parsed right.

when i add one line at the top:
 name: gnatsd
![Uploading image.png…]()

version is:0.6.8

**Comment by derekcollison** [comment]
ok will take a deeper look, thanks..

**Comment by derekcollison** [comment]
Works for me..

```bash
~/Development/go/src/github.com/nats-io/gnatsd> more server/configs/test.conf 
net: "172.29.5.243"

# Simple config file

port: 4242
#net: apcera.me # net interface

http_port: 8222

authorization {
  user:     derek
  password: bella
  timeout:  1
}

# logging options
debug:   false
trace:   true
logtime: false
#log_file: "/tmp/gnatsd.log"
#syslog: true
#remote_syslog: "udp://foo.com:33"

# pid file
pid_file: "/tmp/gnatsd.pid"

# prof_port
prof_port: 6543

# max_connections
max_connections: 100

# maximum control line
max_control_line: 2048

# maximum payload
max_payload: 65536

# slow consumer threshold
max_pending_size: 10000000
~/Development/go/src/github.com/nats-io/gnatsd> ./gnatsd -c ./server/configs/test.conf 
[15011] 2015/12/03 11:59:59.431309 [INF] Starting gnatsd version 0.6.9.beta
[15011] 2015/12/03 11:59:59.431496 [INF] Starting http monitor on 172.29.5.243:8222
[15011] 2015/12/03 11:59:59.431604 [INF] Starting profiling on http port 6543
[15011] 2015/12/03 11:59:59.431620 [INF] Listening for client connections on 172.29.5.243:4242
[15011] 2015/12/03 11:59:59.431645 [INF] gnatsd is ready
^Z
[1]+  Stopped                 ./gnatsd -c ./server/configs/test.conf
~/Development/go/src/github.com/nats-io/gnatsd> lsof -i:4242
COMMAND   PID  USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
gnatsd  15011 derek    6u  IPv4 0x3d844519461d4231      0t0  TCP 172.29.5.243:4242 (LISTEN)
~/Development/go/src/github.com/nats-io/gnatsd> 
```

**Comment by derekcollison** [comment]
Feel free to reopen if I am missing something.
