### ISSUE TITLE
Error parsing passwords that begin with a digit

### ISSUE THREAD

**Issue by jmealo** [nats-io/gnatsd#147]
If a password starts with a number the configuration parser attempts to parse the password as a number instead of a string causing the parsing to fail with a cryptic error message indicating that the first non-numeric character should be a map value terminator.

** Example output: **
```
Parse error on line 7: 'Expected a map value terminator "," or a map terminator "}", but got 'V' instead.'
```

**Comment by derekcollison** [comment]
Parsing numbers is tricky. If the password starts with a number, simply quote it.

e.g.
```
password: '1!2go'
```
