### ISSUE TITLE
Do we have any plans to support adding a new node(peer) dynamically into a nats cluster?

### ISSUE THREAD

**Issue by SrinivasChilveri** [nats-io/gnatsd#152]
I think present gnats doesn't support adding new node dynamically into a gnats cluster dynamically...
Do we have any plans to support adding a new node(peer) dynamically into a gnats cluster?

**Comment by derekcollison** [comment]
Yes, that is next up after this large security release. We will add a gossip protocol for both cluster formation and for client notifications as well. See #126
