### ISSUE TITLE
Parser error when using TLS: [46367] 2015/12/06 19:14:50.058181 [ERR] ::1:58819 - cid:39 - Error reading from client: Client Parser ERROR, state=0, i=0: proto='"\x16\x03\x01\x019\x01\x00\x015\x03\x035\x86U\x1b_\x96\x15{\xb1\xcc,\x96\xaaTDoK\x81x,\xa6"...'

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#153]
(note that with current code, the protocol snippet is not printed, see #154).

I wonder if when the server initializes the client, we should delay the start of the readLoop when tls is required until after we have done the ssl handshake (and re-wrapped the buffer). I was running tests where the client creates SSL connections repeatedly and would often get a parser error (which the protocol looked like it was SSL encryption).

@derekcollison I am experimenting with a fix but wanted to get your opinion.

**Comment by derekcollison** [comment]
Possibly. I will think about this a bit.

**Comment by kozlovic** [comment]
Fixed with #160
