### ISSUE TITLE
Parser error never shows protocol snippet

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#154]
I believe that a recent change caused this issue. Here is the output of a parser error:

[46125] 2015/12/06 19:06:51.965494 [ERR] ::1:56104 - cid:39 - Error reading from client: Client Parser ERROR, state=0, i=0: proto='...'

The protocol snippet is not printed. I believe that this is caused by commit: 498df401af204644fc7b5ef0c173e8ddb0ed0c86

**Comment by derekcollison** [comment]
Do we not have a test for the snippet? Guess we need one.
