### ISSUE TITLE
Client can prematurely decrement pending pings.

### ISSUE THREAD

**Issue by xorgy** [nats-io/gnatsd#168]
gnatsd [will decrement client.pout below zero][1] when the client sends a `PONG`. As a result, the client can send any number of `PONG`s in advance to avoid timeout.

Perhaps this could lead to DoS if malicious clients open a large number of connections which are not properly closed.

In addition to the practical concerns, this also disagrees with the protocol description.
"If the client fails to respond with a PONG message within the configured response interval, the server will terminate its connection."

[1]: https://github.com/nats-io/gnatsd/blob/e9b5839bf0dff0f5c453d0741efa20509c2f2aed/server/client.go#L336

**Comment by derekcollison** [comment]
Thanks, will take a look.

**Comment by camros** [comment]
@derekcollison Suggest we augment ping/pong semantics to allow the sender of a ping to include any payload and expect the same thing back in pong. This addresses many of the client issues / workarounds for ping book keeping. 

My initial tests show this can be made backwards compatible and conditional by using a version or other key out of the connect/handshake Json 

For example, when turned on, clients / senders embed a unique token in their ping and expect it back in pong:
C: ping 123
S: pong 123
C: ping 456
S: pong 123 # c knows it's a dup
S: pong 778 # c knows it never sent this

All clients and servers would need updated to slurp up everything after the ping. Gnatsd would be changed to do this and send back pongs that the client sent and as stated above be backwards compatible. Lmk if you want a pr

**Comment by camros** [comment]
One other side benefit here is syncing up flush calls for clients that use pings for that. Those clients no longer need to clean up the pending/expected state structures etc. flush can ping and look for the exact pong back.

**Comment by xorgy** [comment]
Simple solution without modifying the protocol would be to not allow it to decrement below 0. TCP guarantees the delivery so if they're connected, they should see all of the `PING`s.

If the client can only respond to pending `PING`s, that satisfies the protocol exactly.

**Comment by xorgy** [comment]
The more I look at the protocol document, the more I think that PONG should reset pout to 0 rather than decrementing it.

>`PING` and `PONG` implement a simple keep-alive mechanism between client and server. Once a client establishes a connection to the NATS server, the server will continuously send `PING` messages to the client at a configurable interval. If the client fails to **respond with a `PONG` message within the configured response interval**, the server will terminate its connection.

Note that it doesn't say you have to respond to _each_ of the PING requests, only that you have to respond with a `PONG` in time.

**Comment by derekcollison** [comment]
All good suggestions, and its on the list to be addressed before the next release.

**Comment by kozlovic** [comment]
Addressed with PR #229

**Comment by xorgy** [comment]
Wonderful. :-)
