### ISSUE TITLE
Lock external dependencies

### ISSUE THREAD

**Issue by krobertson** [nats-io/gnatsd#170]
As of 6fc9927f52b1654c5431f5aa53503c044dcb71e3, gnatsd now has an external dependency for `golang.org/x/crypto/bcrypt`. To ensure builds are reproducible, gnatsd should use godep or something similar to capture the intended sha of the dependency, else it is possible for other projects that build gnatsd itself to pull in unintended changes, or to have the build broken when dependencies are added.

From another project, where we tightly control the repos and shas of everything, updating to gnatsd 0.7.2 was broken due to this:

```
[01:09:14][Step 1/3] ../../nats-io/gnatsd/auth/plain.go:9:2: cannot find package "golang.org/x/crypto/bcrypt" in any of:
[01:09:14][Step 1/3]     /usr/local/go/src/golang.org/x/crypto/bcrypt (from $GOROOT)
```

**Comment by derekcollison** [comment]
@krobertson You should do this on your on in core. I don't want to introduce any dependency management in the main gnatsd tree at this time.

**Comment by krobertson** [comment]
Had been working with @ColinSullivan1 and @kozlovic to review a branch with it managed by Godep.

I do generally disagree. Projects should manage their own dependencies. Gnatsd and core are entirely separate projects.

If there is a breaking upstream change, it can break the build for anyone who wants to build gnatsd. Additionally, if gnatsd is built locally for releases, you checked out the dependent repo at a point of time and that is not recorded anywhere for anyone else, so builds of gnatsd are not reproducible.

**Comment by derekcollison** [comment]
There are binary releases for this purpose, please use those and do not build it from source. I do not want to introduce something like godeps at this time. Binary releases will fix this issue for you.
