### ISSUE TITLE
The Linux tarball changes permissions on the current directory

### ISSUE THREAD

**Issue by xiam** [nats-io/gnatsd#171]
Hello there,

Extracting the Linux tarball (like https://github.com/nats-io/gnatsd/releases/download/v0.7.2/gnatsd-v0.7.2-linux-amd64.tar.gz) changes the permission, time and owner of the current directory:

Before:

```
ls -la
# drwxrwxr-x 2 vagrant vagrant 4096 Jan  6 13:19 .
```

During extraction:

```
tar xvzf gnatsd-v0.7.2-linux-amd64.tar.gz
# ./
# LICENSE
# README.md
# gnatsd
```

After:

```
ls -la
# drwx------ 2 vagrant vagrant    4096 Dec  9 19:46 .
```

And if you do this as root, things looks worse:

```
sudo tar xvzf gnatsd-v0.7.2-linux-amd64.tar.gz
# ls -la
# ls: cannot open directory .: Permission denied
sudo ls -la
# drwx------ 2     500     500    4096 Dec  9 19:46 .
```

Changes permissions and owner.

I tested this on an Ubuntu 14.04 box. I honestly didn't know `tar` could do something like that, sounds more like a `tar` issue to me. And if this permission change is required for some reason you can probably add a subdirectory instead of affecting the current one. The README does not say anything about permissions.

**Comment by derekcollison** [comment]
We have a fix for this. Will do a release this week when Go1.5.3 comes out. Thanks again for the report. The one change will be an enclosing directory, e.g. ``gnatsd-1.7.4/``

**Comment by xiam** [comment]
Awesome, thanks @derekcollison.

**Comment by derekcollison** [comment]
This should be handled with new release process. Try https://github.com/nats-io/gnatsd/releases/tag/v0.8.0.beta.
