### ISSUE TITLE
will gnatsd clear invalid subcriptions?

### ISSUE THREAD

**Issue by wustrong** [nats-io/gnatsd#172]
Client's closeConnection() will delete all related subscriptions,
but when TCP conenction is broken in unexpected ways, 
while client is not closed, the subcriptions are still in subs-list of server, 
server may deliver messages to "bad" subcriptions when a "pub" is invoked.
If subscript a subject with queueGroup property, messages will  probability deliver to "bad" connection client, other clients may lost some mesage.

**Comment by kozlovic** [comment]
This is what PING/PONG are for. That is, both client and server send PING to each other and expect a PONG in return.

After a pre-determined number of PINGs out without corresponding PONGs, the connection will be closed. In case of the server, this is when the client connection will be closed and state cleaned-up.

In the server, the default PING interval is 2 minutes (`DEFAULT_PING_INTERVAL`), and the maximum allowed pings outstanding before disconnect is 2 (`DEFAULT_PING_MAX_OUT`).

**Comment by derekcollison** [comment]
The server will drop all state from a client when it detects a connection is broken, via normal TCP or via PING/PONG. If the server believes the connection/client is still valid it could select it and try to deliver a message to it, even if that message will not be processed.

**Comment by wustrong** [comment]
@kozlovic what if server deliver messages in the period of PING interval is 2 minutes, or before server detects a connection is broken? message will be lost?

**Comment by derekcollison** [comment]
Yes in the case the socket connection is lost but not detected that it is
lost, all messages sent to the socket during this period can be lost.

**Comment by wustrong** [comment]
@derekcollison can decrease  PingInterval  for more detection of connetion is broken? will it have big  effect on performence?

**Comment by derekcollison** [comment]
If you are concerned about stalled connections, of course you can lower the
PING interval. It will not affect performance in most cases.
