### ISSUE TITLE
gnatsd should seed a cluster without creating an explicit route

### ISSUE THREAD

**Issue by peterwald** [nats-io/gnatsd#176]
When adding nodes to a NATS cluster, you'd like to use a hostname that is mapped to any of the nodes in the cluster (as in a Kubernetes headless service).

    /gnatsd -cluster=nats://$MY_IP:6222 -routes=nats://nats-service:6222

Currently, this results in `nats://nats-service:6222` being added as an explicit route in the routes list. In the above example, the hostname `nats-service` is configured to return a list of A records containing each live gnatsd instance in the cluster.

1. The first problem is that `nats://nats-service:6222` is literally passed along as the route to new nodes that connect later to the cluster. Since `nats-service` is not a single IP address, each node that resolves it gets a different address. This results in the routing mesh not converging properly. 
1. Since the route is added as an explicit route, it is never removed when servers are removed from the cluster. The nodes that have it in their list constantly poll that address trying to connect (a problem if converted to an IP address at startup time).

#### Possible solution

Add a new configuration option (called `seed_routes` for purpose of discussion). `seed_routes` would function just like the routes configuration option, but would be for seeding the routes rather than explicitly specifying them. When processing the `seed_routes` option, gnatsd would

1. resolve the hostname to an IP address before adding it to the routes list and
2. add it as an implicit route rather than explicit, so it's removed when the node goes away.

NOTE: resolving the IP address is optional. That can be done outside of gnatsd if necessary.

**Comment by derekcollison** [comment]
I will read up on this and get back to you..

http://kubernetes.io/v1.1/docs/user-guide/services.html

**Comment by pires** [comment]
@derekcollison let me know if you need input on that. Both me and @peterwald should be able to clarify any questions about Kubernetes services. Particular to this issue, _headless services_ serves as DNS SRV lookups, returning the addresses for all _pods_ related to each _service_.

The reported behavior is not exclusive to Kubernetes though. As an example, Consul would behave similarly.

**Comment by peterwald** [comment]
One idea that's halfway between static routes and auto-discovery would be to allow a route to be specified as a DNS name that resolves to multiple A records (or SRV records). gnatsd could resolve all of the IP addresses and add them all as individual routes (rather than my original suggestion of it picking a random one each time). This might be simpler than some of the other ideas around cluster discovery. In that case, you'd still want the cluster to treat the routes as implicit I think.

I think that's basically just automating some of what @pires is doing outside of gnatsd.

**Comment by derekcollison** [comment]
Both are good suggestions, am looking at it, just ran out of time last night flying home.

**Comment by jduhamel** [comment]
I use consul to build multiple DNS records ie. both DNS A records that return the route for nats-srv and individual SRV records. So I post process to get the result. +1 @pires I'd love the concept of seed route as it takes a step out of the post processing.

**Comment by derekcollison** [comment]
This does seem like a good idea. Thanks to all for suggestions and comments.

**Comment by derekcollison** [comment]
Would this seed URL simply resolve to N IPs, and try ONCE to connect upon startup? If connected would we try any others? Would the connected one be elevated to explicit or remain implicit?

**Comment by derekcollison** [comment]
What about if ports are different on each host?

**Comment by peterwald** [comment]
Yes, I think we should resolve the host to N IPs and try once to connect to each. In my case, I would want the connection to be implicit, not explicit. When connecting to those IPs, if new nodes are discovered (i.e. the list is not complete), it should add the new nodes as implicit routes as well.

If the url resolves to an A record, then the ports would have to be the same of course. We could potentially use a different url format to connect using SRV records in case the ports need to be different.

**Comment by derekcollison** [comment]
Sounds reasonable, so try to connect to each one once, on the first connect use the information that server passes onto us to form the cluster.

**Comment by pires** [comment]
+1 for @peterwald comment on A vs SRV records and how to handle ports based on that.

**Comment by peterwald** [comment]
Primary issue is fixed by cef87212b94c59249fdbb07df9bc7ee13dba756b. Closing and replacing with the remaining issue #204.
