### ISSUE TITLE
gnatsd chokes on net: 127.0.0.1 in config file

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#179]
at latest gnatsd, 972b9c18ac61bed63d8ea6fbba3a9eb03b18d1b8

In OSX, one cannot reliable use 'localhost' to represent the loopback, so one must use 127.0.0.1.

However, gnatsd chokes on this simplest.config:
~~~
port: 4444
net: 127.0.0.1
~~~

with a parsing failure:
~~~
jaten@jatens-MacBook-Pro ~/src/github.com/nats-io/gnatsd (master) $ gnatsd -DV -c simplest.config
gnatsd -DV -c simplest.config
Parse error on line 2: 'Expected a top-level value to end with a new line, comment or EOF, but got '.' instead.'
jaten@jatens-MacBook-Pro ~/src/github.com/nats-io/gnatsd (master) $ 
~~~

**Comment by kozlovic** [comment]
You need to use `'` or `"` surrounding the host name.

```

**Comment by glycerine** [comment]
yep. that works. thanks Ivan. closing.
