### ISSUE TITLE
wishlist: gnatsd usable as a library

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#180]
This would be a nice-to-have feature. To facilitate testing, it would be great to be able to spin up a gnatsd from within a test. That is, to be able to instantiate and configure a gnatsd server solely as a library, without depending on file system files or command line flags.

For example, usage like this fragment
~~~
package mylibrary

import  gnatslib "github.com/nats-io/gnatsd/server"

func TestThatNeedsAGnatsServer(t *testing.T) {
        ...
        user := "myuser"
        pw := "mypw"
        host := "127.0.0.1"
        port := 4444
        serverList := fmt.Sprintf("nats://%v:%v@%v:%v", user, pw, host, port)

        // start yourself an embedded gnatsd server                                              
        parseFlags := false // ignore command line flags
        gnats := gnatslib.NewGnatslibServer(
            server.Options{
                Host:     host,
                Port:     port,
                Username: user,
                Password: pw,
            },
            parseFlags)
        defer func() {
            P("calling gnats.Shutdown()")
            gnats.Shutdown() // when done                                                        
        }()
        <- gnats.Ready // gnatsd closes this after sockets are bound

...
}
~~~

I hacked one together for now, but 

a) supplementing/allowing complete replacement of the config file (argument to -c) to avoid any need for filesystem access would be great.

b) not having to maintain it/rebase on master would be great.

Thanks for considering adding this in. Testability would greatly benefit.

Jason

**Comment by kozlovic** [comment]
You can already do that. The server can be started as a go routine. That's how the tests are starting the server. You can check in various places, but for instance, check the GO [nats client](https://github.com/nats-io/nats):  `test/test.go` file and check for the various `RunServerXXX` functions. Let me know if that solves your problem.

**Comment by glycerine** [comment]
Oh nice. Excellent. Thanks @kozlovic.
