### ISSUE TITLE
wishlist: symmetric encryption

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#181]
Dealing with TLS certs, while it does work, is a pain when all you need symmetric encryption between client and server, and between servers in a cluster.

It would be great to have a simple utility that generated an a strong (e.g. NaCl for speed) symmetric cypher secret and then just used that to encrypt all nats communication, and a simple config setting to tell nats clients and gnatsd to use that key.

The advantage is that then that key can simply be baked into cloud images. Boot a new server off that image in the cloud, and there is no need to generate new keys. Also no need to deal with expiring certs. This is the approach I took for my job queueing system Goq, and it worked out quite nicely.

**Comment by derekcollison** [comment]
There is a tremendous amount of ongoing research and very old research and applications (e.g Diffie-Hellman) on how to securely pick a symmetric key. The NATS server does not need to be involved in client only encryption, so you are free to do that at will. I have an example of the client picking the security context, etc.

https://github.com/derekcollison/nats_chat

**Comment by glycerine** [comment]
I don't think this issue should be closed -- I'm tnot alking not about payload encryption, but encryption (and authentication) of all nats traffic; which requires the server to know the key.

It is unacceptable to most users that need encryption to leak their subject lines and to allow arbitrary parties to inject traffic into the system.

**Comment by derekcollison** [comment]
I am not sure I would want to promote static symmetric keys. I would argue we should make it easier to generate a simple self-signed certificate for the server with no client certificate requirement.

Static symmetric keys have proven to be problematic.

/cc @philpennock

**Comment by glycerine** [comment]
'static' ? Certainly symmetric keys are easily rotated if desired, no?  What in particular is the concern?

In contrast to the web or authenticating a large user base, the situation is very different when running a cloud service or a backend production cluster of 10s - 100s - 1000s of machines. 

Here if the key gets compromised you just regenerate it and update it everywhere, because all locations are fully under your control. Way, way simpler. Just use ssh/scp to distribute your new key and boom, done.

**Comment by philpennock** [comment]
Live services need to be able to restart without disruption.  One symmetric key used by all parties requires simultaneous restart of all nodes, client and server, with error handling for the duration where everything appears "bogus" to gracefully degrade ... in the absence of the main communication layer between nodes.  This is problematic for reducing overall complexity.

There's a reason that popular deployed use public key crypto, to act as an identity and introducer to negotiate symmetric keys.  X.509 and TLS have many problems, but before replacing them with a simpler subset one first needs to identify what the required subset actually is instead of going for the minimal possible and then trying to retrofit fixes once systems are already deployed.

**Comment by glycerine** [comment]
Hi Phil, 

That is certainly a reasonable concern. It's a rationale for allowing a small set of keys at once to enable key rotation.

Moreover a cert system has the exact same problem. In either case, if the system doesn't support more than one server identity at once, you can't change that identity incrementally without a full restart of all nodes.

Best,
Jason

**Comment by derekcollison** [comment]
I do plan on adding in additional identities, still think simple server self-signed cert with no requirement for client certs is best way to secure the client/server transport. You can pick how long the cert is valid for as well when generating it.
