### ISSUE TITLE
multiple user/password stanzas

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#182]
Are multiple authorization stanzas supported by the gnatsd config file?  To upgrade a cluster's credentials incrementally, without full restart at once of all nodes, multiple accounts will be needed.

e.g. to support login by either alice or bob:

~~~
authorization {
  user:     alice
  password: T0pS3cr3t
  timeout:  1
}
authorization {
  user:     bob
  password: FinickyNoodle
  timeout:  1
}
~~~

**Comment by glycerine** [comment]
The options block in [github.com/nats-io/gnatsd/server/opts.go](https://github.com/nats-io/gnatsd/blob/master/server/opts.go#L30) suggests only a single username and pw are supported at present.

~~~
// Options block for gnatsd server.                                                                                                                           
type Options struct {
    ...
    Username           string        `json:"user,omitempty"`
    Password           string        `json:"-"`
    ...
}
~~~

So something like this would be needed

~~~
type Account string {
 Username string
 Password string
}
...
// Options block for gnatsd server.                                                                                                                           
type Options struct {
    ...
    Accounts []Account
    ...
}

**Comment by derekcollison** [comment]
Not at this time bit are on the roadmap for sure.

**Comment by camros** [comment]
@glycerine can you outline/confirm your goal vs a solution if that makes sense.

Here is what I understand from your description above:

You would like support to _upgrades to a nats cluster_ without causing availability loss to nats clients using the cluster. An upgrade could be any change, whether a new version of gnatsd, or a config change (e.g., to _change auth tokens_)

**Comment by glycerine** [comment]
@camros, right, your description seems spot on to me.

**Comment by mcqueary** [comment]
Duplicates #129 -- We'll address this as part of that requirement.
