### ISSUE TITLE
are subscriptions lost on reconnect?

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#193]
I ran a long-running nats-subscriber, which was receiving traffic just fine.

Then I took the gnatsd down, and brought it back up again.

Observed: The subscriber no longer received any messages.

Expected: I expected that the subscriptions would be remembered in the client-side of the connection, and supplied to the server upon reconnect. Does that not happen?  Automatic reconnect isn't very useful without a subscription memory.

**Comment by derekcollison** [comment]
Yes by default most clients will not only reconnect but will also re-subscribe automatically to the existing subjects. Which client (+version) did you notice the behavior?

**Comment by mcqueary** [comment]
Jason, the client should resend subscriptions on successful reconnection, assuming that it did reconnect successfully. Was the ReconnectedCB invoked?

**Comment by glycerine** [comment]
version info:
~~~
jaten@jatens-MacBook-Pro ~/src/github.com/nats-io/nats (master) $ git log
commit 6a83f1a633cfbfd90aa648ac99fb38c06a8b40df
Merge: 99bc8d7 5d5979c
Author: Derek Collison <derek.collison@gmail.com>
Date:   Wed Jan 20 12:54:03 2016 -0700

    Merge pull request #131 from AnatoliiPrylutskyi/pub_sub_global_error

    Fix error in next message after encode/decode fail in previous
~~~

I'll add a reconnect handler and let you know if its called.

**Comment by derekcollison** [comment]
Look for the disconnect, closed and reconnect CBs. Also monitor the server itself with monitoring enabled and look at /connz?subs=1 to see the connections with the subscriptions that are active listed.

**Comment by glycerine** [comment]
Thanks for the monitoring hints about /connz?subs=1 ... will post update shortly (though sleepy, might be tomorrow).

**Comment by mcqueary** [comment]
Jason, if you can, and it's practical, start `gnatsd` with `-DV` so we can see what's going on during and after the reconnect.

**Comment by glycerine** [comment]
-DV on, thanks.

**Comment by glycerine** [comment]
Found at least one problem with my code; it was making more more nats connection that intended. I'll open a new ticket with full details (thanks for all the debugging and diagnostics hints) if I see subscription loss and document it. Closing this one so I don't forget to.

**Comment by derekcollison** [comment]
What was the most useful tool that help diagnose your problem?

**Comment by glycerine** [comment]
The http://127.0.0.1:8222/connz?subs=1 page told me I had an extra client connection I wasn't expecting, so that. 2nd place: setting the Names option let me determine which connection was duplicated.
