### ISSUE TITLE
how to determine the nats-client port number?

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#194]
I'm looking at nats-top at the clients listed. I see two clients, but they are only distinguished by having different ports.

~~~
gnatsd version 0.7.3 (uptime: 16m53s)
Server:
  Load: CPU:  0.0%  Memory: 10.4M  Slow Consumers: 0
  In:   Msgs: 6  Bytes: 18.2K  Msgs/Sec: 0.0  Bytes/Sec: 0   
  Out:  Msgs: 0  Bytes: 0  Msgs/Sec: 0.0  Bytes/Sec: 0

Connections: 2
  HOST                 CID      SUBS    PENDING     MSGS_TO     MSGS_FROM   BYTES_TO    BYTES_FROM  LANG     VERSION
  127.0.0.1:54028      1        0       0           0           0           0           0           go       1.1.7
  127.0.0.1:54027      2        0       0           0           6           0           18.2K       go       1.1.7
~~~
How do I tell what port a given client has bound? So I can tell which client is getting traffic through?

Looking at github.com/nats-io/nats/nats.go: the nats.Conn structure looks as though it has a conn net.Conn, but it is private so I can't ask it what its port is.

Suggestion: make that net.Conn public, or provide AddressPort() method that returns the IP and Port in use by the client.

**Comment by derekcollison** [comment]
You can name your clients, depending on which client library you use. But if set, will show up in /connz and the top application.

**Comment by glycerine** [comment]
Using the Go library... I'm guessing Name is it.
~~~
// Options that can be passed to Connect.

// Name is an Option to set the client name.
func Name(name string) Option {
	return func(o *Options) error {
		o.Name = name
		return nil
	}
}
~~~
