### ISSUE TITLE
prevent accumulation of "zombie" routes when dynamically scaling NATS cluster

### ISSUE THREAD

**Issue by peterwald** [nats-io/gnatsd#204]
When using a service like kubernetes, the cluster is scaled down by killing nodes. When nodes are recreated, they come up with a different IP address each time.  This is a fairly common operation. For example when upgrading NATS itself, a rolling update would be propagated across a cluster by scaling up the new version while simultaneously scaling down the old version.

Currently, when a node goes down, NATS keeps trying to reconnect to the route at that node continuously (forever AFAIK). Since a node is unlikely to ever come online again at that same IP address, the nodes can accumulate a list of bad routes that they are constantly polling.

It seems that we need some strategy for pruning these dead routes.

**Comment by pires** [comment]
Shoudln't route `PING/PONG` take care of this?

**Comment by peterwald** [comment]
Seems like maybe it could, but it doesn't. I think if I remember right it's because the routes are added as explicit and so are never dropped.

**Comment by peterwald** [comment]
Figured out i was running an outdated build. This has been fixed in master.
