### ISSUE TITLE
Clients may not know why a handshake failed when using tls

### ISSUE THREAD

**Issue by camros** [nats-io/gnatsd#205]
Clients should always know why a connection handshake failed to ensure reconnect and other logic works correctly. 

From sniffing and traces kind of stuff  this looks to be a half close timing related issue under high load where the client believes the tls handshake failed rather than the auth err making it back.

**Comment by derekcollison** [comment]
I believe it works as it should. Under heavy load it may in fact close the connection, which would look like a tls fail on the client side before the client can read the -ERR.

https://github.com/nats-io/gnatsd/commit/9fac37dd66291264f228c9929204e67c9747626f
