### ISSUE TITLE
In-process hosting of gnatsd in a .NET server application?

### ISSUE THREAD

**Issue by drauch** [nats-io/gnatsd#208]
Is it possible to host the gnats daemon in-process within a .NET server application? This would simplify our deployment process.

**Comment by ColinSullivan1** [comment]
Not directly - the NATS server is an executable written in go.

Two options you have are to include the NATS server (gnatsd) as an executable in your application and invoke it from your application, or another option you can look into, but would require more work, would be compiling the NATS server as as library and deploying it as unmanaged code in your application.  The main routine, Start(), is exported.

Typically applications do not embed the NATS server.  Perhaps we there's another alternative.  Can you share more of your architecture?

**Comment by drauch** [comment]
Thank you for the background information, we're going to use the Go standalone executable. This seems the way-to-go.

**Comment by AndreiPashkin** [comment]
@ColinSullivan1, in some use-cases it might be not possible to launch separate processes - for example in case of an iOS application (which could be written in Go).

**Comment by ColinSullivan1** [comment]
@AndreiPashkin , yes, if you wrote your iOS application in go, you could certainly embed the server.  If taking that route, I'd suggest running the server as a [leaf node](https://nats-io.github.io/docs/leafnodes/) when connecting to your remote NATS server/cluster.
