### ISSUE TITLE
feature request: cluster membership changes sent to client connections

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#209]
Because clients may be started before servers in a cluster, and server membership in a cluster may change, it is a chicken-and-egg problem to tell all clients about all servers. And impossible to do with a static configuration file for a client.

However, the fault tolerance guarantees of a gnatsd cluster depend critically on clients knowing about all servers in the cluster.  If clients do not know about all currently running servers, then the system is no longer fault tolerant.

Hence this issue requests a mechanism to lets gnatsd tell clients about all servers in the cluster (perhaps in a heartbeat published on a "system topic"; perhaps in a reply to a request sent directly to the gnatsd server); so the clients wishing to be fault-tolerant can keep up to date with a dynamic server-cluster membership.

It could simply be a "system" topic that clients can subscribe to, that gnatsd itself publishes on every when a request for such information is made. 

The part that would require some nats client smarts would be having the Go nats client automatically update that list of servers into its connection information.  This would allow me to user the infinite auto-reconnect feature of the Go client in a fault-tolerant manner.

**Comment by glycerine** [comment]
from slack conversation with Larry McQueary

> That's already on the roadmap, so yes!
> 
> Upon a change in cluster membership, a new INFO message will be sent to clients. The new INFO message will contain the list of cluster member urls(edited)
> 
> Q: but what If I’m disconnected at the time and miss that message?
> 
> A: You'll get a new one on reconnect.
> 
> The message is sent on connection, and anytime membership changes.
> 
> The point is actually that you only need to know a seed server to connect, then you immediately learn of all cluster members
> 
> INFO is the very first thing you get from the server on successful TCP connection
> 
> (And reconnection is not special -- it is simply a new connection on which the client resubmits its subscriptions)

**Comment by mcqueary** [comment]
Duplicates #126
