### ISSUE TITLE
drop rates very high, lots of messages lost

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#217]
gnatsd 0.7.5, go client 1.1.9, both on linux amd64 under go1.5.3. The server is running in a 2 node HA cluster, however publisher and subscriber are only subscribing to a single sever (the same gnatsd server; the clients only know about one of the two gnatsd servers in the cluster).  Publisher, gnatsd, and subscriber are all running on the same linux host, and TLS certs are being used on both ends.

I'm seeing lots of message loss when publishing on various topics. My receiver is connected well in advance, and I observe message loss like this:

~~~
 subject: a  915565 observed out of 1980235 transmitted (46% transmitted, 54% lost)
 subject: b  204161 observed out of 259859 (79% transmitted)
 subject: c    3380 observed out of out of 3417 (99% transmitted)
 subject: d    3834 observed out of 3834 (100% transmitted)
 subject: e     679 observed out of 679 (100% transmitted)
 subject: f      56 observed out of 56 (100% transmitted)
 subject: g       1 observed out of 68 (1.5% transmitted, 98.5% lost)
~~~

**Comment by glycerine** [comment]
What didn't work: I tried adding Flush() calls on the publisher side after every 1000 messages, and after the last message sent, but I see no change in loss rates. They remain high. This seems to suggest the server or the receiver is dropping messages.

**Comment by camros** [comment]
@glycerine Can you share a code snippet that shows your receiver and subscriber? Am guessing there is something wrong there causing some issues.

**Comment by derekcollison** [comment]
Please attach an error handler to your client.

Example here: https://github.com/nats-io/nats/blob/master/test/sub_test.go#L531

**Comment by derekcollison** [comment]
You can also try SetPendingLimits if the client is a slow subscriber.

See here for more information: https://godoc.org/github.com/nats-io/nats#Subscription

**Comment by glycerine** [comment]
Thanks for the suggestions.  It's not trivial to extract a minimal reproducing case just now, and I think there's lots of good info from the reporting and error handler:

Turning on the error handler, the consumer is getting lots of errors like: "nats: slow consumer, messages dropped"

When I check the stats with the subscription reporting functions, I do see that many messages are dropped:

SubReport{Delivered:1110000, Dropped:1081447, MaxMsgsQueued:65537, MaxBytesQueued:67121072, PendingMsg:30436, PendingBytes:67105645, LimitMsg:65536, LimitBytes:67108864, SubscriptionActive:true}

I'm sending at a rate of 25-30K messages (on average about 1k bytes each in size) per second.

It looks like what is happening is gnatsd is calling the consumer slow, and dropping messages.  I don't think its really that the consumer is actually slow, but rather the producer is just much faster than gnatsd, and is overwhelming the gnatsd internal buffers.

**Comment by kozlovic** [comment]
When the client gets "slow consumer", it means that the messages have been accumulating in the client library (the server is OK delivering to the library), because the message callback is too slow to process the messages. You can see that you have hit the limit of messages (default 65536). As Derek suggested previously, try to bump this limit with `SetPendingLimits`.
Note: when the server declares a client a slow consumer, it closes the connection. If you don't see the client being reconnected, then again, the issue is more on the client side (callback "too slow").

**Comment by glycerine** [comment]
@kozlovic Ah, thanks for clarifying that. I misinterpreted.

**Comment by kozlovic** [comment]
And by "too slow" to be honest, any callback doing real work will probably causes messages to pile-up if you have a fast producer. 
So you can either increase the pending limits up to the point you think you think is reasonable, or throttle the sender.

**Comment by glycerine** [comment]
@kozlovic, Is there a way to deliver a batch of messages in a callback (as in, everything the client library has at the moment), instead of one-by-one?

**Comment by kozlovic** [comment]
No, but that would not change much. If we consider that the slow down is in the processing of a message, the callback would then have this processing x the number of passed messages. In the meantime, messages arriving from the fast producer will accumulate, leading to slow consumer...

**Comment by glycerine** [comment]
@kozlovic Thanks for the insight. To be on the safe side, it sounds like I'm going to need to apply back pressure by throttling the producer.

**Comment by kozlovic** [comment]
That's a good approach.

**Comment by ColinSullivan1** [comment]
@glycerine ...another option could be to distribute the work load through queue subscribers, assuming you have message atomicity.

**Comment by glycerine** [comment]
Thanks for the suggestion @ColinSullivan1.

For anyone else encountering this same issue, the quick fix is raising the limits, the code for that goes like so:
~~~
    msgLimit := int(1e7)
    bytesLimit := int(1e10)
    err = fm.subscription.SetPendingLimits(msgLimit, bytesLimit)
    if err != nil {
        return fmt.Errorf("Got an error on subscription.SetPendingLimit(%v, %v) for subj:'%s': %v\n", msgLimit, bytesLimit, subj, err)
    }
~~~

(Of course this doesn't introduce any back-pressure, so is still vulnerable message loss)... but for now, with these larger nats-client buffers, the receiver is keeping up and I'm seeing 0 dropped messages:

~~~
subscription report = '&profiler.SubReport{Delivered:1600001, Dropped:0, MaxMsgsQueued:1116620, MaxBytesQueued:708757778, PendingMsg:648147, PendingBytes:666311670, LimitMsg:10000000, LimitBytes:10000000000, SubscriptionActive:true}'
~~~
 
So I have a solution and I understand the issue much better now.

Closing ticket.

**Comment by glycerine** [comment]
for future reference --

https://github.com/glycerine/go-sliding-window

**Comment by raphaelLacerda** [comment]
My solution to the problem: Fast producer and slow consumer was to scale up the consumer.

I was losing a lot of messages


Scaling up should do the trick
