### ISSUE TITLE
Address lint issues

### ISSUE THREAD

**Issue by camros** [nats-io/gnatsd#221]
We need to make a pass to address golint output: https://goreportcard.com/report/github.com/nats-io/gnatsd.

Specifically, make a pass to address comments for exported functions variables. Less focus on ALL_CAPS and other warnings for now.

**Comment by mcqueary** [comment]
I believe #224 should close this, at least as defined here (i.e. hitting the important stuff). @ColinSullivan1, please confirm and close if true.

**Comment by camros** [comment]
@mcqueary yes, it does; created this when we discussed via email

**Comment by ColinSullivan1** [comment]
@mcqueary @camros Correct - #224 addresses this issue.

**Comment by mcqueary** [comment]
Thanks, guys!

On Sun, Mar 20, 2016 at 10:32 AM, Colin Sullivan <notifications@github.com>
wrote:

> @mcqueary <https://github.com/mcqueary> @camros
> <https://github.com/camros> Correct - #224
> <https://github.com/nats-io/gnatsd/pull/224> addresses this issue.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/gnatsd/issues/221#issuecomment-198960026>
>



-- 
*Larry McQueary* | Director, Messaging Technology
larry@apcera.com | @mcqueary | github.com/mcqueary
