### ISSUE TITLE
gnatsd reports dead and gone connections to nats-top

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#223]
Re https://github.com/nats-io/nats-top/issues/32, gnatsd should stop reporting connections (in /connz?) whose keep-alives have failed some N times in a row. I currently see connections who have been dead a gone for 5 days still reported by gnatsd to nats-top. These processes died without unsubscribing.

**Comment by derekcollison** [comment]
Do you have a test case to reproduce?

**Comment by glycerine** [comment]
Just happened to notice it in the nats-top display, so no formal test case.

Manual steps: I have a client subscribe connect to the server with 1 subscription, and then I kill -9 the subscriber, so it can't unsubscribe before it dies. The subscriber isn't being sent any traffic by any other subscriber. It still shows up days later in nats-top.

**Comment by glycerine** [comment]
Ok, wierd. the process named replayer is dead, but I see another process holding that port open using lsof. My bad, there is a live process, and I must have mixed up nats name with the program name. Closing tickets.
