### ISSUE TITLE
case of a node failure

### ISSUE THREAD

**Issue by deviantmk** [nats-io/gnatsd#225]
Hi
So lets say in a cluster of 3 nodes, we push a message but a node fails before the message is delivered, is there a chance that the message would be lost or the other 2 nodes already have it and will deliver it (once or twice?)

or in other words, when a message is pushed to nats.io, is the message acknowledge when its present in all 3 nodes or just that one node where its pushed to and then is redistributed to the rest of the nodes.

**Comment by kozlovic** [comment]
There is no acknowledgment at all in NATS. This is a "fire-and-forget" mechanism, in that when a message is sent, there is no guarantee that it is going to be delivered. At the application level, one can use Request (with timeout) to ensure that the receiver gets the message, and resend if the reply is not received within the timeout.

At the server level, it's just a send. So if your application sends to server A, and A sends to B and C (assuming there is an interest on both), there is no guarantee that B and/or C receives it, and therefore no guarantee that subscribers attached to it receive it either. Again, the sender can get around that using request/reply if guarantee delivery is desired.

Note that we have a persistence layer in the works.

**Comment by deviantmk** [comment]
thanks
