### ISSUE TITLE
Question: at-least-once delivery

### ISSUE THREAD

**Issue by drauch** [nats-io/gnatsd#228]
According to the documentation NATS guarantees at-most-once delivery of a message, however, at-least-once delivery is not guarnateed.

I can iamgine only two scenarios where at-least-once delivery fails:
* subscriber is not reachable anymore
* subscriber cannot process the high load anymore

Both scenarios should lead to a forceful subscriber disconnect by the server.

Therefore, does the following assumption hold in general?

> If at-least-once delivery cannot be fulfilled for a given subscriber, the subscriber is forcefully disconnected by the server.

Or the other way round:

> As long as a subscriber is connected, he is guaranteed to receive all messages at-least-once and at-most-once (and in-order, if there is only a single publisher).

**Comment by derekcollison** [comment]
Neither will hold when publisher and subscriber are connected to different servers in a cluster and the route between the servers is partitioned.

**Comment by derekcollison** [comment]
The only statement we can make is the following.

For any given publisher, messages produced will be delivered in order with at most-once delivery semantics per subscriber.

**Comment by drauch** [comment]
I understand, thank you for your clarification.
