### ISSUE TITLE
Vendoring tool

### ISSUE THREAD

**Issue by pkieltyka** [nats-io/gnatsd#242]
Hey guys, I see you've vendored the deps, awesome stuff.. which vendoring tool are you using btw? I just wanted to bring to your attention the awesome package: https://github.com/kardianos/govendor.

Similarly to your vendor/manifest file it creates: vendor/vendor.json

**Comment by derekcollison** [comment]
https://github.com/FiloSottile/gvt

**Comment by pkieltyka** [comment]
gvt looks pretty nice as well.
