### ISSUE TITLE
Prometheus metrics

### ISSUE THREAD

**Issue by lukaf** [nats-io/gnatsd#243]
Hi,

Would it be acceptable to have metrics exported in Prometheus format as a part of existing monitoring? I'd be happy provide a PR for it.

Thank you!

**Comment by derekcollison** [comment]
Doe they not take JSON?

**Comment by lukaf** [comment]
Unfortunately not, it uses its own data format: https://prometheus.io/docs/instrumenting/exposition_formats/#text-format-details

**Comment by derekcollison** [comment]
ok, so the question would be then whether or not we do a small converter application, or we try to shoehorn the varz endpoint with a qualifier for formatting to this input format. For now, feels like a small utility app may be the way to go.

**Comment by lukaf** [comment]
Thanks for the input, but I'm not sure what you mean by utility app? A separate tool that converts from JSON to Prometheus format?

My initial thought was adding a new handler to https://github.com/nats-io/gnatsd/blob/master/server/monitor.go and exposing it along the others.
All the metrics are already there so no additional processing would take place.

**Comment by derekcollison** [comment]
Yes a separate application that takes the JSON from NATS and translates to prometheus. I am not convinced that baking this specialized format directly into NATS makes sense.

**Comment by lukaf** [comment]
Ok, cool, makes sense. Thanks

**Comment by markuslindenberg** [comment]
I'm not totally convinced that it makes sense to rely on an external exporter for prometheus. As I understand it /varz is supported by borgmon (Google internal / proprietary), while Prometheus is considered (by Google, see the SRE book) a free and open implementation of the same concepts which is gaining a lot of traction everywhere currently.

So I guess a lot of people can make much more use of native Prometheus support than a varz endpoint.

**Comment by glerchundi** [comment]
And now it's part of CNCF (Cloud Native Computing Foundation)*. The same foundation that Apcera belongs. ;)

*: https://prometheus.io/blog/2016/05/09/prometheus-to-join-the-cloud-native-computing-foundation/

**Comment by derekcollison** [comment]
Regardless of where this functionality should live, /varz in its current form is depended upon and can not be changed except to be added to. With microservices it feels the best place to put this is in a separate component, not as part of gnatsd itself.

**Comment by markuslindenberg** [comment]
I had a closer look at gnatsd's `/varz`. It's conceptually broader than what Prometheus' `/metrics` does as Prometheus only deals with float64 timeseries. So yes I agree a seperate component is the best option to get gnatsd metrics into Prometheus right now. 

Prometheus calls those components *exporters*, so I have created a [nats_exporter](https://github.com/markuslindenberg/nats_exporter). Currently the `/varz` and `/subsz` endpoints are scraped and all available metrics are exported to Prometheus. 

The exporter should be fully functional and stable, although I still have to work through the details of Prometheus' [best practices](https://prometheus.io/docs/instrumenting/writing_exporters/) document. So I'll likely have to rename some metrics and meaningful help strings are missing. Also `/routez` metrics are not yet implemented and I'm thinking about if and how to make use of the `/connz` data.
