### ISSUE TITLE
performance issue?

### ISSUE THREAD

**Issue by s921102002** [nats-io/gnatsd#264]
Hi all,
There is a very strange problem that when the publish string contain ' '  (space)  and the performance become 4-5x slow. below is  the code 

in my computer execution time

3.3993399s (first)
15.871587s (second)

The two test strings are the same length

I test such as "1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 "

if there are more spaces and the performance is very slow.

I don't trace the problem occur in client or server, but I test c# go and c client, this situation always happen.

my env:
I use simple server, no cluster and no parameters and just execute the executable in local 
server version
0.7.2
0.8.0 beta2

golang 1.6.2

windows 7 32bit

```go
package main

import (
	"fmt"
	"github.com/nats-io/nats"
	"time"
)

func main() {
	
	nc, _ := nats.Connect("nats://127.0.0.1:4222")

	
	x := []byte("012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890")
	t1 := time.Now()
	for i := 0; i < 100000; i += 1 {
		nc.Publish("Test", x)
	}
	t2 := time.Now()
	diff := t2.Sub(t1)
	fmt.Println(diff.Seconds())
	
	x2 := []byte("12345 6789012345 6789012345 6789012345 6789012345 6789012345 6789012345 6789012345 6789012345 6789012345 67890")
	t3 := time.Now()
	for i := 0; i < 100000; i += 1 {
		nc.Publish("Test", x2)
	}
	t4 := time.Now()
	diff2 := t4.Sub(t3)
	fmt.Println(diff2.Seconds())
}
```

**Comment by kozlovic** [comment]
Thanks for the report, we are going to have a look.

**Comment by derekcollison** [comment]
You should put a call to nc.Flush() before grabbing the end time for each run..

**Comment by kozlovic** [comment]
Adding the Flush() would make it more fair. But even without, I am unable to reproduce this issue using your program. Here is the output (on a Windows 64bits VM) with 10,000,000 messages sent:
```
e:\go\src\github.com\nats-io\nats>go run examples/test.go
7.515625
7.296875
```
I am using master for both server and go client.

**Comment by kozlovic** [comment]
I think that in your case, the `nc.Flush()` may be the answer. Note that by default, the wait is 60 seconds. If this call was to fail with a timeout on your machine, you can call `nc.FlushTimeout()` and pass the desired timeout instead.

**Comment by s921102002** [comment]
Thanks for your reply.
But I test on win7 x64 it's also not working
The situation always happen, and I already download gnatsd master and nats matser from github and rebuild them.

I think there must have some problem here.
The above code I use normal string first and abnormal string second, this time I change sequence the result is the same, and I replace the abnormal string, and use "1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ",  and it take long time to execute

68.016s
21.836s

In fact I have 2 questions

Q1.100000 msgs take 68.016s with flush command, is it right? it's means one msg avg take 0.68"ms"? why so slow? (I think it can down to below 50-100 microsecond, I use local machine test, there's no network latency problem)

Q2.Because I test at least 2 computers, and the problem always exist, so I think maybe something wrong, but I don't know what cause this problem or maybe environment problem or my code is wrong? or something else wrong, so how can I do to help you to reproduce this issue?

ps. when I test this issue there only start gnatsd and the test program and there's no any subscriber

Thanks every one.

below is new code and a picture include code and environment 
```
package main

import (
	"fmt"
	"github.com/nats-io/nats"
	"time"
)

func main() {
	
	nc, _ := nats.Connect("nats://127.0.0.1:4222")

	
	//x := []byte("012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890")
	x := []byte("1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 ")
	t1 := time.Now()
	for i := 0; i < 100000; i += 1 {
		nc.Publish("Test", x)
		nc.Flush()	
	}

	t2 := time.Now()
	diff := t2.Sub(t1)
	fmt.Println(diff.Seconds())


	//x2 := []byte("12345 6789012345 6789012345 6789012345 6789012345 6789012345 6789012345 6789012345 6789012345 6789012345 67890")
	x2 := []byte("012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890")
	t3 := time.Now()
	for i := 0; i < 100000; i += 1 {
		nc.Publish("Test", x2)
		nc.Flush()	
	}
	
	t4 := time.Now()
	diff2 := t4.Sub(t3)
	fmt.Println(diff2.Seconds())
}
```
![test](https://cloud.githubusercontent.com/assets/19200719/15061752/9b06828e-136b-11e6-8dc1-f15e127c3196.PNG)

**Comment by kozlovic** [comment]
We suggested that you put the `nc.Flush()` at the end of the loop, before capturing the time, not inside each iteration. That will speed-up things. With Flush inside the loop, you have a round-trip with the server for each message.
As for the difference, I don't know. The number I gave in my previous update was using your sample code on a Windows VM, with 10,000,000 messages, and it ended in less than 8 seconds.

**Comment by kozlovic** [comment]
As an experiment, you could start `gnatsd` with the `-DV` parameter, as: `gnatsd -DV`, and change your test program to send only say 10 messages in each run and provide the output?

**Comment by kozlovic** [comment]
Also, attached is my run with your original test program (adding nc.Flush()). Notice that I send 1,000,000 messages and it takes less then 8 seconds.

![screen shot 2016-05-05 at 7 49 10 pm](https://cloud.githubusercontent.com/assets/13736691/15062168/a70c9c06-12fa-11e6-8ae9-678a4c9b812b.png)

**Comment by s921102002** [comment]
Thanks your reply
I test the 2 mention test, -DV and change Flush() position and here is the result
Result1:
![dv](https://cloud.githubusercontent.com/assets/19200719/15062422/7c57f104-1372-11e6-9e51-1b7c21d457ce.PNG)

Result2:
![test2](https://cloud.githubusercontent.com/assets/19200719/15062423/7c5869ea-1372-11e6-81bd-6999a842e9ac.PNG)

**Comment by s921102002** [comment]
Hi all,
I'm so sorry for this issue, I found these computers have installed anti-virus program.
I remove the anti-virus program, and it looks ok.
Thanks All. :)

**Comment by kozlovic** [comment]
No worries, glad to know that the issue is resolved!
