### ISSUE TITLE
dynamic routes?

### ISSUE THREAD

**Issue by 1N50MN14** [nats-io/gnatsd#272]
I've set up a simple cluster where nodes are dynamically launched (one by one) and my docker container populates the routes (pulled from a service discovery) and appends them to `gnatsd.conf` prior to launching `gnatsd` itself in each node. 

That's basically emulating `Example: Setting a gnatsd cluster one by one` per http://nats.io/documentation/server/gnatsd-cluster/ except that it's automated.

Given clients randomly connect to cluster nodes, the only way to ensure subscription messages are received is by strictly publishing messages to the latest added node in the cluster which holds the routes to all other nodes. 

This means to ensure messages are sent to subscribers regardless the node they are connected to I will either need to keep track of the newest node in the cluster that is alive and use that or restart all cluster nodes and update their routes.

A much simpler way would be if I could just tell each node in the cluster "here, add this route please" through an AP call. Is such a thing possible in gnatsd?

**Comment by 1N50MN14** [comment]
Never mind, restarting manually

**Comment by derekcollison** [comment]
There is no way to programmatically add routes at this time, but it is fairly easy to build a cluster with auto-discovery and seed nodes.

https://github.com/nats-io/gnatsd/blob/master/README.md#clustering
