### ISSUE TITLE
Detected duplicate remote route error that shouldn't happen?

### ISSUE THREAD

**Issue by 1N50MN14** [nats-io/gnatsd#274]
Given `Server A` with a route to `Server B` and `Server B` with route to `Server A` I get the error `Detected duplicate remote route "KogwJt2tTIGO8E0blTrqlT"` this shouldn't happen pr http://nats.io/documentation/server/gnatsd-cluster/

But if I don't set any routes of `Server A` and set one route from `Server B` to `Server A` then the issue doesn't happen, problem then is that if I publish to `Server A` then subscribers on `Server B` wont' receive the message.

I'm using v0.8.0, any ideas?

**Comment by derekcollison** [comment]
Given Server A and Server B, there needs to be one connection between them. When you configure A to solicit B, and B to solicit A, if both connect at the same time the system will prune the duplicate route connection based on server ids.

**Comment by 1N50MN14** [comment]
So given Server A is launched first, Server B is launched afterwards and it establishes a route to Server A, if I a client connected to Server A publishes a message to a topic, subscribers connected to Server B do not reveive the message. It's like the route is a one way connection, the other way around (publishing to Server B) delivers the message to topic subscribers on both Server A and Server B. Is this the expected behaviour?

**Comment by derekcollison** [comment]
No that is not expected. Any route is full duplex, meaning interest and data flow the same way regardless of who solicited and created the route.

**Comment by kozlovic** [comment]
The only caveat would be if you pulish before the route is fully established (server with subs interest sending its interest to peer).

**Comment by 1N50MN14** [comment]
Oh I *think* this might be it @kozlovic!! more precisely the subs - the below code would result in the message being delivered to the first server only (nc1), however, if I wrap `nc1.publish()` with a timeout then both clients receive the message. The route between both servers is long established.

```javascript
var nc1 = nats.connect('nats://46.101.140.203:4222');
var nc2 = nats.connect('nats://46.101.140.203:4333');

nc1.subscribe('foo', function(msg) {
  console.log('nc1 received a message: ' + msg);
});

nc2.subscribe('foo', function(msg) {
  console.log('nc2 received a message: ' + msg);
});

nc1.publish('foo', 'Hello World');
```

**Comment by derekcollison** [comment]
Since the code is in Node.js, and by default is asynchronous, there are no guarantees with the current code that the state has propagated from the client to the cluster. All that can be guaranteed from above is the the subscription for nc1 will happen before the publish to nc1 since order is preserved and guaranteed on a per connection/client basis. So you are guaranteed to get the message on nc1. If you want to guarantee you get it on nc2, you need to only publish to nc1 after a succesful flush call for nc1.

```javascript
var nc1 = nats.connect('nats://46.101.140.203:4222');
var nc2 = nats.connect('nats://46.101.140.203:4333');

nc1.subscribe('foo', function(msg) {
  console.log('nc1 received a message: ' + msg);
});

nc2.subscribe('foo', function(msg) {
  console.log('nc2 received a message: ' + msg);
});

// Make sure subscription is processed before sending publish.
nc2.flush(function() {
  nc1.publish('foo', 'Hello World');
});
```

**Comment by 1N50MN14** [comment]
Got it I now understand how this works thanks @derekcollison.

Two last questions if I may:

1. What happens to subscriptions when the client loses and recovers connection to the server, i.e. do I need to listen to `reconnect` and re-establish the subs or is that handled internally; if so is that also the case when the client reconnects to a different server (passing `servers` to the constructor).

2. Instead of having "unique" routes from each server X pointing to all other servers (that don't already have a route to server X), I'm thinking of a topology where I have a small "inner ring" of three servers and a bigger "out ringer" in which each server will point to the three servers in the inner ring. This way I can scale out the cluster without having to recalculate the routes of all servers and restart the (obviously this is automated, it's the downtime I'm thinking of). In theory this should work right?

3. Is it possible to add a new route to an existing client without destroying it first? can I append a route directly with the `servers` property in the client?

Thank you

**Comment by kozlovic** [comment]
1. Handled by the library. On reconnect, subscriptions are automatically resent.
2. Yes, should work. See 3.
3. No, but we have plan for cluster info to be asynchronously sent to clients when topology changes, so that client library can update the list of its server in case of a reconnect.

**Comment by 1N50MN14** [comment]
Awesome this clarifies things for me, thank you very much for the help!
