### ISSUE TITLE
Differentiate between recoverable and non recoverable ERR

### ISSUE THREAD

**Issue by danielwertheim** [nats-io/gnatsd#277]
Documentation states that most `-ERR` replies are non recoverable. Would be great to differentiate between these, e.g: `-ERR` vs `+ERR`; that way you as a client developer would know if you immediately should try and reconnect or if you should `PING` to see if still alive.

**Comment by derekcollison** [comment]
-ERR is a parseable state from a client's perspective. If the server state is not recoverable then the server will swiftly terminate the connection after the ERR message has left the server.

**Comment by danielwertheim** [comment]
The idea would be if you get `-ERR` you know as a client dev, you could terminate immediately and potentially reconnect, since the server indicates non recoverable `ERR`, even by the first char `-`.

`+ERR` (or something) would mean, you might still be alive and should check.

**From docs:**
Protocol error messages which do not close the connection:
- -ERR 'Invalid Subject': Client sent a malformed subject (e.g. sub foo. 90)

which then would be `+ERR 'Invalid Subject....'`.

But I guess it's better as a client to upon any `ERR`, check if still alive and if not, potentially reconnect to a node in cluster depending on config from consumer of client? Or perhaps not even do the check?

**Comment by derekcollison** [comment]
We want that with the server, and is subject to change. So as a client, when you process an error, assume nothing, don't check anything. If the server can not recover it will terminate the connection. In the future we reserve the right to possibly recover the state and not have to terminate.
