### ISSUE TITLE
Send only one ERR

### ISSUE THREAD

**Issue by danielwertheim** [nats-io/gnatsd#278]
When e.g. sending a completely invalid command like `FAIL` it would make more sense as a client dev to only get one `-ERR` back. Otherwise we need to "try" and read out a potential second `-ERR` to let any subscribers know of all possible `-ERR` ops, which to me makes no sense to me. If we should fail fast, then one `-ERR` should mean: _"optionally check state and/or reconnect according to what the client has been configured to do"._

**Sample**
Send `FAIL` and you can get:
- `-ERR Uknown Protocol Operation`
- `-ERR Parser Error`

**Comment by derekcollison** [comment]
We do swiftly close the connection since the server can not recover, but I agree we only need one ERR. Thanks, will see about a fix.
