### ISSUE TITLE
Add log rotation capabilities

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#286]

**Comment by vykulakov** [comment]
I want to rotate my logs too. In documentation I didn't find recomendations to a log rotation. If I can use logrotate, can somebody provide simply config for logrotate, wich will work with gnatsd good?

**Comment by petemiron** [comment]
@vykulakov 

In [0.9.6](https://github.com/nats-io/gnatsd/commit/1c32f2893475f711b2904d492e9f7488e0095497), a feature was added to catch signal SIGUSR1, allowing logging to rotate back to the originally specified log file. You should be able to use something like below:

Start gnatsd:
```
gnatsd -log /home/gnats/log/gnatsd.log -pid /home/gnats/gnats.pid
```

logrotate config:
```
/home/gnats/log/gnatsd.log {
    daily
    size 100M
    rotate 30
    compress
    missingok
    notifempty
    postrotate
        kill -SIGUSR1 `cat /home/gnats/gnatsd.pid`   
    endscript
}
```

**Comment by vykulakov** [comment]
Thanks for your reply. I updated gnatsd and now log rotation works fine!
