### ISSUE TITLE
Publishing on invalid subjects allowed regardless of pedantic mode

### ISSUE THREAD

**Issue by wallyqs** [nats-io/gnatsd#288]
With pedantic mode, we can get notified of errors due to sending control lines containing invalid subjects, though the server is still waiting to consume the full message payload and dispatches the message to any present wildcard subscribers.

```
telnet demo.nats.io 4222
Trying 107.170.221.32...
Connected to demo.nats.io.
Escape character is '^]'.
INFO {"server_id":"Vwp6WDR1NIEuFr0CQ9PtMa","version":"0.8.0","go":"go1.6.2","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576} 
sub > 90
+OK
pub *.*.*.*.* 5        
-ERR 'Invalid Subject'
hello
+OK
MSG *.*.*.*.* 90 5
hello
```

/cc @derekcollison

**Comment by derekcollison** [comment]
Need me to fix for bug fix release?

**Comment by derekcollison** [comment]
I can easily fix for pedantic mode only for now, and we can revisit.
