### ISSUE TITLE
Server can send "authorization timeout" to client after accepting its CONNECT

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#289]
In some race conditions, I believe that it is possible for the server to still send an authorization timeout (and close the connection) to a client after accepting its `CONNECT` protocol and responding to a `PING`. The issue is that then the client receives this error through its readLoop (not during the connect/reconnect handshake) which causes the client library to close the connection, preventing any reconnect.

I believe that the server should check the returned boolean from `c.atmr.Stop()` which, if `false`, would indicate that the timer could not be stopped, likely because the routine has been started/is executing. In this case, the server should return the auth timeout error in place and close the connection to prevent the client from receiving `PONG` and start its readLoop.

**Comment by ColinSullivan1** [comment]
For some additional context, this was likely occurring by a user who was running servers on windows VMs with limited resource issues, and hitting various corner cases around timing with reconnects.  I updated the .NET client to account for this, but moving forward, should defensive code for this be added to all of the clients to handle this?  Today, as mentioned above, they'll close their connection, preventing reconnect attempts.  This also begs the question of which errors should result in a reconnect attempt by a client,versus which should cause the client to disconnect, such as an authorization error.
