### ISSUE TITLE
Is gnatsd/server/pse/pse_${GOOS}.go essential?

### ISSUE THREAD

**Issue by dncohen** [nats-io/gnatsd#290]
New to gnatsd (nats-server), and one of my dev boxes happens to be openbsd.

In order for `go build` to succeed on openbsd, I copied pse_solaris.go to pse_openbsd.go.  With that, I was able to build, run, and follow the telnet "hello world" example.  Totally working.

Or is it?  What I am missing by having just a stub implementation of pse_openbsd.go?  Under what circumstances do pse.ProcUsage results change gnatsd behavior?

BTW, before copying pse_solaris.go, I copied pse_freebsd.go thinking it might just work on openbsd.  Doesn't.  It also has a compilation error, and undefined variable "errno" on line 41.

**Comment by derekcollison** [comment]
The pse_* is to extract memory and cpu usage for the monitoring endpoints. Functionally this is fine to be stubbed, but we recommend implementing for any production use such that the monitoring of cpu and memory can be tracked via the /varz endpoint.
