### ISSUE TITLE
v0.8.0 panic: concurrent map read and map write

### ISSUE THREAD

**Issue by nickcarenza** [nats-io/gnatsd#295]
just upgraded a cluster form 0.6.6 to 0.8.0. started seeing this in the first day.

see log attached 
[gnatsd-panic.txt](https://github.com/nats-io/gnatsd/files/303230/gnatsd-panic.txt)

cluster size is 3, all running 0.8.0

**Comment by ColinSullivan1** [comment]
@nickcarenza, could you try with the master branch?  This looks to be fixed by https://github.com/nats-io/gnatsd/commit/1eb12a1501d837825e87c296c239de842357184f

**Comment by nickcarenza** [comment]
built master and deployed, will keep an eye out. thanks @ColinSullivan1

**Comment by nickcarenza** [comment]
seems to have fixed the problem. thanks.
