### ISSUE TITLE
feature request: identify slow consumers from server

### ISSUE THREAD

**Issue by nickcarenza** [nats-io/gnatsd#296]
On the /varz monitoring endpoint I see a slow_consumer count > 0 but I don't see a way to identify which client client is the slow consumer. The nats client _does_ call the async error callback when it detects it is a slow consumer.

What are your thoughts on adding this to monitoring on the server side?

**Comment by derekcollison** [comment]
To monitor it on the server side we would need to hold state for the connection, but on slow consumer we close the client connection, hence the reason that the reporting is only on a global scale across all connections. 

Most clients should report that they were signaled as a slow consumer when they report the connection was closed from the server.

**Comment by nickcarenza** [comment]
ah, that makes sense. i was wondering then why the server is still reporting it has a slow consumer. i actually can't find anywhere in code where the number is decremented.

this is where it gets incremented:
https://github.com/nats-io/gnatsd/blob/f2c17eb159e1fcc5859b25b632a60c26506f0665/server/client.go#L796

will the server just always report the total number of slow subscribers it has ever had.

**Comment by derekcollison** [comment]
Yes the server just keeps track of those signals. Regular polling of the endpoint will allow you to track deltas, etc.

**Comment by EmilyEmily** [comment]
@derekcollison , sorry to ask two more questions, as you discussed above that the servr just report the total number of slow consumer it has ever had, 
1. What's the timeframe will server record the slow consumers it has ever had? Will the server clean the slow consumer number util the nats server get restarted?  
2. What's the impact for /varz returning slow consumer number >0? 

Thank you.

**Comment by derekcollison** [comment]
The /varz/slow_consumers is only currently reset on a server restart. These are absolute values and /varz has a "now" field as well that can be used to calculate deltas for subsequent polls of a varz and understand the additional number of slow consumers for the same timeframe.

**Comment by EmilyEmily** [comment]
Thank you @derekcollison, your answer is very helpful. I'm investigating if some metrics can reflect the ongoing slow consumer issue which shows the environment is in bad performance and needs to send out alerts. I found /connz has pending_bytes property, if this is higher than 0, could I say that the nats environment has potential performance issue?  How about the comparison between in_msgs and out_msgs?

**Comment by derekcollison** [comment]
If pending_bytes gets large that is a good indicator that you could experience a slow consumer and data loss for sure.
