### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by jjp91** [nats-io/gnatsd#297]
Hello,

When installing by the command .
go get github.com/nats-io/gnatsd

Got this error
src/github.com/nats-io/gnatsd/conf/parse.go:204:20: error: reference to undefined identifier ‘os.LookupEnv’
  if vStr, ok := os.LookupEnv(varReference); ok {

Thank you

**Comment by nuss-justin** [comment]
The os.LookupEnv function was added in Go 1.5, but you are using an older version. Please try to build gnatsd with Go 1.5 or newer (current version is 1.6.2).

The README currently says that Go 1.4+ is required, but even the .travis.yml only checks Go 1.5 and 1.6. I will send a PR that updates the README to say that Go 1.5 is required.

**Comment by jjp91** [comment]
Ok,

Thank you,
