### ISSUE TITLE
Documentation for client behavior in clustering mode?

### ISSUE THREAD

**Issue by rrichardson** [nats-io/gnatsd#303]
http://nats.io/documentation/server/gnatsd-cluster/ notes that there is a clustering mode for performance, high-availability and resiliency.  As I understand it, the latter two features would require that a client replicate their message to more than one server in the cluster simultaneously. 

If clients send out a single message at a time,  does it wait for failure before trying a new node?  
If not, that's OK, it would just be good to note that high-availability is of the cluster itself, and that in-flight messages are pretty much guaranteed to be lost in the event of the loss of one of the servers in the cluster. 

Regardless of the exact behavior, it would be nice if there were some documentation describing the exact delivery semantics for clients of a clustered server.

**Comment by derekcollison** [comment]
You can present a list of NATS servers to most clients. Clients will connect to a single NATS server and only send messages to that server. If the connection fails most clients will buffer messages while connecting to another server in the list. Upon succesful connection it will send the buffered messages to the new server.

Node.js example.

https://github.com/nats-io/node-nats#clustered-usage

**Comment by kozlovic** [comment]
Keep in mind that NATS does not offer at-least-one guarantee (but [NATS Streaming](https://github.com/nats-io/nats-streaming-server) does).
Therefore, the publish API returning successfully does not guarantee that the message is going to be redelivered.
You can ensure end-to-end delivery by using the Request/Reply pattern. The requestor would wait for a reply from the application processing the request message. This gives you the at-least-one delivery semantics without having to use persistence.

An application has a single connection to a server in the full mesh cluster. It needs to produce the message only once, regardless the size of the mesh. The server receiving the producer's message will then send it all its local subscribers that have an interest or to the other servers that have expressed an interest in the subject the message is sent to. From a high level, one message produced will be sent to all interested subscribers, regardless which server in the mesh they connect to.

Recent updates allow now a client application that connects to one server in a cluster to be automatically - and transparently for the user - notified of all server URLs that the client library can reconnect in case of a disconnect event. Here is some more documentation: https://github.com/nats-io/nats#clustered-usage
