### ISSUE TITLE
monitoring subjects as they're created

### ISSUE THREAD

**Issue by rybit** [nats-io/gnatsd#312]
I want to build a monitoring tool that will let me know what data streams there are available in the system. Not only those that already have subscribers. This way I can hook up a subscriber and monitor the channel.

Think of the use case being that I have some bots that are streaming their logs to subjects and I want to be able to list what those are. Then maybe hook into them.

A few ways that were proposed in slack:
1. subscribe to ">"
   - pro: I will get all the messages and can implement my own logic easily
   - con: I will get all the messages (network load)
2. query the `/connz` endpoint with `-m` flag
   - con: could add load to the server depending on how many subjects there are
3. add a metadata subject that got pushed when new topics were discovered
   - pro: avoids the network load
   - con: puts the logic of "discovered" in the server and could impact perf 
   - def needs more thought on what this feature would look like

I am thinking that 1. would be the most direct approach. Maybe there is some kind of 'sparse' flag that could be part of the subscription. 3. seems like a good feature, but it not clear. 

Ideas?

**Comment by derekcollison** [comment]
So you are interested in data flow presence, not interest or subscription presence, correct?

The monitoring endpoints can give you visibility in the interest graph (subscriptions), and there are several ways we could optimize that, however they do not give insight into data flow (published messages and their subjects). For that, the only current way would be to use a wildcard subscription.

Note that it does not have to be a complete wildcard for everything on the system, e.g. ">". I would suggest prefixing the apps that are publishing to logs, e.g. prod.logs.CLASS.APPID. In that case the monitoring app could listen to "prod.logs.>" to see all activity. If you are worries about load, you could make these queue subscribers and run as many as you want, and only coordinate on the presence of new data streams for logs (the trigger event).

Hope that helps..

**Comment by rybit** [comment]
That does help! I do have my logs all split by topic and group, I'll be using smarter wildcards.

I was wondering if there was some kind of way I could subscribe, but shallowly? Getting only the metadata (not the actual message payload) for a given message.

**Comment by derekcollison** [comment]
Currently there is no way to subscribe but limit the payload, but interesting to think about. Would require a protocol update.

**Comment by noahbetzen-wk** [comment]
Almost three years later, is this feasible?

Basically I'm looking for something like RabbitMQ's management web client: https://www.rabbitmq.com/management.html

I want to be able to easily see all existing topics, all subscriptions, and filter them down based on producer, consumer, etc.

**Comment by derekcollison** [comment]
NATS allows monitoring connections with subscription details.

e.g. 

http://demo.nats.io:8222/connz?subs=1

and you can also filter by specific connection.

http://demo.nats.io:8222/connz?subs=1&cid=215201

Although not recommended, you can ask a server for all subscriptions as well.

http://demo.nats.io:8222/subsz?subs=1

**Comment by derekcollison** [comment]
To run server with monitoring `gnatsd -m 8222`. More config examples can be found at https://nats.io/documentation/managing_the_server/monitoring/.

**Comment by derekcollison** [comment]
This is not async. With NATS 2.0 we have the ability to make this a system event.

**Comment by derekcollison** [comment]
Closing for now, happy to re-open if this does not suffice.

**Comment by noahbetzen-wk** [comment]
Oh neat! I didn't know about `?subs=true` on the `/subz` endpoint. That does what I need.

It might be worth updating the documentation on that; it only mentions the flag for the `/connz` endpoint.

Regarding NATS 2.0, is there somewhere to view the milestone progress on it?

**Comment by derekcollison** [comment]
Agree on the docs, we are working on that for sure. /cc @gcolliso 

We plan on releasing NATS 2.0 soon, next few weeks.
