### ISSUE TITLE
Authentication in Nats server

### ISSUE THREAD

**Issue by steventanwc** [nats-io/gnatsd#335]
Is there a way that I can add multiple users credentials to the config file (or any other way) without having to restart the server???

**Comment by kozlovic** [comment]
Not at the moment. I believe that there are plans to have the NATS Server reload the configuration file on a signal without dropping client connections. This would be limited to a certain number of configuration parameters, but authentication may be one of them. We will keep you posted.

**Comment by steventanwc** [comment]
Thank you. Urgently needing this feature as currently one user credentials can only allow a single logon.

So means we have to run the server without authentication and hence not secure.

**Comment by kozlovic** [comment]
Not sure about the reference to "one user credentials can only allow a single logon", but to reiterate, NATS supports multi-user authentication and authorization, however, it does not support reload of the configuration without restart at the moment.

**Comment by steventanwc** [comment]
Meaning only one connection can use 1 user and password combination. No other connection can use this credentials again while the first connection is still connected. 
So if I have 100 multi users credentials when server startup, 101 user cannot be authenticated and cannot be connected. 




Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Ivan Kozlovic <notifications@github.com> Date: 26/08/2016  11:29  (GMT+07:00) To: nats-io/gnatsd <gnatsd@noreply.github.com> Cc: steventanwc <steven@mggsoftware.com>, Author <author@noreply.github.com> Subject: Re: [nats-io/gnatsd] Authentication in Nats server (#335) 
Not sure about the reference to "one user credentials can only allow a single logon", but to reiterate, NATS supports multi-user authentication and authorization, however, it does not support reload of the configuration without restart at the moment.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nats-io/gnatsd","title":"nats-io/gnatsd","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nats-io/gnatsd"}},"updates":{"snippets":[{"icon":"PERSON","message":"@kozlovic in #335: Not sure about the reference to \"one user credentials can only allow a single logon\", but to reiterate, NATS supports multi-user authentication and authorization, however, it does not support reload of the configuration without restart at the moment."}],"action":{"name":"View Issue","url":"https://github.com/nats-io/gnatsd/issues/335#issuecomment-242627715"}}}

**Comment by kozlovic** [comment]
Closing this issue for now. Please follow #338. When this is implemented, that should solve your issue.
