### ISSUE TITLE
tlsverify doesn't do what it says it does

### ISSUE THREAD

**Issue by MikaelSmith** [nats-io/gnatsd#336]
The `tlsverify` option states `Enable TLS, verify client certificates`. However in practice, it only requires that a client has a certificate, not performing any verification of the certificate.

Verification usually includes that a certificate is signed by a certificate chain that can be traced back to registered certificate authorities. gnatsd only [does that for other servers](https://github.com/nats-io/gnatsd/blob/master/server/opts.go#L308-L311), [not for clients](https://github.com/nats-io/gnatsd/blob/master/server/opts.go#L574-L577) (even when `tlsverify` is enabled).

This doesn't appear to be an actual security issue, as authentication can still be done via username/password (which is what's actually tied to authorization).

**Comment by MikaelSmith** [comment]
Also, pretty sure "server can be configured with a CA authority to verify the client certificates" is also incorrect.

**Comment by kozlovic** [comment]
Would you mind elaborating? As a quick experiment, I changed `ClientAuth` to `RequireAndVerifyClientCert` and added `ClientCAs = opts.TLSConfig.RootCAs` during the parsing of TLS section and it seems to be working (without the last part, I would get a failure when `ClientAuth` is now set to `RequireAndVerifyClientCert`. Do we need a dedicated entry for the client CA you think?

**Comment by MikaelSmith** [comment]
You're quicker than I at setting up a test environment :)

If you really want client certificate verification, then you need to use `RequireAndVerifyClientCert` and a way to set a Client CA. So that could be useful. As I said at the end, I'm not sure verification is required if you assume authentication is done via username/passwords. But I don't see the downside in enforcing certificates come from a known CA either.
