### ISSUE TITLE
Hot configuration reload

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#338]
`gnatsd` should support reloading (parts of) its configuration without requiring a restart.

**Comment by ofpiyush** [comment]
A public interface would help.

One could then implement reloads from a config store like [etcd](http://github.com/coreos/etcd)

**Comment by simonrussell** [comment]
It would be actually quite useful if one could publish a new configuration to a configuration subject, which the server would pick up.  (And a subject you can subscribe to for info about config updates.)

**Comment by etopian** [comment]
+1 to be able to use the API to change authentication config. it would make implementing applications that dynamically add and remove users much simpler than trying to modify the config file. if you could publish to a subject to change config it's even better because you could do auth for the web app managing that in the file and then modify the other stuff using any client.

**Comment by maxatome** [comment]
At least, the automatic detection that TLS certificates changed on disk would be great, see https://diogomonica.com/2017/01/11/hitless-tls-certificate-rotation-in-go/

**Comment by ColinSullivan1** [comment]
Following the NATS tenet of simplicity, the mechanism to trigger a reload is simple - a unix signal or windows service control message.  While we understand the feature requests here and how they can help, with what we have today one can build tooling around this to trigger reloads after certificates have been updated or configuration files around authorization and authentication has changed from an external process.

This was addressed through:
#499, #503, #513, #515, #519, #524, #523

**Comment by pangqiyong** [comment]
@ColinSullivan1 What kind of unix signal can trigger the NATS server to reload the config file. Thanks.
