### ISSUE TITLE
Is support for other messaging protocols planned?

### ISSUE THREAD

**Issue by ofpiyush** [nats-io/gnatsd#341]
MQTT in particular looks rather simple to implement with light refactoring and some code.

From a quick read, the feature spec of MQTT looks divided between NATS streaming server and gnatsd.

Apart from minor differences like the separators, wildcard tokens and a couple of missing (exactly once delivery), it looks pretty doable. MQTT's version of gnatsd zero allocation parser looks fairly doable as well.

Is there any reason other than interest and time why contributors of NATS/Appcera have not pursued it?

Off-topic: Thanks for the amazing free beer software! 🍺

**Comment by mcqueary** [comment]
Piyush, thanks for your interest in NATS. We have no plans to make our wire protocol "pluggable", which is how I'm interpreting your question. Support for MQTT or AMQP would be via a connector strategy, e.g. the [NATS Connector Framework](https://github.com/nats-io/nats-connector-framework). We may also pursue Go plugins when golang eventually supports them.
