### ISSUE TITLE
Problem with frozen request/response

### ISSUE THREAD

**Issue by aby2503** [nats-io/gnatsd#350]
Hi, I'm not sure about uniqueness of this issue. I think it can be related to this one https://github.com/nats-io/gnatsd/issues/216. 
In some cases, when I send simple request from CLIENT1 to topic "A", which is observed by CLIENT2, server can handle it after undetermined peace of time( I tested it on local server with 2 subscribers, so load is low). Even more - such freezing requests can accumulate, so respond time grows up. 
 According to NATS server log. 

> [1] 2016/09/07 09:47:24.901776 [DBG] 10.1.0.123:38446 - cid:3353 - Client connection created
> [1] 2016/09/07 09:47:24.908919 [TRC] 10.1.0.123:38446 - cid:3353 - ->> [CONNECT > {"verbose":false,"pedantic":false,"ssl_required":false,"name":"","lang":"java","version":"0.3.0-SNAPSHOT"}]
> [1] 2016/09/07 09:47:24.908962 [TRC] 10.1.0.123:38446 - cid:3353 - ->> [PING]
> [1] 2016/09/07 09:47:24.908973 [TRC] 10.1.0.123:38446 - cid:3353 - <<- [PONG]

then after 2 minutes
> [1] 2016/09/07 09:49:24.902063 [DBG] 10.1.0.123:38446 - cid:3353 - Client Ping Timer
> [1] 2016/09/07 09:49:24.902154 [TRC] 10.1.0.123:38446 - cid:3353 - <<- [PING]
> [1] 2016/09/07 09:49:24.903470 [TRC] 10.1.0.123:38446 - cid:3353 - ->> [SUB response  1]
> [1] 2016/09/07 09:49:24.903507 [TRC] 10.1.0.123:38446 - cid:3353 - ->> [PUB sports response 0]
> [1] 2016/09/07 09:49:24.903516 [TRC] 10.1.0.123:38446 - cid:3353 - ->> MSG_PAYLOAD: []
> [1] 2016/09/07 09:49:24.903528 [TRC] 10.1.0.28:58412 - cid:2943 - <<- [MSG sports 2 response 0]
> [1] 2016/09/07 09:49:24.903555 [TRC] 10.1.0.123:38446 - cid:3353 - ->> [PONG]
> [1] 2016/09/07 09:49:24.911924 [TRC] 10.1.0.28:58832 - cid:3320 - ->> [PUB response 955]
> [1] 2016/09/07 09:49:24.911956 [TRC] 10.1.0.28:58832 - cid:3320 - ->> MSG_PAYLOAD: [bbb]
> [1] 2016/09/07 09:49:24.912007 [TRC] 10.1.0.123:38446 - cid:3353 - <<- [MSG response 1 955]
> [1] 2016/09/07 09:49:24.926080 [TRC] 10.1.0.123:38446 - cid:3353 - ->> [PING]
> [1] 2016/09/07 09:49:24.926107 [TRC] 10.1.0.123:38446 - cid:3353 - <<- [PONG]
> [1] 2016/09/07 09:50:20.065101 [DBG] 10.1.0.28:58832 - cid:3353 - Client connection closed

**Comment by kozlovic** [comment]
The issue you reference had to do with the application not making sure that the subscription was registered in the server before starting sending message. This is something you need to check indeed.

The other issue I would point to is this: [jnats issue 5](https://github.com/nats-io/jnats/issues/5). It may be more relevant to your problem.

Lastly, if none of those seem to solve the problem, please try to run the CLIENT1, CLIENT2 *and* server all on the same machine and use locahost (127.0.0.1) for the url. If it works, you may want to look at network, anti-virus, etc... that would block delay traffic between your clients and server.

**Comment by kozlovic** [comment]
Have you upgraded your client to at least `0.3.1`? Did that solve the issue?
I am going to client this issue now. Feel free to post an update and we will re-open then.
