### ISSUE TITLE
Request/idea: dead letter subject for messages posted nowhere

### ISSUE THREAD

**Issue by simonrussell** [nats-io/gnatsd#352]
Basically borrowed from Akka (possibly elsewhere): a subject that receives messages that aren't delivered to an open subscription.  Could be configurable to only match a particular filter; could be possible to have multiple dead letter endpoints.

The idea is that you can see which messages were sent to a subject which no-one is subscribed to.  Clearly this would only be useful in some scenarios, but for debugging it could be quite useful.

**Comment by mcqueary** [comment]
It would be useful to know what the real use case is, how often you'd use this feature, and what the impact of not having it is.

Discarding messages for which there is no subscription interest serves two basic goals of NATS: simplicity and performance. Implementing Dead Letter semantics in `gnatsd` would add complexity (implementation, configuration and security) without a clear benefit to all users. 

For debugging, a simpler if less tailored answer would be to create a client that subscribes to `>` and looks for messages being published to bad subjects (subjects not conforming to your project's naming rules) and log that.

The desire to know who's subscribed to a given subject is a recurring request, though it's sometimes expressed in different ways. See also related issue #312.

**Comment by simonrussell** [comment]
To be honest, it has been a while and I can't remember my exact requirements here.  I was playing with implementing an agent system on top of NATS, and the dead letter aspect came up in there.

Your hack may be adequate for the debugging use-case, so perhaps the "fix" for this is to just put that suggestion in the documentation.

I suppose more generally it would be useful to know that a message will never be received because no-one is subscribed, or that somewhere there's a break.  These situations could be monitored.

**Comment by ColinSullivan1** [comment]
Great discussion, I'm closing this as there are a few options discussed here, and there is also discussion that would address this issue in #568.
