### ISSUE TITLE
Tagged messages

### ISSUE THREAD

**Issue by jjp91** [nats-io/gnatsd#359]
Hello

This is a request.
The idea is to save bandwidth over internet, save CPU from server (crypted mode) to not send some messages, simplify the server administration by less create subscription and unsubscription.

To be able to ask after a subscription to NOT receive (on a particlar subscription) certain tagged messages, tag would be in the first 2 or 4 bytes of the messages.

This would be userfull for .
- The sender to not receive his own messages
- The other senders that are on the same queue group to not receive them also
- To less create un/subscriptions because, suppose a sender that propose different kind of messages to a group, if the sender says that it will propose a specific kind of messages with a specific tag, the receivers would simply specify that they don't want these tag on the main subscription, and let the other messages come. And all that without having to create new specific subscriptions, and unsubscribe them when the messages had passed.

And when the tag is over by the sender, the sender (or any connexion) could run a specific command like untag( subscription , tag ) that would remove this tag on all the subscriptions that didn't want it, that would prevent all the clients to untag by themselves.

To be able, to not receive our own messages, and to block others, it would be nice to have several unwanted tags at the same time on the same subscription for a connexion.

Thank you for reading.

**Comment by mcqueary** [comment]
Thanks for your interest in NATS. What problem are you actually trying to solve? Is it simply that you want a publisher to be able to subscribe to the subject it's publishing to, without receiving messages it has published?

If you tell us more about your use case, perhaps we can help you arrive at an answer that doesn't involve changing the NATS protocol.

Please refer to [the NATS contributor's guide](https://nats.io/documentation/CONTRIBUTING/) for further information on how we review feature requests and PRs.

**Comment by jjp91** [comment]
Thank you for responding.

Yes, it is very simple, for a sender to not receive his own messages, even if it has subscribed to it.
The idea, is to prevent also other members of the same queue group to not receive messages sent by one of the members.

The best benefit is when using far connections over Internet, not receive messages spare lots of bandwith. And it is a big deal for me and for many people, I guess.

If it isn't possible to do it on a subscription, at least on a entire connection, would be right.

**Comment by mcqueary** [comment]
Thanks for the clarification. Can you tell us more about your use case? It would be helpful to know why your publishers (or queue group members) need to be subscribed to the same subject they're publishing to.

**Comment by jjp91** [comment]
My case is to route messages between sites

**Comment by mcqueary** [comment]
How many sites are there? Have you considered putting a `gnatsd` at each site and letting NATS do the routing?

**Comment by jjp91** [comment]
I don't know how many sites for now, it will depends on where i will have to install it, which i don't know for now.

As far as i know, gnatsd is limited in the length of routes, I remember that a way cannot exceed more than 2 gnatsd, and i cannot limit me this way, but, never mind, i manage the routing, it is ok for me.

Moreover, i need to better control the flow of messages, make sure that some messages never get over a site, things like that.

**Comment by mcqueary** [comment]
This fits into two general requirements we're already discussing:

#446 discusses directed acyclic graph routing in NATS clusters, which would allow creation of cluster graphs that are not complete mesh and therefore could potentially limit message distribution to specific servers, vs. every connected server.

#452 discusses creating a NATS cluster gateway (or edge router) that can allow you to control what is passed between networks.

**Comment by mcqueary** [comment]
I believe that #446, #452 and #453 address the different elements of your use case. Closing this issue in favor of those. If we've missed anything, please let us know.
