### ISSUE TITLE
Round robin

### ISSUE THREAD

**Issue by oaStuff** [nats-io/gnatsd#365]
Will there ever be support for round robin among subscribers in a queue group. the random selection is not PERFECTLY fair.

**Comment by derekcollison** [comment]
I had always though round robin was efficient til I got to Google where they always (may have changed) random since they did not know the efficiency of the endpoints. NATS is the same way, we do not know the nature of the endpoints so RR would not correct, random is the way to go.

**Comment by oaStuff** [comment]
Well .... Ok. I think the argument goes both ways. Since the efficiency of each endpoint is unknown,   RR could still be used without carrying much. You could randomly pick an endpoint that is inefficient and pick in more often while randomizing (that is possible). If RR was used the inefficient endpoint(s) would be guaranteed not to be picked more often than others (every endpoint will have a fair share).

**Comment by derekcollison** [comment]
I certainly understand the argument, and again, this is what Google chooses who has way more data than most. They always choose random.

**Comment by oaStuff** [comment]
OK. Seems like Google is becoming the web standard. The beauty about open source is that you can grab the code and modify it in different ways. So i just added RR to gnatsd and it works perfectly as i expect it to.

**Comment by oaStuff** [comment]
The modified code that supports RR can be found https://github.com/oaStuff/gnatsd/tree/aihe-dev
