### ISSUE TITLE
Need ability to configure ping_interval and ping_max

### ISSUE THREAD

**Issue by vkhorozvs** [nats-io/gnatsd#370]
Could you make it possible to set ping_interval and ping_max in a config file (command line would also be appreciated)?

A default setting of 2 minutes for ping_interval and 2 ping_max are not suitable for some use cases.  For example, for integration testing purposes I'd like to set smaller values to validate how our system behaves under different negative scenarios.

**Comment by kozlovic** [comment]
Looks like we have a PR for that: https://github.com/nats-io/gnatsd/pull/187. However, it looks like the contributor did not provide a test case and PR was never merged. Will ping him again and see if he is still interested in contributing or if we need to take over.

**Comment by kozlovic** [comment]
Addressed with https://github.com/nats-io/gnatsd/pull/372

**Comment by vkhorozvs** [comment]
@kozlovic could you tell me when do you plan to cut a new release version including this patch ?
