### ISSUE TITLE
Gracefully take NATS node out of cluster

### ISSUE THREAD

**Issue by riaan53** [nats-io/gnatsd#371]
Hi,

If I need to perform maintenance on the node running a NATS server that forms part of the big cluster or I need to change the certs how would I take it out of the cluster without loosing messages/upsetting client connections?

Thank you!

**Comment by mcqueary** [comment]
@riaan53 Great question. We're working on a solution for the example scenario you've cited here (see #338), but as of right now, there's no way to do this perfectly with NATS. You can remove the NATS instance, and if they are configured correctly, that instance's clients will seamlessly fail over to other cluster members. The supported NATS clients will buffer outgoing (published) messages during that failover, but as you have noted, there is no guarantee that those clients won't miss inbound (subscribed) messages during this failover. If losing messages is an issue, you might consider using [NATS Streaming](nats-io/nats-streaming-server) along with one of the supported APIs. 

A great resource for peer advice is our community over on the [NATS Google Group](https://groups.google.com/forum/#!forum/natsio).

**Comment by riaan53** [comment]
Hi @mcqueary, Thank you for the feedback. I will have a look at the forum and keep an eye on #338 . 

Thank you for the great product!

Feel free to close the issue.
