### ISSUE TITLE
publication with wildcard not working

### ISSUE THREAD

**Issue by altSoftLLC** [nats-io/gnatsd#375]
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
INFO {"server_id":"e9G1oMHqgyqwynQwtiJqPM","version":"0.9.4","go":"go1.7.3","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576}
sub foo.bar 90
+OK

Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
INFO {"server_id":"e9G1oMHqgyqwynQwtiJqPM","version":"0.9.4","go":"go1.7.3","host":"0.0.0.0","port":4222,"auth_required":false,"ssl_required":false,"tls_required":false,"tls_verify":false,"max_payload":1048576}
pub foo.* 5
-ERR 'Invalid Subject'
hello
+OK

**Comment by derekcollison** [comment]
You can only subscribe to wildcards. Publishing to wildcards is not supported.
