### ISSUE TITLE
Hardware advice for best performance?

### ISSUE THREAD

**Issue by monopollly** [nats-io/gnatsd#380]
Could you please write a hardware preferences for nats...

something like this:
https://www.elastic.co/guide/en/elasticsearch/guide/current/hardware.html

Thanks!

**Comment by mcqueary** [comment]
Thanks for the great suggestion! I'm moving this over to the nats-io/nats-site issues list.

**Comment by mcqueary** [comment]
This issue was moved to nats-io/nats-site#187
