### ISSUE TITLE
Last version (master doesn't compile on Windows anymore)

### ISSUE THREAD

**Issue by ninoles** [nats-io/gnatsd#381]
This is because of the pull request #379, which used a syscall.SIGUSR1, which doesn't exist on Windows.

Could this be conditionally compile for Windows ?

**Comment by derekcollison** [comment]
Will take a look later today, thanks.

**Comment by derekcollison** [comment]
Should be good now in master.

**Comment by ninoles** [comment]
Thanks very much!  That was fast!
