### ISSUE TITLE
Subscriber management interface

### ISSUE THREAD

**Issue by mackeyja92** [nats-io/gnatsd#391]
Is there plans in the future to make a management interface to manage streaming subscribers? For example, no where in my code do I unsub because I mostly intend to restart the client and continue on with my durable queue.

When decommissioning nodes and no longer care about restarting their clients we don’t want NATS tracking those subscribers anymore and taking up resources. We could write a script to go back and unsub but a management interface to just view all the subs for various subjects would be better.

**Comment by derekcollison** [comment]
This would be better posted in https://github.com/nats-io/nats-streaming-server
