### ISSUE TITLE
Bareword in call to gnatsd causes it to ignore other params.

### ISSUE THREAD

**Issue by ckeeney** [nats-io/gnatsd#392]
If you call `gnatsd bareword -cluster nats://:6222`, nats will still start, but it will ignore the `-cluster` arg (or any other args).  This leads to confusing behavior and I think it would be better if nats just exited with an error in this case.

For example, the second revision of this gist works as expected, the first revision of this gist still starts, but does not cluster:

https://gist.github.com/ckeeney/ba40d1d6362a9d7633a0eb1f8eab7b24/revisions

**Comment by mcqueary** [comment]
To be more specific, it may mask problems with command line construction, making such problems harder to debug, and lets users think they're running `gnatsd` with their desired options, even if they accidentally omitted the dash in front of one or more flags. IMO, the "fail fast" best practice applies to command lines as much as anywhere else.
