### ISSUE TITLE
Dockerize Unstable for New NATS Verzion

### ISSUE THREAD

**Issue by drasko** [nats-io/gnatsd#396]
We at [Mainflux](https://github.com/mainflux/mainflux) use NATS within [Docker composition](https://github.com/mainflux/mainflux/blob/master/docker-compose.yml) and services wait for it to be available using [Dockerize](https://github.com/jwilder/dockerize): https://github.com/mainflux/mainflux-core/blob/master/Dockerfile#L37-L43

Dockerize detects that NATS is up while listening to TCP port 4222.

It used to work pretty well, but recently is became very unreliable - there is no response from NATS or it comes with big delay.

We bumped down `apcera/gnats` version from `latest` to 0.7.2 - now it works correctly. So obviously some regression has been introduced during the last week or two (before we had no problems).

Can it be that commit https://github.com/nats-io/gnatsd/commit/ca268290a651f3ad565ed81d985dfef332bcadf4 from @kozlovic introduced the regression?

**Comment by kozlovic** [comment]
@drasko Do you specify max_connections in the config? If not, then the change should have no effect since the change in server code checks for `s.opts.MaxConn > 0`.

Instead, there has been some changes to detect incorrect command line parameters. It could be that you are actually passing incorrect parameters which would have before not complain but ignore the other parameters in command line? See [PR 393](https://github.com/nats-io/gnatsd/pull/393)

**Comment by kozlovic** [comment]
Also check [Issue 392](https://github.com/nats-io/gnatsd/issues/392)

**Comment by lenovouser** [comment]
You're using an outdated image. The last push to **[apcera/gnatsd](https://hub.docker.com/r/apcera/gnatsd/)** was over a year ago. They have switched to the official repository at **[_/nats](https://hub.docker.com/r/_/nats/)** which also has newer tags available (the lastest release is `v0.9.4`).

**Comment by drasko** [comment]
Wow, quick responses ;). Thanks.

@kozlovic I do not know what Dockerize uses, but I think it just tries to open the TCP socket, and that's all.

@lenovouser I am trying _/nats image now...

**Comment by drasko** [comment]
And with nats:latest it works like a charm.

Thanks, closing the issue.

**Comment by kozlovic** [comment]
@drasko I had noticed the reference to `apcera/gnatsd` but assumed that you used this one as a test. As @lenovouser stated, `apcera/gnatsd` is no longer maintained.

**Comment by kozlovic** [comment]
@drasko Glad to know that latest works as expected. By the way, the docker image is `0.9.4` from last august and therefore none of the commits referenced in this issue are relevant since they are in master but not in `0.9.4`.
