### ISSUE TITLE
NATS middleware

### ISSUE THREAD

**Issue by arekkas** [nats-io/gnatsd#410]
Most of you probably know what a middleware is all about. It could make a lot of use cases really easy, if we were able to define middlewares in NATS. We could, for example:

* Inspect the payload to decide if the requestee is allowed to publish (or subscribe) to the message
* Transform the payload to, for example, make debugging easier
* Log all messages for replay

Of course, the middleware would have to use a network API (maybe even using the NATS protocol):

<img width="794" alt="bildschirmfoto 2016-12-24 um 10 48 52" src="https://cloud.githubusercontent.com/assets/3372410/21466313/9b0639d4-c9c6-11e6-9fbf-c0d67c1a1ad7.png">

When both services run on the same host, network latency won't be a real issue, and it could be very fast with little overhead.

I think this would be a very interesting field that not a lot of message broker have touched, yet middlewares are a pattern that is quite common in reactive system. By using a network API (likely even the NATS protocol), concerns (like authN/authZ) would be completely separated and allow for a lot of userland code. Also, tracing and debugging errors will become a lot easier, because we can scrap message data in real-time and inject things like a `Original-Request-Id`, if missing.

**Comment by soulne4ny** [comment]
Isn't it just the same as making 2 subjects – foo-raw and foo-filtered? Then middleware is just a usual client that moves entries from one to another.

**Comment by tylertreat-wf** [comment]
gnatsd could also use Go plugins, which are coming in go1.8 for linux and 1.9 for darwin/windows (https://tip.golang.org/pkg/plugin/).

**Comment by arekkas** [comment]
> Isn't it just the same as making 2 subjects – foo-raw and foo-filtered? Then middleware is just a usual client that moves entries from one to another.

True

**Comment by mcqueary** [comment]
Hi @arekkas. The term "middleware" is perhaps a little too broad for this conversation. NATS itself is a form of middleware (message-oriented middleware). 

What you're describing sounds to me a lot like rule-based routing and mediation, which could be accomplished using connectors to a system that specializes in that sort of thing. For example, [Apache Camel](http://camel.apache.org/), which has a [NATS connector](http://camel.apache.org/nats.html) already.

**Comment by mcqueary** [comment]
Closing this for now (see previous comment). Please reopen if you feel strongly that this should be accomplished by NATS and provide further justification and use cases that would differentiate this from e.g. Apache Camel and the like.

**Comment by amdshrif** [comment]
@mcqueary  I would defiantly support this feature to be added to NATS but on the client side not on the server side. Adding a middleware that for example  Encodes and Decodes data sent/received is a good example, logging and data validation on the connection level is also a good example . Specially since ```nats.EncodedConn```` has been deprecated
