### ISSUE TITLE
use monotonic time source

### ISSUE THREAD

**Issue by glycerine** [nats-io/gnatsd#414]
Given this:
https://blog.cloudflare.com/how-and-why-the-leap-second-affected-cloudflare-dns/

and the current state of the time.Now() call not being monotonic:
https://github.com/golang/go/blob/29cb72154d3bb3530d8092cc89d35b3ed4f7e9c5/src/runtime/sys_linux_amd64.s#L147

you may wish to prefer this:
https://github.com/glycerine/monotime

and replace calls to `time.Now()` with `time.Unix(0, int64(monotime.Now()))`

**Comment by derekcollison** [comment]
I read the other thread between you and @kozlovic. Will take a look in case we make an assumption, but do not think a change to the library you mention is required at this time. I do appreciate the issue however.
