### ISSUE TITLE
On Documentation

### ISSUE THREAD

**Issue by dc0d** [nats-io/gnatsd#430]
There are some inconsistencies in NATS documentation. For example the configuration file for gnatsd, described on [github](https://github.com/nats-io/gnatsd#configuration-file) is different than the configuration file described on NATS' docs on [website](http://nats.io/documentation/server/gnatsd-config/).

Also I remembered [this](https://groups.google.com/forum/#!topic/natsio/YqwswoAurmw) topic on concurrent safety of `*nats.Conn`. Lacking documentation, at this level (API comments), could hurt such a brilliant product.

**Comment by mcqueary** [comment]
@dc0d Kaveh, thank you for pointing this out. We're preparing for a revision to the docs and will make sure this is included in the changes.

**Comment by gcolliso** [comment]
updated w/ PR673
