### ISSUE TITLE
Authorization Timeout and TLS

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/gnatsd#432]
When TLS and authorization is enabled, the authorization timeout can fire during the TLS handshake, causing the server to write the authorization timeout error string into the client socket, injecting what becomes bad data into the TLS handshake.  This creates misleading errors on the client such as `tls: oversized record received with length 21024`.

I've only seen this happen when the host machine is under very heavy load with many clients simultaneously connecting, causing the server to become CPU bound.

There are a few ways to tackle this, but I propose waiting to schedule the authorization timer until after TLS is fully established to avoid this scenario.  Any thoughts?

**Comment by ivanr** [comment]
FYI, this issue (or a variation of it) appears to still exist. We were seeing connection problems a lot of the time, using gnats 1.10. Examining the network capture, I see the negotiation starting to take place, and then the server sends a plaintext "-ERR 'Secure Connection - TLS Required', which naturally derails the client.

Increasing the TLS timeout resolved the issue. Before the change, every other connection would fail (staging environment, one client, no load). After the change, no connections appear to fail. If it matters, we use client certificates.

**Comment by derekcollison** [comment]
Being able to set these is due to DOS attack mitigation.

**Comment by ivanr** [comment]
Interesting. Has this been done preemptively, or have there been attacks against TLS handshakes in the past?

**Comment by derekcollison** [comment]
I am just trying to be pre-emptive. We could look at more sane defaults or if you set one less than the other etc. Do you think this would have helped? The server should have logged that a timeout was being exceeded, but the client will be more vague, again by design.

**Comment by derekcollison** [comment]
When you received these timeouts was it a single new connection or when many clients were trying to connect to a server? For instance when an old server is shut down? This is something I am looking into.  In terms of timeout defaults etc, will take a more detailed look. Could you create an issue? 

for DOS and DDOS, its resource exhaustion as you say, but mostly memory and kernel resources IMO.

**Comment by oliverhausler** [comment]
2s are definitely too short. We have our servers distributed across Europe and with 2s TLS timeout machines often (>50%) failed to connect. When set to 5s, close to 100% of connection attempts succeeded.

**Comment by derekcollison** [comment]
You can set the timeout in the config of course to whatever you need it to be.
