### ISSUE TITLE
Initialize subscriptions during server startup in clustered mode

### ISSUE THREAD

**Issue by gazoon** [nats-io/gnatsd#439]
Consider following situation: two nats servers in clustered node, we also have a subscriber S connected to server A, periodically clients send PUBs to server B, server B knows about subscriber S and successfully redirects all messages to server A. But after some time server B falls and boots again now we have situation when server B can accept PUBs from new clients, but it doesn't know about subscriber S, therefore it doesn't send any message until server A doesn't send info about subscribers.  May be in clustered mode server should pull info about subscribers before it starts accept new clients?

**Comment by kozlovic** [comment]
I don't think this is feasible, or at least the use would be very limited: it may work but only for servers that have explicit routes. Even then, if server A and B have explicit route to each other, there is a race that can cause one of the server to drop the route (after it was established) to be re-established later. If a server starts accepting clients (and PUBs) after establishing a route, some PUBs could still be lost in the event I just described. And again, that would not work at all for servers just accepting routes, but not initiating them (that is, say that B does not have a route defined to connect to A, when it starts, it will accept clients right away and so PUBs could be "lost").

I would even say, how is your application going to make the difference between publishing to B while A is down (or route connection lost, and messages are necessarily not getting to S), and the situation where messages were published just as B was restarted.

I think that when you use NATS, you need to accept the fact that a PUBs can be lost. If you want added certainty of not losing the message, you should send it with a request/reply pattern.

**Comment by gazoon** [comment]
Thanks for explanation. Now I understand that it's a bad idea.
