### ISSUE TITLE
Test for concurrent connections

### ISSUE THREAD

**Issue by yuridiniz** [nats-io/gnatsd#441]
Is there a limit test for concurrent connections in a controlled environment? 
Has anyone ever reached the mark of 1 million concurrent connections on a single server?

Thanks

**Comment by ColinSullivan1** [comment]
@yuridiniz ,  We currently have no formal test as the behavior you will see is largely dependent on your environment (for example, memory, available file descriptors, network bandwidth).

Can you further describe your use case?

**Comment by yuridiniz** [comment]
@ColinSullivan1, Thanks for the answer, I'm using NATS to connect IoT devices to the servers, I took a look at the MQTT protocol but I found NATS and it's amazing.

In my research on MQTT, I found the emqtt.io, in its documentation, it was described that the broker could handle up to 1.2 millions of concurrent connections on a robust CentOS server

I believed that it was only possible to handle 65335 concurrent connections because of the limitation of ports on the server

Recently I found an article in a blog where they tried to reach +10M using NATS but the article is very superficial

Link to documentation: http://emqtt.io/docs/v2/getstarted.html#one-million-connections
Link to article: https://blog.greta.io/a-signaling-system-for-10m-concurrent-connections-10d327fd6837#.xp76gow1b

**Comment by ColinSullivan1** [comment]
@yuridiniz , Thank you!  We really feel NATS is amazing as well.  :)

Greta.io uses NATS as the transport behind their signaling system, but I understand they do not use 10M actual NATS connections.

I appreciate you passing the emqtt.io information on - reaching one millions connections there is interesting.  Yes, by default there is a 65k limit, but that is on outbound connections.

One million connections on a single server is impressive, and a good exercise, although I'm wondering how useful that would be in practice.  In any pub/sub messaging product, once subscriptions are made, a server with a massive number of clients will likely become memory bound very quickly (unless most clients will only publish to small number of subscribers).  For decent throughput, availability, and if security is required (encryption can burn CPU), you'll want your connections spread out across a number of clustered nodes, as you'd quickly run into a number of bottlenecks.  NATS makes clustering very easy to setup, and will automatically propagate cluster topology changes to clients through an auto-discovery feature.

Thank you for bringing this up - we do need to look into scalability testing with NATS to see how far it can go with respect to maximum number of connections, and in other areas too.

What is the maximum number of concurrent connections you need for your case?

Thanks,
Colin

**Comment by yuridiniz** [comment]
@ColinSullivan1, In order for my project to become viable and costs become low for customers, I would need to support at least 100k of simultaneous connections to a server in the following scenario.

- Each device subscribes in 5 pub.
- Devices, when not requested, send 1 message every 1 hour.
- Eventually, the devices need to send 1 message every 300ms

Assuming a fictional scenario in which all devices would be requested at the same time, we would have a message overload of 100k every 300ms (+/- 330k per second)

I believe that these numbers influence the number of concurrent connections as well as the server hardware configuration, but today I am still without parameter to know if these settings is very utopic or if in fact they are feasible to work with these numbers.

**Comment by bjflanne** [comment]
@yuridiniz -- Thanks for providing some high level requirements here, and the color given so far. I work on the NATS Ecosystem team, and I'd be interested to learn more about what you're trying to accomplish here - perhaps a quick call next week? We can also include you in the NATS Slack Channel and discuss there if you happen to use slack.. if you'd like an invite and to discuss further shoot me an email: brian@nats.io

**Comment by derekcollison** [comment]
You will need to tweak the network parameters but its possible. The 65k limit is per client addr, so if all clients appear to the server as from the same address you can only do 65k. Otherwise it is 65k per client address space.

**Comment by streetlist** [comment]
I'm interested also on the concurrent connection. Pls provide benchmark on server spec, network spec, ram spec too if any can be found online etc. appreciate this.

**Comment by derekcollison** [comment]
ok I will look into it. How many connections are you looking to achieve? Main connections will be more heavy, but we will be introducing lightweight, but still performant Websockets soon.

**Comment by streetlist** [comment]
i read somewhere 600k on golang websocket... let's push for 1 mil? specs, no idea but let's hope it's production capable kind of operations.

**Comment by derekcollison** [comment]
Right now its about 30k / connection give or take. So for 1M connections would be over 30GB of memory. We would need to slim up connections. And again, the websocket version will be coming this year.

**Comment by derekcollison** [comment]
Closing for now, but high connection count per server is on our list.

**Comment by joy4eg** [comment]
@derekcollison I know, that ticket is already closed ... 
Anyway, does NATS have some tests/benchmarks about how many clients/connection can be handled with the one server ?

I'm curious because I have almost the same situation as @yuridiniz, with 10M-50M-100M connections to the cluster, and now looking for the corresponding solution.

**Comment by derekcollison** [comment]
TBH you are only limited by memory, but you will have to tweak the kernel to get those types of numbers. There are lots of online articles about how to tune the linux kernel for lots of connections.
