### ISSUE TITLE
Add --cluster_advertise <host/ip> option which would be used for auto-discovery

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#447]
#### Use Case:

Related to issue #438.

Right now, with auto-discovery, a server will propagate to the routed servers and possibly clients, the host/IP specified in `listen` and/or `cluster` parameter.

It can be a problem if this address is not accessible or should not be from outside of the box.

The listen address should only be used for the bind (could be 0.0.0.0 on a container, or a special interface in a bare-metal cluster with private networking). The advertised host/ip should be the only ip known by both other members of the mesh and clients, keeping the backend hidden.

Such configuration permit to use VIP addresses in front of potential dying containers (works for both swarm and kubernetes for example without the use of headless services).

#### Proposed Change:

Adding a new parameter, say `--cluster_advertise <host/ip>`, would allow the server to use this address instead of trying to resolve the `listen` address (if `0.0.0.0` is specified), or the result of `RemoteAddr()` for routes.
Other servers and clients would be made aware of the advertised address instead of the address used by the server to create the tcp listener.
 
#### Who Benefits From The Change(s)?

People running NATS Server in containers or in the cloud when some addresses are not visible from the outside. Also, would help for situations when a node is restarted and assigned a new IP address, which with auto-discovery would be added to the list as a new entry. With use of `cluster_advertise`, the address being the same, it would not change the list of server.
 
#### Alternative Approaches

If host/ip is used for `listen` and `cluster` parameters, that address is currently advertised to clients, but not other servers. Still, as mentioned above, there are cases where the binding address of the NATS Server is not the address one would want to make public.

**Comment by stamf** [comment]
Hey guys, we are also interested in this functionality in order to circumvent the problem of connecting via reverse proxy (amazon elb). Is there any update on this idea or a branch we might be able to play with?

@luma

**Comment by kozlovic** [comment]
@stamf This is not implemented yet. Asking @ColinSullivan1 and/or @petemiron to see if this is in the roadmap.

**Comment by ColinSullivan1** [comment]
IMO this sounds like a good enhancement to me.  We're evaluating outstanding issues and will be publishing a roadmap soon.

**Comment by twang2218** [comment]
I have the same issue, as described in #542, when using NATS cluster inside docker, the `connect_urls` returns the docker internal IP addresses, which cannot be accessed to the Client.

Another case is when the servers have multiple network interface, and one for communication between NATS servers in the cluster, and another for the communication with clients, in this case, the `connect_urls` are most likely return the IP addresses are not accessible to the client either.

Having a `-advertise` argument will help the issue, we can specify which address we expect the client will connect to:

```
$ gnatsd -p 4223 \
    -cluster  nats://0.0.0.0:5222 \
    -routes nats://nats_a:5222 \
    -advertise 1.2.3.4:4223
```

**Comment by chrissharkey** [comment]
I would be interested in paying someone to do this work or making a donation to the project if we could get it done. Would someone be able to contact me about this if interested please: chris@autopilothq.com.

**Comment by petemiron** [comment]
Thank you for the offer @chrissharkey, we'd happily accept a PR submission for this feature. I'll email you separately to see if you'd like to be invited to our slack channel and for any support questions.

**Comment by kozlovic** [comment]
For those interested in this issue, could you please have a look at the comment I made on the PR regarding "route" advertise (not client, which I think is fine). Would love some feedback on your use case. Link to comment is [here](https://github.com/nats-io/gnatsd/pull/608#issuecomment-362641418)
