### ISSUE TITLE
Add option to load server TLS key passphrase from a file (or URL)

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#450]
## Feature Request
 
_(from Slack discussion with user @primalmotion)_

#### Use Case:

As a user/administrator, I need to start `gnatsd` with a TLS certificate and supply the private key's passphrase via configuration (not interactively), because I am using an automated service to configure and start `gnatsd`. 

#### Proposed Change:

Add a configuration option (command-line and config-file), e.g. `--tls_password_file` to specify a file/URL containing a passphrase (or list of pass phrases) to be used when loading the server certificate key. See for example [NGINX's ssl_password_file parameter](http://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_password_file)
 
#### Who Benefits From The Change(s)?

Any user/organization that wishes to use TLS-secured `gnatsd` instance(s).
 
#### Alternative Approaches

The user could create a wrapper script that starts up `gnatsd`, reads the passphrase from some URL, and supplies the passphrase via redirection of `stdin`.  However, this would be less user-friendly, potentially error-prone, (even) less secure, and may create debugging confusion should things go awry.

**Comment by joelguevara** [comment]
We are currently using NATS in a production environment that requires private keys to be encrypted with a passphrase. 

Could we kindly reopen this issue?

**Comment by derekcollison** [comment]
Since this one is pretty stale let's open a new one and make sure we capture this issue correctly.
