### ISSUE TITLE
NATS cluster gateway

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#452]
#### Use Case:

As a user/admin, I need to have multiple sites communicate using NATS. My objectives are:

1. Maximize bandwidth efficiency (reduce unneeded message propagation between sites)
2. Actively filter content ingress/egress by subject 

#### Proposed Change:
 
Create a NATS gateway (or edge router) that can be configured to route message between NATS clusters, filterable by subject and direction (ingress/egress). 

_(further requirements definition needed)_

#### Who Benefits From The Change(s)?
 
NATS users who want to distribute NATS messages efficiently between multiple sites with multiple NATS clusters, while filtering or preventing unneeded or undesired message propagation between sites.

#### Alternative Approaches

There is no simple alternative available through configuration. However:

 * Users could create their own custom client to do this.
 * DAG routing (#446) could offer cluster configuration strategies that are more efficient for this use case, but ~~not subject filtering. It would also be more complex to implement, perhaps significantly.~~ risk and complexity would likely be higher. This would be a change to the core routing logic in `gnatsd`, with additional testing burden and likely higher complexity of configuration for the user.

**Comment by ColinSullivan1** [comment]
@mcqueary , What do you mean by subject filtering?  I'd imagine DAG would inherently filter subjects.

**Comment by mcqueary** [comment]
@ColinSullivan1 Thanks. Good point. We could implement DAG _or_ a Gateway _without_ filtering, but neither of these would be very useful without also having subject-based filtering/routing. I'll edit my rationale.

**Comment by derekcollison** [comment]
Closing for now, we have several issues all talking about the same thing.

**Comment by vazir** [comment]
+1 - Intercluster (within-gateway) filtering is very required as we would like one cluster to share a very limited set of topics with other clusters or do not want it's users to subscribe to alien topics at all

**Comment by derekcollison** [comment]
I would suggest using leafnodes which I think will do what you need.
