### ISSUE TITLE
Prevent delivery of messages to sending connection's subscriptions

### ISSUE THREAD

**Issue by mcqueary** [nats-io/gnatsd#453]
If a client connection's `CONNECT` protocol contains (e.g.) `no_local : true`, the server should not deliver messages that originated from that connection to subscriptions on that connection.

- [ ] Add option to clients

**Comment by derekcollison** [comment]
Wondering if we still think this is interesting? Almost feels like it should be per subscription not just per client connection.

**Comment by derekcollison** [comment]
We could do this connection wide without a major protocol change. Per subscription would require low level protocol changes from client to server.
