### ISSUE TITLE
Ping messages are not processed on TLS connections between routes

### ISSUE THREAD

**Issue by stefanschneider** [nats-io/gnatsd#458]
The PING/PONG functionality is not active on a running 3 nodes NATS cluster with TLS enabled between routes. I looked at the commit history, but I am not sure if this is a desired behavior or not.

This is the code line that disables the PING/PONG for TLS connections:
https://github.com/nats-io/gnatsd/blob/fdf1a24d78c1e5f2aa0f71a3426fd7a2fdc500bc/server/client.go#L1197

This is a dirty patch that enables PING/PONG for TLS connections: https://github.com/stefanschneider/gnatsd/commit/3bc0824f8c06b9bb9a9fa83282125d7aab8f09de

### How did I see this problem and how could PING/PONG prevented a network issue?
I have a 3 node NATS cluster (server A, B, and C) with TLS enabled.

Checking the server connections with netstat:
Server A has a route connection to server B established 
Server A has a route connection to server C established
Server B has a route connection to server C established
Server C does NOT see the the connections from server A and B. 
I am not sure how this happen, it may be because of some network issues or some TCP proxy issues. 

Checking the server routes with `/routez`:
Server A has 2 routes
Server B has 2 routes
Server C has 0 routes

Because the PING/PONG was disabled in this scenario, Server A and B did not close the TCP/TLS connection and the route was kept in a healthy state until the underling socket would be closed. Even though server C attempted to created a route to server A and B, the new connection was considered a duplicate and closed.

This NATS cluster partition was present for at least 20 minutes in my debug environment. There was definitely something flaky in my network, but if the PING/PONG functionality was enabled the NATS cluster mesh would have automatically recovered very fast even in this scenario. 

Fell free to close this issue if PING/PONG was disabled on purpose for TLS route connections.

Thank you
Stefan

**Comment by kozlovic** [comment]
Thanks for the report! I think we could simply check `if c.nc == nil`. When the timer is set, the connection is already established. Actually, the purpose of the test would then be just that the connection has not be closed while the callback was about to fire. @derekcollison what do you think?

**Comment by stefanschneider** [comment]
Wow that was fast :) Thank you for looking into this.

**Comment by kozlovic** [comment]
@stefanschneider Than *you* for the report! We now have a test that will make sure we don't break that again in the future ;-)
