### ISSUE TITLE
gnatsd-server delivers duplicate messages

### ISSUE THREAD

**Issue by robertfreund** [nats-io/gnatsd#463]
We are experiencing issues where gnatsd will keep resending the same message for extremely long periods of time. Our gnatsd server is NATS server version 0.9.4. 

From time to time we see that gnatsd sends the same data over and over. It seems more frequent when traffic is burstable and slow consumers are detected. 

This is not a queued subscriber. When this scenario is detected our timestamps we use to measure latency just don't make sense. We take a timestamp and place in message when we receive data and use our subscriber to check with its timestamp what the latency generally is. There are periods where we see this number go into well over 48 hours, sometimes into the 100's of hours. 

At the time we detect this we see that the actually message is the same message being repeated over and over and over. It appears the entire system does not just halt and send repeats as other messages have realistic timestamps. 

Also it should be noted that our monitoring is constantly running. When we see our reports of over 48hours latency we did not slowly grow to 48hours but all of a sudden we have packets being delivered with extremely old timestamps. Meaning our latency will be 400 ms or so and then all of a sudden spike where some messages are being delivered over and over again from the past.

Has anyone experienced this type of issue? I would expect in a fire-forget system that when a new consumer does subscribe that a message from over 48h ago would not be delivered over and over. 
Also at the same time I see the duplicated message, i see other timestamps that are reasonable and under 300 ms.

In our environment we use both java and go clients.
github.com/nats-io/go-nats:6b6bf392d34d01f57cc563ae123f00c13778bd57

In this scenario to rule out client though; when I seen this behavior I created a new subscription and was delivered the same 48h old message. Again there is no queue subscriber in play.

Thanks.

**Comment by kozlovic** [comment]
That is clearly not possible since gnatsd does not keep any message in memory. When a message comes in, it is sent directly to matching subscribers. The longest it can stay in the socket buffer is 2 seconds, which is the write deadline set by the server, after which the consumer's client connection is closed if data was not drained from the socket.
You may have an application that sends those messages, but not the server. As for the weird timestamps, make sure that for some reason this machine does not have its clock changed.

**Comment by robertfreund** [comment]
thank you for your quick response. i am continuing to investigate as we are battling latency issues.
