### ISSUE TITLE
Add  Msgs/Sec Bytes/Sec to varz

### ISSUE THREAD

**Issue by vsundupey** [nats-io/gnatsd#469]
Can you add In/Out - Msgs/Sec, Bytes/Sec statistic to http://localhost:8222/varz reports various general statistics?

**Comment by derekcollison** [comment]
We would need to understand the last time you polled the endpoint to determine the rate across that time interval. This would make too many assumptions, so instead we provide you with a timestamp of when you pulled the information from varz, you can use this to do your own calculations on any scale you desire to calculate the rates. These mechanisms are built into most collectors as well such as Prometheus.
