### ISSUE TITLE
amd64 binary not statically linked

### ISSUE THREAD

**Issue by leifg** [nats-io/gnatsd#470]
I just found out, that the binary for 64bit has not been compiled with statically linked libraries:

```
wget https://github.com/nats-io/gnatsd/releases/download/v0.9.6/gnatsd-v0.9.6-linux-amd64.zip
unzip gnatsd-v0.9.6-linux-amd64.zip
file gnatsd-v0.9.6-linux-amd64/gnatsd
=> gnatsd-v0.9.6-linux-amd64/gnatsd: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, stripped
```

this caused trouble running it on alpine linux. I looked up the [binary for the docker container](https://github.com/nats-io/nats-docker/blob/24da6ab2af9e849f6a96e32ed2efcb7c0799ab13/gnatsd) which seems to be statically linked.

Is that by accident? I think the 64bit binary should be statically linked (as the 32bit one is)

**Comment by kozlovic** [comment]
Strange since they are all compiled with the same flags `scripts/cross_compile.sh`. Will have a look. Thanks!

**Comment by kozlovic** [comment]
I think we need to add `env CGO_ENABLED=0` before `gox`, let me experiment.
