### ISSUE TITLE
SetClientAuthMethod (authMethod Auth)

### ISSUE THREAD

**Issue by altSoftLLC** [nats-io/gnatsd#476]
The new version does not have func (s * Server) SetClientAuthMethod (authMethod Auth)

Bring her back. Because you need the ability to override the authorization method for clients and routers.

**Comment by derekcollison** [comment]
What type of override where you doing? Were you building you own forked version to support this?

Thanks.

**Comment by altSoftLLC** [comment]
We use this to implement client authorization through our own OAuth2 service.

**Comment by derekcollison** [comment]
So you do build your own gnatsd server correct? It should be simple to retrofit your code to the new simple code path.

**Comment by ColinSullivan1** [comment]
Closing this for now.  There is discussion of a future plug-in interface that will allow overrides of the default auth mechanism (#434).
