### ISSUE TITLE
double-quoted string values in the config aren't backslash-escaped

### ISSUE THREAD

**Issue by ericpromislow** [nats-io/gnatsd#477]
From reading the lex code it looks like the only time string lexing does backslash-escaping is for raw strings (no quotes). And the lexer seems to only recognize backslashes, but it doesn't actually convert sequences like `\"` to `"` (and the lexer tests repeat that). The parser doesn't do any escaping, and it really can't, because it doesn't know how the `itemString` it picks up was delimited.

I found this trying to set up a bosh-lite cf with a nats password of `spaces and \ backslashes`

**Comment by derekcollison** [comment]
Feel free to submit a PR with a test case and fix. Happy to review.

**Comment by ericpromislow** [comment]
On it.
