### ISSUE TITLE
wire protocol?

### ISSUE THREAD

**Issue by mcuadros** [nats-io/gnatsd#48]
Where i can find the wire protocols specs?
Its needed for any who want build a driver for unsupported languages (python, php, etc)

**Comment by reikje** [comment]
Any news on this :)

**Comment by derekcollison** [comment]
@reikje Are you looking for a protocol doc, that correct?

**Comment by derekcollison** [comment]
We will start creating much better docs, thanks..

**Comment by mcqueary** [comment]
The NATS documentation is now live on our new open source website: [nats.io](http://nats.io).
The protocol doc is here:
http://nats.io/documentation/internals/nats-protocol/
