### ISSUE TITLE
Request/idea: Force client connection closing

### ISSUE THREAD

**Issue by valichek** [nats-io/gnatsd#483]
## Feature Requests
Trigger somehow killing client connection by ip/login/token/connectionId/subscription with custom error

#### Use Case:
One may need to force one client or group of clients to authentication/authorization because of security threat or just to reconnect for debugging remote device

**Comment by derekcollison** [comment]
When configuration reload is complete, it will disconnect users who are no longer valid. Meaning either they were removed all together or the password for the user was changed.
