### ISSUE TITLE
Add Support for Multiple CAs for client TLS verification

### ISSUE THREAD

**Issue by petemiron** [nats-io/gnatsd#484]
#### Use Case:
As an administrator, I need to be able to rotate my TLS Certificate Authority keys to support key rotation for my clients, so that I can release new CA keys without updating all clients simultaneously.
 
#### Proposed Change:
Allow `tls.ca_file` config parameter to take a comma-separated list of files.

**Comment by kozlovic** [comment]
Closing this since multiple CAs can be concatenated into a single file.
