### ISSUE TITLE
Change configuration parameter write_deadline type (from integer to time.Duration)

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#487]
- [X] Feature Request or Change Proposal
 
## Feature Requests

Change the `write_deadline` configuration type from being an integer to be a string that can be parsed as a duration (say "25ms") to allow lower than 1 second deadline from configuration.
 
#### Use Case:

There may be some cases of 1 to many subscribers where one would want to reduce the write deadline so that one slow consumer in the list does not slow down too much the rest of group.

#### Proposed Change:

Support for `write_deadline` in the configuration was introduced in PR #421 as a number of seconds. The corresponding option, however, is a `time.Duration`. Since this is in master but not part of an official release, I wonder if this would be ok to modify the configuration parsing to look for a time.Duration instead of an integer.
People that are using the parameter (say: `write_deadline: 1`) would get an error saying that this parameter is expected to be a duration, and would need to change to `write_deadline: "1s"` for instance.
 
#### Who Benefits From The Change(s)?

People that need a smaller than 1 second write deadline from the configuration file.
 
#### Alternative Approaches

Introduce a new parameter parsed as time.Duration that would override the current `write_deadline`.

cc @petemiron This is based on the discussion that we had. I can submit a PR if desired.

**Comment by petemiron** [comment]
Yes. Please create a PR. this is perfect. Thanks!
