### ISSUE TITLE
Configuration parsing sometimes attempts parsing a value of the wrong type

### ISSUE THREAD

**Issue by aricart** [nats-io/gnatsd#494]
- [X] Defect (LOW)
 - [ ] Feature Request or Change Proposal
 
## Defects 

If you have a simple cluster config like this:
```
# This file was generated 2017-05-17 17:03:40.501690691 -0500 CDT
listen: xxx.local:10571
http: xxx.local:15571


tls {
	cert_file: "/Users/xxx/test_certs/xxx.cert"
	key_file: "/Users/xxx/test_certs/xxx.key"
	verify: false
	timeout: 2.0
}



cluster {
	listen: xxx.local:13071

	authorization {
	 	user: cluster_1
	 	password: 5ADISY_bfhkprstuvv
	 	timeout: 2.0
	}

	routes = [
		
		nats-route://cluster_1:5ADISY_bfhkprstuvv@xxx.local:12628
		
		nats-route://cluster_1:5ADISY_bfhkprstuvv@xxx.local:12885
		
	]
}
max_connections: 10
max_payload: 65536

include ./auth.conf
include ./messagerate.conf
```

The `cluster` config for the `password` will fail because the lexer attempts to parse as an integer. Gnatsd will report: `Parse error on line 20: 'Expected a map value terminator "," or a map terminator "}", but got 'A' instead.'`. 

The workaround is to enclose the `password` value in quotes. Since the password field likely should be interpreted as a string this shouldn't be necessary. Alternatively for safety we should be indicating that string values should be quoted (specially if the configuration is machine generated).

#### Versions of `gnatsd` and affected client libraries used:
 found on 0.9.6

#### OS/Container environment:
OS X

#### Steps or code to reproduce the issue:
Use config above
 
#### Expected result:
Parse value as string or provide a better error message indicating that the value was expected as a number.

**Comment by derekcollison** [comment]
You can always put a string in single or double quotes to force string parsing.

**Comment by aricart** [comment]
Yes this is the workaround.

**Comment by mmanna-sapfgl** [comment]
In Windows, I had the same error. I escaped all double quotes with \. And then it worked. The only problem for me was to transfer the file via SSH and ECHOing it into a conf file. WHich I had to map using --volume option.

**Comment by wallyqs** [comment]
@mmanna-sapfgl this is fixed in master already and part of the next release
