### ISSUE TITLE
Get rid of global logger

### ISSUE THREAD

**Issue by tylertreat** [nats-io/gnatsd#500]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
#### Use Case:
gnatsd currently uses a [global logger](https://github.com/nats-io/gnatsd/blob/d6069447d22cc48d7b70c144f4634784748852bb/server/log.go#L16-L19). This can cause some problems (especially around the [config-reload work](https://github.com/nats-io/gnatsd/pull/499)), but global variables are also just an anti-pattern in general. The current behavior is particularly surprising because the global logger is configured through [calls to the `Server`](https://github.com/nats-io/gnatsd/blob/d6069447d22cc48d7b70c144f4634784748852bb/server/log.go#L54).
 
#### Proposed Change:
Make the logger a field on the `Server` instance.
 
#### Who Benefits From The Change(s)?
gnatsd maintainers. This will also make config reload more sane.
 
#### Alternative Approaches
None considered.

**Comment by tylertreat** [comment]
A follow-up to this might be to extract the logger into a separate NATS logging package. According to @ColinSullivan1:

> IMO the logger should be its own NATS logger package, and the server should have an instance of it.  The server, streaming server, prometheus exporter all use the same logging code, copied.  Well, the streaming server uses a hybrid version last I checked.

**Comment by kozlovic** [comment]
Closed with #501.
