### ISSUE TITLE
Improve external usage of server stats

### ISSUE THREAD

**Issue by ripienaar** [nats-io/gnatsd#516]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
#### Use Case:

When embedding the nats broker it would be handy for the thing its embedded in to be able to get at the stats in its data format.

Right now the http handlers in server/monitor.go also does the work of constructing the data they are serving

#### Proposed Change:

Extract each data creator out into say a method like server.NewConnz()  that does the work of building up the data structure and filling in all the current values etc and then return that.

Use these new methods in the http handlers and as proposed make sure they are exported for others to use

Filing the issue to see if you're happy with the approach and if so I can look at making a PR for the change

#### Who Benefits From The Change(s)?

Those who embed the NATS server in other go projects
 
#### Alternative Approaches

not sure?

**Comment by derekcollison** [comment]
This functionality exists now.
