### ISSUE TITLE
Extract gnatsd logger into separate logging package

### ISSUE THREAD

**Issue by tylertreat** [nats-io/gnatsd#518]
With #500, the gnatsd logger was made non-global. This logger is also used by NATS Streaming and Prometheus Exporter. We should consider extracting the logger into a separate NATS logging package that both can consume. According to @ColinSullivan1:

> IMO the logger should be its own NATS logger package, and the server should have an instance of it. The server, streaming server, prometheus exporter all use the same logging code, copied. Well, the streaming server uses a hybrid version last I checked.

**Comment by derekcollison** [comment]
Checking in with @ColinSullivan1 and @kozlovic, can we close this one?

**Comment by ColinSullivan1** [comment]
@derekcollison, What do you think of pulling out logging into its own repo?

**Comment by derekcollison** [comment]
I think @kozlovic worked with the current setup within STAN, but want him to chime in here.

**Comment by kozlovic** [comment]
At this point it would take a lot of effort to take logger out and make it a separate repo. I would vote for closing this for now.
