### ISSUE TITLE
Provide additional information about slow consumers 

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/gnatsd#520]
- [X] Feature Request or Change Proposal

Users have mentioned that a pain point in NATS is often tracking down slow consumers.  Additional information should be provided which can help the user identify the connection and subscription to help quickly identify the slow consumer.  One approach is to log the connection name, cid, and sid for slow consumers.  Another could be to hold this in memory and allow this information to be returned via monitoring.

#### Use Case:
A slow consumer error occurs, but there are many applications and a large cluster of NATS servers making it difficult to identify which consumer is slow.
 
#### Proposed Change:
Additional information such as the connection ID, connection name, and subscription ID should be provided through logging or monitoring which will help identify the slow consumer. 

#### Who Benefits From The Change(s)?
Users with applications receiving slow consumer errors, especially if they have large deployments.

#### Alternative Approaches
The applications can log and report the slow consumer in the asynchronous error callback on the connection.  Update the examples to demonstrate this.  Note, this may not be foolproof since the connection can be closed a slow consumer error would be handled.

**Comment by EmilyEmily** [comment]
Could I ask at an estimation, when will this feature be implemented?

**Comment by tylertreat** [comment]
I don't think we've determined how we want to solve this problem yet. Personally, I think logging this information is less useful than exposing it somehow through monitoring. Perhaps adding a "slow consumer" count to each connection in `/connz`? Would be useful to get community feedback though.

**Comment by EmilyEmily** [comment]
@tylertreat that's a good idea to add a "slow consumer" count in /connz. Waiting for the final solution.

**Comment by ColinSullivan1** [comment]
Adding a note, a few other users have requested this.

**Comment by derekcollison** [comment]
Closed via #692
