### ISSUE TITLE
Strategy for signaling config reload on Windows

### ISSUE THREAD

**Issue by tylertreat** [nats-io/gnatsd#521]
On Unix platforms, the plan is to expose config reload using `SIGHUP`. However, Windows doesn't have an equivalent and is limited to the [interrupt signal](https://github.com/nats-io/gnatsd/blob/f8e5f5fe64b0263e0b9b66d0c73077fee7d989e0/server/signal_windows.go#L17).

We need to determine a strategy for signaling config reloads on Windows. One option might be to expose an HTTP endpoint for triggering reload, but this would be unprecedented for NATS since the existing HTTP APIs are all read-only. AFAICT nginx uses a CTRL+C handler using [SetConsoleCtrlHandler](https://msdn.microsoft.com/en-us/library/windows/desktop/ms686016(v=vs.85).aspx). We currently [trap this and exit](https://github.com/nats-io/gnatsd/blob/f8e5f5fe64b0263e0b9b66d0c73077fee7d989e0/server/signal_windows.go#L23).

@nats-io/core

**Comment by derekcollison** [comment]
I think following NGINX's pattern for windows would make the most sense.

**Comment by tylertreat** [comment]
I think this would mean trapping CTRL+C and doing config reload instead of exiting the process.

**Comment by petemiron** [comment]
It looks like nginx uses the packages for running a windows proc as a
service:
https://godoc.org/golang.org/x/sys/windows/svc

**Comment by petemiron** [comment]
Sorry. Wasn't done.

It looks like nginx uses the packages for running a windows proc as a
service:
https://godoc.org/golang.org/x/sys/windows/svc

re: http://hg.nginx.org/nginx/file/tip/src/os/win32/ngx_service.c

Then, in the command line (for both unix + windows), it has command line
options for restart, reload, shutdown:
nginx -s [signal -- stop | quit | reload | reopen]

**Comment by ColinSullivan1** [comment]
This does make sense to me.  While users currently tend to use NSSM for their needs, implementing a windows service for the NATS server would add to NATS.

Thinking of the HTTP endpoint (over a different interface/port than monitoring), there are some advantages:
* Authorization
* Versioning of a REST API for compatibility moving forward
* Extensible - won't run out of signals/service control codes
* Same mechanism used across platforms
* Easy to build tooling around it

I do favor a REST API on an HTTP endpoint over the signal/service control code, but as @tylertreat mentioned, it is unprecedented and does break with our current read-only policy.

**Comment by tylertreat** [comment]
Consensus from the weekly NATS eng. call was to implement NATS as a Windows service for the MVP and implement a REST API at a later time if we decide that's needed.
