### ISSUE TITLE
Invalid configuration is accepted by the server

### ISSUE THREAD

**Issue by aricart** [nats-io/gnatsd#530]
- [X ] Defect
 - [X] Feature Request or Change Proposal
 
## Defects 

The gnatsd configuration loads an invalid configuration without complaining. For example this snippet on a test to see if a JSON version of the configuration would work:

```
# NOTE 'DEFAULT_PERMISSIONS' needs to be in the authorization section
"DEFAULT_PERMISSIONS":{
	"publish":">"
	"subscribe":["foo.>","bar.>"]
}

"authorization": {
	"users": [
		{"user": "test", "password": "a"}
	]
	# default of 5 seconds for an authorization timeout.
	"timeout": 5.0
}

```

The server takes it:
```
[albertoricart@barsoom:/tmp/natsservice/1/current]$ bin/natsservice1 -c natsservice1.conf
[54613] 2017/07/07 10:18:49.931405 [INF] Starting nats-server version 0.9.6
[54613] 2017/07/07 10:18:49.931480 [INF] Starting http monitor on barsoom.local:15084
[54613] 2017/07/07 10:18:49.931960 [INF] Listening for client connections on barsoom.local:10084
[54613] 2017/07/07 10:18:49.932360 [INF] Server is ready
[54613] 2017/07/07 10:18:49.932782 [INF] Listening for route connections on barsoom.local:12584
```

Now on a client:

```
[albertoricart@barsoom:~]$ nats-sub -s nats://test:a@barsoom.local:10084 "barx.>"
Listening on [barx.>]

```

This is unexpected, the server likely should have failed to start since it had a configuration that it couldn't make sense of.

**Comment by tylertreat** [comment]
I would add that this is really a security vulnerability as it's easy to start a server thinking you have permissions enabled when in fact you don't if your config is invalid.

**Comment by kozlovic** [comment]
To play devil's advocate, the general idea is try not to reject things that the server don't know (or care) about. This allows for easy downgrade: a new parameter can make sense to a server version y but not to version x (x < y).
Also, specifically for this case: this is a variable, so it even makes less sense for the server to reject this. (although the presence of the quotes is questionable). This variable could be used in the scope or in a file including this file.

**Comment by aricart** [comment]
What this means is we need a version number on the config, then we can downgrade. However if the server doesn't know what to do with it, the human will think it is ok only to find out that it isn't.
Previous experience says, it should crash with a message or offer a flag to prevent strict validation.

**Comment by kozlovic** [comment]
Also, in the case of NATS Streaming, I possibly feed the same config file to both Streaming and NATS, which would then now fail since NATS would report errors for anything that is Streaming related.

**Comment by kozlovic** [comment]
Actually, your definition of DEFAULT_PERMISSIONS at the top makes it a variable. So you could use it inside the authorization map:
```
"users": [
		{"user": "test", "password": "a", permissions: $DEFAULT_PERMISSIONS}
	]
```
Since this is a variable (which happens to have the same name than an option in the authorization section), makes it difficult for the server to reject. At the very least, this means that the server would have to check that a variable does not use any of the known option name.

**Comment by aricart** [comment]
Yes that works, but the name is special and is lost if not in the authorization section.

**Comment by kozlovic** [comment]
In summary, it would mean that server should:
- reject variables if they have same name than an option (otherwise, the configuration you have above would be considered valid)
- every `switch` in configuration file parsing would need to have a `default` that would return an error about unknown parameter

This would cause NATS Streaming to force users to use 2 separate files for NATS and Streaming (which they can now, but we recently made it easy for them to specify a single config file that was given to each module).

**Comment by kozlovic** [comment]
Problem with above is that server would then fail a valid configuration. For instance:
```
my_listen_port: 4222
listen: $my_listen_port
```
when it comes to `ProcessConfigFile`, what we have is a map with 2 keys ("my_listen_port" and "listen").  The value of "listen" has already been expanded to being 4222. But the server would reject with the rules defined in previous post saying that "my_listen_port" is an unknown option.
More thinking to do here...

**Comment by derekcollison** [comment]
Agree to more thinking on this before any decisions are made.

**Comment by RedShift1** [comment]
Philosophically it comes down to this, does NATS:

- Fail fast and hard
- Or keeps plowing on despite errors or illogicalities

I always follow the fail fast and hard path, as my experience has taught me the "keep plowing on" method can introduce subtle, hard to reproduce/find bugs. In this case maybe even security issues. As a more practical example, PHP for example is notorious for its "keep plowing on" methodology, allowing things like writing to an invalid file handle and only spewing out warnings, which are usually suppressed in production. This has been a source of bugs, security issues and general frustration. So I would vouch to fail fast and hard whenever any irregularity comes up.

**Comment by derekcollison** [comment]
I think the example given is valid. DEFAULT_PERMISSIONS is a variable in that example but is correct. We could introduce some warnings if need be but not so sure we need to fail that example at all.
