### ISSUE TITLE
Log File path using gnatsd.exe as a windows service needs to be in Linux format   

### ISSUE THREAD

**Issue by WDevereux** [nats-io/gnatsd#553]
- [X ] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

When you install gnatsd.exe as a windows service (as per the ReadMe doc) and you specify a Config file on the service command line then ..
The Service can start and read the Config file but the path for the log_file in the config file has to be set to use the Linux "/" character instead of the normal "\" windows one. If you don't do this then the Service fails to start.

It should be like this on windows
log_file: "D:\Projects\Research\NATS\64Bit\Logs\gnats.log"

but it only works like this
log_file: "D:/Projects/Research/NATS/64Bit/Logs/gnats.log"

If you start gnatsd.exe from the command line (not as a service) the above does not happen.

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ N] Included `gnatsd -DV` output
 - [ N] Included a [Minimal, Complete, and Verifiable example] (http://stackoverflow.com/help/mcve)
 
#### Versions of `gnatsd` and affected client libraries used: 
Version 1.02

#### OS/Container environment: 
Windows 10 - Creators Update

#### Steps or code to reproduce the issue:

Install gnatsd.exe as a windows service using the following command:
sc.exe create gnatsd_Server binPath= "D:\Projects\Research\NATS\64Bit\gnatsd32.exe -c D:\Projects\Research\NATS\64Bit\Nats.cfg"

In the above Nats.cfg file, set the value for the log file to 

# logging options
debug:   false
trace:   true
logtime: true
log_file: "D:\Projects\Research\NATS\64Bit\Logs\gnats.log" 
(using normal windows backslash path separator) 

Start the service
 
#### Expected result:

The Service should start and it should use the specified log file.
 
#### Actual result:
 
The service fails to start at all.

If you change the log file to 

# logging options
debug:   false
trace:   true
logtime: true
log_file: "D:/Projects/Research/NATS/64Bit/Logs/gnats.log" 
(now using Linux forward slash path separators)
 
it works as expected.

## Feature Requests
None
 
#### Use Case:
None
 
#### Proposed Change:

Change the code to allow for windows style paths on a Windows OS

#### Who Benefits From The Change(s)?

Everyone who uses gnatsd.exe as a Windows Service

**Comment by WDevereux** [comment]
Hi, The path for the .pid file has the same problem.

**Comment by ColinSullivan1** [comment]
@WDevereux, thanks for raising this issue, I'll take a look.

**Comment by ColinSullivan1** [comment]
@WDevereux , currently, the option value for `pid_file` and `log_file` is being parsed as a string that supports escaping.  You're probably getting an invalid escape character error, something like:  
```Invalid escape character 'P'. Only the following escape characters are allowed: \xXX, \t, \n, \r, \", \\.'```

You can verify this by running the NATS server outside of a windows service: `D:\Projects\Research\NATS\64Bit\gnatsd32.exe -c D:\Projects\Research\NATS\64Bit\Nats.cfg` 

I bet this was frustrating - I'll look at a fix.  In the meantime, you can continue to use the unix path separator, or escape the backslash by using `\\` as a path separator in those option values if you prefer something closer to windows style separators.

**Comment by WDevereux** [comment]
Hi Colin,

Thanks for that – I will continue to use the Unix path separators for now 😊

It did have me baffled for quite some time.

I have almost completed writing a Delphi (Object Pascal) Client for NATS which I will be open sourcing (when I find out how)

Regards

Wayne Devereux

**Comment by ColinSullivan1** [comment]
@WDevereux , Great!  I'll be looking forward to seeing your client - certainly keep us posted!

At this time, we'll continue to support escaping in string values within the configuration file as it may be valuable to some users, but I'll certainly update relevant documentation about this behavior.  Thanks again for raising this issue.

Regards,
Colin

**Comment by jocontacter** [comment]
> I have almost completed writing a Delphi (Object Pascal) Client for NATS which I will be open sourcing (when I find out how) 

I would be very happy if you share! My legacy code part written on object pascal

**Comment by jonahzheng** [comment]
hi @WDevereux, good job, Delphi Client for NATS Server is available?
where to download

**Comment by biot2** [comment]
> I have almost completed writing a Delphi (Object Pascal) Client for NATS which I will be open sourcing (when I find out how).

Hi @WDevereux,

I am also interested in your NATs client for Object Pascal. If you wish to share it please let me know.

Regards,
Biot
