### ISSUE TITLE
Proposal: Dead-Letter Queue Subscriptions

### ISSUE THREAD

**Issue by tylertreat** [nats-io/gnatsd#568]
# Background

With gnatsd, there is no way of knowing if a message was delivered (or attempted to be delivered) to a subscriber. However, the server knows this information when it receives a published message. If there are no subscribers, the message is [dropped on the floor](https://github.com/nats-io/gnatsd/blob/4246f83c7414ad13a33a1ca94c5db2413941f038/server/client.go#L1107-L1110). Typically, error-handling/timeout/retry logic should be handled by the client, but in the case where there is no interest on the subject, it's moot.

# Use Case

Let me provide a concrete example where this is a problem. In NATS Streaming clustering, when a client publishes a message to a channel, it gets delivered to every node in the cluster but only processed by the leader of the channel. The followers simply drop the message and wait for the leader to replicate it. In this case, we create unnecessary network traffic and waste server resources. What should happen instead is only the leader of the channel subscribes to the channel subject. However, this creates the problem of bootstrapping a channel: before a channel is created, no one is subscribed. One solution would be to add a separate operation for creating channels, but this complicates the API. The second solution is a dead-letter queue subscription in gnatsd.

# Proposed Solution

@petemiron and I discussed what is basically the "inverse" of an interest subscription. A client normally subscribes to subjects like `foo`, `foo.*.baz`, `foo.>`, etc., which is "deliver any messages with these subjects to me." The inverse of a subscription is "deliver any messages with these subjects to me *if no one is interested in them*, i.e. a dead-letter queue.

The subscription semantics of a dead-letter queue are similar to those of a regular subscription (they support wildcards, queue groups, etc.), but the difference being they are only triggered when a message matching the DLQ subject is not delivered to any subscribers (again, the NATS server knows this already).

This solves the NATS Streaming clustering use case described above in that the cluster subscribes to a DLQ on the channel publish wildcard subject. Initially, when there is no channel leader, a message is delivered to all nodes via the DLQ, the nodes create the channel, and once a leader is established, the leader subscribes to the channel subject. Thus, future messages are delivered only to the leader of the channel. If multiple messages are published on a channel before a leader is elected, they will get delivered to everyone in the cluster, but nodes should block until the channel is created and a leader is established.

# Alternative Solutions

For the most part, many of the problems DLQs solve could probably be solved by using more sophisticated pub/sub patterns that NATS already supports. However, there are trade-offs to this. As hinted at in the NATS Streaming use case, using these patterns would almost certainly introduce a lot of complexity into the NATS Streaming API.

Further, a common question NATS users ask is "how do I know if anyone is listening?" Again, this could be solved with timeouts and retries, but this is unreliable and slow despite the NATS server *knowing* this information. Similarly, a solution commonly cited is to use the monitoring API to determine if there are listeners, but at the same time, use of the monitoring API for application logic is (and should be) discouraged. An elegant solution would be for a client to setup a DLQ subscription on a subject, publish on the same subject, and if it receives the message on the DLQ, it can be certain no one has received the message (and in a much more timely manner than with a timeout).

# Implementation Note

The implementation of DLQs should be nearly identical to regular subscriptions, including the full-mesh semantics. We can avoid a protocol change by using the reserved `_SYS` subscription prefix. In the client, this would be exposed as a new API call, `SubscribeDLQ`, with a similar signature to `Subscribe`.

**Comment by sfrooster** [comment]
I'm exceedingly light on caffeine/sleep so forgive me in advance, but you say "One solution would be to add a separate operation for creating channels, but this complicates the API."  By that, do you mean within the protocol?  It looks like what you're proposing an extra-protocol (outside of the protocol) solution and if that's the distinction, this seems fine to me.

Thoughts on preventing subscribers from subscribing to the DLQ (which of course you will) as in, how would you do that?

**Comment by tylertreat** [comment]
@sfrooster The solution I was referring to for creating channels explicitly was referring to the problem in NATS Streaming. If we made channel creation explicit there, it would require clients to call `CreateChannel` before calling `Publish`. That makes the API much more clunky. If we had DLQs, the client API would remain unchanged—clients would just have to call `Publish` and, if the channel doesn't exist yet, it's created lazily.

As for access control on DLQs, my thought is we would apply the same authorization used for subscriptions to them.

**Comment by ColinSullivan1** [comment]
Adding a note - for us, this addresses an issue in NATS streaming.  If you have a concrete use case where this feature would be useful, we'd certainly love to hear about it!

**Comment by kozlovic** [comment]
I think it would be nice to be able, for a requestor that wishes, be able to subscribe on the DLQ for the subject it publishes to, and get "immediate" response that there is no interest.

The problem with timeout is setting the right value: too short and you don't give time to the subscriber to receive the request and send back the reply. Too long and you waste valuable time.

So suppose that I want to publish a request on `foo` but want to be notified asap if there is no interest at all. I could subscribe to `_SYS.dlq.foo` and then publish the request. When the server processes the incoming message on `foo` and there is no subscription, it would publish a message (the sent message?) to the subject `_SYS.dlq.foo`. The requestor could then select either the actual response from the reply subject or the response received on the dlq, in which case it can fail fast.

(optimization wise: not sure if it is worth for the server to check if there is interest in dlq subscription before sending the message out)

**Comment by tylertreat** [comment]
Adding to what @kozlovic said...

An additional use case in NATS Streaming regarding publish NACKs. With DLQs, we could avoid the redundant traffic by having only the leader listen to a channel as described above. Currently, with NATS Streaming clustering, if a message is published to a channel that does not have a leader, it's dropped and the client times out. Unfortunately, this means the client must always wait the ceiling of the timeout before it can react, despite the NATS Streaming cluster "knowing" there is no leader immediately when the message is received.

With a DLQ, we could send a NACK to the client and short-circuit the timeout entirely in one of two ways: 1) have the NATS Streaming cluster subscribe to the DLQ and publish a NACK to the client or 2) have the client subscribe directly to the DLQ and not involve the cluster at all. In the second case, we also need to scope the DLQ down to the client so that a client only receives its own NACKs and not other clients'. This can be done by having clients publish on a subject like `_STAN.my-cluster.some-channel.clientid` and the leader for `some-channel` subscribes to `_STAN.my-cluster.some-channel.>`. Then clients subscribe to their DLQ: `_SYS.dlq._STAN.my-cluster.some-channel.clientid`. This way, the server receives all channel messages and when there is no channel leader, clients only receive NACKs for their own messages.

**Comment by ColinSullivan1** [comment]
Adding that this functionality was also requested elsewhere:  https://github.com/nats-io/gnatsd/issues/352

**Comment by tylertreat** [comment]
I went ahead and implemented this to see what it would look like. Feedback is welcome: https://github.com/nats-io/gnatsd/pull/571

**Comment by cdevienne** [comment]
The use case for client needing to know if the message was handled has one shortcoming I can think of with permissions.

In our case, clients can publish on some subjects, but not subscribe, because sensitive data may be sent and we want only a selected set of accounts to handle these subscriptions.
Which means that the client would not be able to do a DLQ subscription to get a NACK.

The whole concept would still be a good addition imo, only it is not a solution for this particular case.

**Comment by tylertreat** [comment]
@cdevienne I think NACK could be implemented in such a way that the client could only subscribe to their own NACK inbox. This was my thought for NACKs in NATS Streaming since that would be an issue there as well. We wouldn't want clients receiving NACKs for clients other than themselves.

**Comment by derekcollison** [comment]
Closing this for now, may add in ability to understand interest in a given published subject.
