### ISSUE TITLE
Consider writing a kubernetes operator for nats as a service.

### ISSUE THREAD

**Issue by SEJeff** [nats-io/gnatsd#582]
#### Use Case:

* Providing my users with NaaS (nats as a service) just like the [etcd-operator](https://github.com/coreos/etcd-operator) allows them to use etcd as a service. They're currently using kafka, but most of the apps are in go and nats is a better fit. Making it more straightforward to spin up testing clusters on all of our available hardware seems like a massive win. Also we have existing software using nats which will be moving shortly to kubernetes.
 
#### Proposed Change:

Create a nats [operator](https://coreos.com/blog/introducing-operators.html) for creating, managing, and running nats / nats streaming as a service on a kubernetes cluster. Ideally, you'd run this with RBAC and give it only access to the specific namespaces the operator is running in.
 
#### Who Benefits From The Change(s)?

Kubernetes users who want to use nats. Since GKE has a free tier, it would make it really nice to document how to spin up a fully working out of the box nats server in the google cloud as well.
 
#### Alternative Approaches

Running nats [manually on kubernetes](https://github.com/pires/kubernetes-nats-cluster) works, but isn't near as magical or fun. Also, the configuration and monitoring can be done automatically when creating multiple discrete nats clusters for different users.

Use the [kafka-operator](https://github.com/krallistic/kafka-operator) and be sad that you have to use an app written in java.

**Comment by bjflanne** [comment]
Hi @SEJeff -- thanks for all the detail provided here, I like the way you explained the challenge and the benefit... Let me know if this repo @pires has been working on is useful for what you are trying to solve. I believe this is for NATS not NATS Streaming, but may be worth a look: https://github.com/pires/nats-operator  

Regardless, I'd be interested to chat sometime and learn more about what you are using NATS for / considering it for, feel free to drop me a note at brian@nats.io to sync up (or ping me in NATS Slack if you are in there...)

B

**Comment by pires** [comment]
hey @SEJeff! I do have a working NATS operator as @bjflanne so kindly referred to above. It works great but is missing a live-migration upgrade story. Perhaps you want to help (https://github.com/pires/nats-operator/issues/16)?

Now, AFAIK NATS-Streaming doesn't support clustering. Has this changed in the last couple months? Otherwise, depending on your storage backend, a Statefulset is enough.

**Comment by tylertreat** [comment]
NATS Streaming clustering is still in progress...

**Comment by pires** [comment]
...so a Statefulset is enough if your storage backend is disk and not some network-exposed database.

**Comment by ColinSullivan1** [comment]
> Has this changed in the last couple months? 

@pires Glad you asked!  As @tylertreat said, streaming clustering is in progress.  We've updated our [roadmap](https://github.com/nats-io/roadmap), and do plan to keep it current moving forward.

**Comment by AceHack** [comment]
I would also like this, and please wrap it up in a helm chart.  Statetfulsets and or operator pattern would be great.  I would love to see an officially supported helm chart (with upgrade support).

**Comment by pires** [comment]
@AceHack [there's already a statefulset](https://github.com/pires/kubernetes-nats-cluster). [The operator](https://github.com/pires/nats-operator) works fine too.

None are official but I've had some conversations with @wallyqs and @petemiron and they are willing to help.

There's no Helm support but feel free to contribute it.

Upgrades work fine **but** NATS has no story around upgrades that would _guarantee_ no loss of messages. If a certain server goes away and has messages that no client (connected to it or any other server in the cluster) consumed, they're simply gone. I would like to see a story here but I'm open to be convinced to document this behavior and just move to support NATS Streaming (now that it is almost done with clustering).

**Comment by ColinSullivan1** [comment]
FYI, a helm chart is under development, [here](https://github.com/ColinSullivan1/nats-k8s).

**Comment by pires** [comment]
Oh ok, @ColinSullivan1 a word of notice, multiple NATS instances coming up doesn't meant full-mesh so you should move from Deployment to Statefulset. I did so in my repo (and adopted the official container image plus a few other things) so feel free to take lessons from it if you want.

**Comment by AceHack** [comment]
@pires just curious if it uses Parallel (burst) or normal stateful sets?

https://github.com/kubernetes/kubernetes/issues/41255
https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#parallel-pod-management

**Comment by ColinSullivan1** [comment]
@pires , thanks!  Much appreciated, I'll take a look.  I did confirm full mesh using the chart, but I'll certainly look into moving to Statefulset.

**Comment by pires** [comment]
@AceHack with NATS you can't burst. You need to make sure to connect to a host (headless service makes it random, yet not proxied) that knows about the full-mesh network, otherwise you'll have instances that have no routes between each other.

**Comment by pires** [comment]
@ColinSullivan1 hmmm, I may be wrong but I'd recommend you triple checking that all nodes have routes to every other node in the cluster.

**Comment by manigandham** [comment]
If we can have an option to "try connecting every X seconds" for routes built into NATS itself then we can remove all the complexity in the deployment and just use a regular Kubernetes deployment/replicaset.

**Comment by kozlovic** [comment]
@manigandham NATS does try to connect to an explicit route every 2 seconds. Even for implicit routes (the one that are initiated due to auto-discovery), there is an option to have the server attempt to connect more than once with the config: `connect_retries`

**Comment by derekcollison** [comment]
Checking in on this, can this be closed? /cc @pires @wallyqs

**Comment by wallyqs** [comment]
We'll be supporting the operator from @pires at https://github.com/nats-io/nats-operator so sounds good on closing (thanks again Pires!)
