### ISSUE TITLE
Very high CPU usage during initial TLS setup

### ISSUE THREAD

**Issue by ripienaar** [nats-io/gnatsd#589]
#### Versions of `gnatsd` and affected client libraries used:

server 1.0.2 latest go client

#### OS/Container environment:

centos 7 on ec2 t2.medium

#### Steps or code to reproduce the issue:

create 16 000 TLS connections as quick as you can
 
#### Expected result:

I know TLS is quite heavy and initial setup is costly but perhaps somewhere something can be tuned, this seems excessively slow

Once the initial TLS handshakes are done and connections are up CPU usage is back down to a good 2% no problem
 
#### Actual result:

NATS, for 90 seconds or so, using all available CPU on all cores

**Comment by RedShift1** [comment]
Maybe not enough entropy available?

**Comment by kozlovic** [comment]
Which cipher is being used? You could run server with `-D` and run only one of the client to see what cipher is being negotiated between the two. You may want to make sure that you use a faster cipher (CHACHA ones). Are you using on top of that authorization with bcrypt or token?

If we can improve we will, but still, it is expected that if you do create that many connections at once, there will be burden in the CPU. I would recommend adding some random delay in the creation of all those connections.

**Comment by ColinSullivan1** [comment]
More information about configuring ciphers and curve preferences can be found through `gnatsd -help_tls`.  Based on your environment, some could be better to use than others.

**Comment by ripienaar** [comment]
`TLS version 1.2, cipher suite TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256`

**Comment by ripienaar** [comment]
these are what -help_tls suggest to me:

```
TLS configuration is specified in the tls section of a configuration file:

e.g.

    tls {
        cert_file: "./certs/server-cert.pem"
        key_file:  "./certs/server-key.pem"
        ca_file:   "./certs/ca.pem"
        verify:    true

        cipher_suites: [
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        ]
    }

Available cipher suites include:

    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    TLS_RSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_RSA_WITH_RC4_128_SHA
    TLS_RSA_WITH_RC4_128_SHA
```

**Comment by ColinSullivan1** [comment]
Which version of gnatsd are you using?

Also, here's a older, but good, comparison of cipher suites.
https://community.qualys.com/thread/16005

**Comment by kozlovic** [comment]
He is using `1.0.2` but unfortunately, this was built with `Go 1.7.6`, which does not have the CHACHA ones. Any chance you can build from master with Go 1.8+ to try?

**Comment by kozlovic** [comment]
We are planning to have a `1.0.4` soon that will be built against Go 1.8.3, which should help for people not able to build from source.

**Comment by ripienaar** [comment]
Will do a build and try yes

**Comment by kozlovic** [comment]
Have you configured to use specific ciphers or were you just listing the `help_tls`? I am not sure from your post if you did setup based on the tls help. If so, after building with Go 1.8, you may want to change the config.

**Comment by ripienaar** [comment]
I did not change it, was just showing there's no CHACHA anything with what you shipped, all the cipher settings is as per defaults you shipped.

**Comment by kozlovic** [comment]
They are, but only avail when built with Go 1.8. If you do build with 1.8+, and do `gnatsd --help_tls` you should then see them.

**Comment by ripienaar** [comment]
Yes, as above I'll do such a build and let you know if they help.

**Comment by kozlovic** [comment]
Thanks, and keep in mind that the Go clients too need to be build with Go 1.8+ in order to have access to those ciphers. Otherwise, they will negotiate older slower ciphers than the CHACHA ones.

**Comment by ripienaar** [comment]
```
TLS configuration is specified in the tls section of a configuration file:

e.g.

    tls {
        cert_file: "./certs/server-cert.pem"
        key_file:  "./certs/server-key.pem"
        ca_file:   "./certs/ca.pem"
        verify:    true

        cipher_suites: [
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        ]
        curve_preferences: [
            "CurveP256",
            "CurveP384",
            "CurveP521"
        ]
    }

Available cipher suites include:
    TLS_RSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    TLS_RSA_WITH_AES_128_CBC_SHA
    TLS_RSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_RSA_WITH_RC4_128_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
    TLS_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    TLS_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    TLS_RSA_WITH_RC4_128_SHA

Available curve preferences include:
    X25519
    CurveP256
    CurveP384
    CurveP521
```

Do you have a suggestion of an exact config you'd like me to run a test against?

**Comment by kozlovic** [comment]
You could first try without any specific config. You should see that the cipher selected (again assuming that your Go client has also been built with Go 1.8) should now be different. Otherwise, try with any of those:
```
TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
```
and see which one "performs" better. Thanks!

**Comment by ripienaar** [comment]
OK, will revert 'morrow and let you know

**Comment by tylertreat** [comment]
@kozlovic is there a different default cipher suite in Go1.8?

**Comment by kozlovic** [comment]
Yes. When no cipher is configured, in Go 1.8, the NATS Server will use these as the default:
```
tls.TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,
tls.TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,
tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
```
Below 1.8, it uses:
```
tls.TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,
tls.TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,
tls.TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,
tls.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,
```

**Comment by ripienaar** [comment]
Did various things, nothing really improves matter significantly.  I did though add a ton of debug code and all the time it spent here:

https://github.com/golang/go/blob/718d9de60fd4337d9044cdc2c685177dd2177ef6/src/crypto/tls/conn.go#L1255

So way out of your control, so I guess I am just going to have to write this down as That's Just How It Is.

**Comment by tylertreat** [comment]
@ripienaar Are you running a single gnatsd server? If so, can you spread the connections across a cluster of servers rather than a single one?

**Comment by ripienaar** [comment]
Yes, well for sure cluster them not just for this but for general operability and availability.  Still I am looking at in a cluster of 3 each one handling a rather large amount of connections and the concern is around how long are maintenance windows for etc

Anyway, we have little choice and even with this being bad, its a LOT better than our alternative

**Comment by kozlovic** [comment]
Is your CentOS an ARM architecture? If so, there are some perf issue with Go on that platform due to lack of some optimizations. Here are few links that may give you some context: https://github.com/nats-io/gnatsd/issues/466 and https://github.com/golang/go/issues/19840.

**Comment by ripienaar** [comment]
64bit Intel CentOS/RHEL/Others - but all Intel.
