### ISSUE TITLE
Parser Error Error reading from client: Client Parser ERROR, state=31, i=1: proto='"SH-2.0-libssh2_1.7.0\r"...'

### ISSUE THREAD

**Issue by robertfreund** [nats-io/gnatsd#596]
Seeing the following parsing errors in the gnats logs.

 cid:2720 - Error reading from client: Client Parser ERROR, state=31, i=1: proto='"SH-2.0-libssh2_1.7.0\r"...'

Any idea what causes this. 
[1] 2017/10/06 04:26:26.931162 [INF] Starting nats-server version 1.0.4

**Comment by kozlovic** [comment]
Someone tried to ssh to your gnatsd. The error gives a hint: `..libssh..`

**Comment by xiaomi-tc** [comment]
I get something like this,  nats-streaming-server run at two host:

```
[host_1]#  ./nats-streaming-server -cid cluster-1 -st FILE --dir /tmp/data -p 5222 -m 8222 --cluster nats://192.168.223.100:5248

[host_2]# ./nats-streaming-server -cid cluster-2 -st FILE --dir /tmp/data -p 5222 --cluster nats://192.168.223.150:5248 --routes nats://192.168.223.100:5248
```
at host_1 output:
```
[6957] 2017/12/28 14:34:45.182325 [ERR] 192.168.223.150:57264 - cid:4 - Error reading from client: Client Parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 192.168.22"...'
[6957] 2017/12/28 14:34:55.182712 [ERR] 192.168.223.150:57304 - cid:5 - Error reading from client: Client Parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 192.168.22"...'
[6957] 2017/12/28 14:35:05.187227 [ERR] 192.168.223.150:57344 - cid:6 - Error reading from client: Client Parser ERROR, state=0, i=0: proto='"GET / HTTP/1.1\r\nHost: 192.168.22"...'
```

**Comment by wallyqs** [comment]
@xiaomi-tc something would have made an HTTP request to the client port of the server (-p 5222 in your example, maybe it was confused with 8222 port)

**Comment by FlightToFreedom** [comment]
Is there a way to expand logging to show all lines?
I get an ERR for one of my post request to my NATS server and i cant figure out why that happens.
`cat debugLog.txt
== Info: Rebuilt URL to: nats.PROJECTNAME-test.svc:4222/
== Info:   Trying 10.254.48.XX...
== Info: Connected to nats.PROJECTNAME-test.svc (10.254.XX.XX) port 4222 (#0)
=> Send header, 182 bytes (0xb6)
0000: POST / HTTP/1.1
0011: Host: nats.PROJECTNAME-test.svc:4222
0031: User-Agent: curl/7.47.0
004a: Accept: */*
0057: Content-Length: 2189
006d: Content-Type: application/x-www-form-urlencoded
009e: Expect: 100-continue
00b4:
<= Recv data, 256 bytes (0x100)
0000: INFO {"server_id":"8Q2E4nc5bmNnidrEpdq8ex","version":"1.2.0","pr
0040: oto":1,"git_commit":"6608e9a","go":"go1.10.3","host":"0.0.0.0","
0080: port":4222,"max_payload":1048576,"client_id":277,"connect_urls":
00c0: ["10.254.XX.XX:4222","10.254.XX.XX:4222","10.254.XX.XX:4222"]}
<= Recv data, 35 bytes (0x23)
0000: -ERR 'Unknown Protocol Operation'
== Info: Connection #0 to host nats.infra-test.svc left intact
`
When i check the logs in the server, i see a different error:
`kubectl -n infra-test logs nats-1 -c nats | grep "14:35:39.708491"
[7] 2019/05/21 14:35:39.708491 [ERR] 10.254.XX.XX:57484 - cid:276 - Client parser ERROR, state=26, i=2: proto='"ST / HTTP/1.1\r\nHost: nats.PROJECTNAME-"...'`
I would like to expand the whole error message to see what is wrong in that request, probably the problem sits behind the '...'

**Comment by kozlovic** [comment]
@FlightToFreedom The problem is that someone probably sends an HTTP request (monitoring request maybe?) to the NATS client listen port. That is, a non NATS client is connecting to the NATS Server client port.

**Comment by derekcollison** [comment]
The NATS server does not accept HTTP POST requests, only GET in monitored mode `-m`.

Fo more verbose output when the server is running try `nats-server -DV`

**Comment by FlightToFreedom** [comment]
> That is, a non NATS client is connecting to the NATS Server client port.

Thank you for taking the time to reply, does that mean i have to subscribe first?
My JSON payload is in the following format:
`clientID:"NOT_A_REAL_REGISTERED_CLIENT"
guid:"YmtE8OJQZMFASNpg81GO2y"
subject:"A_SUBJECT"
{"data":{`

So, beside having to change the method of my request (thank you @derekcollison for the suggestion), can i use the name of an actively registered client to send a message?
I have a pod running a Webhook container, forwarding to NATS requests coming from a Bitbucket client, i want to (integration) test from NATS onward, so ideally my role in my test would be 'webhook' and i am writing a CURL script that sends requests to NATS.
Sorry if this looks like too much like a stackoverflow question.
Thx

**Comment by derekcollison** [comment]
NATS currently does not support sending or receiving messages via any form of HTTP. So you would need to terminate the websocket and send to NATS with a normal NATS client. 

This can help find some solutions that already exists and may fit your problem space.

https://www.google.com/search?q=websockets+NATS&oq=websockets+NATS

**Comment by satyajituk** [comment]
How will it work in case there is a load balancing sidecar e.g. Linkerd or istio in the service? In that case the nats connection will be made through the sidecar which won't work.

**Comment by derekcollison** [comment]
Correct, any layer 7 proxy will not work for the most part if placed in between a NATS client and server.
