### ISSUE TITLE
Data Race

### ISSUE THREAD

**Issue by derekcollison** [nats-io/gnatsd#60]
https://travis-ci.org/apcera/gnatsd/builds/39413956#L358

**Comment by derekcollison** [comment]
https://travis-ci.org/apcera/gnatsd/jobs/66923669

**Comment by derekcollison** [comment]
https://travis-ci.org/apcera/gnatsd/builds/66927045

**Comment by derekcollison** [comment]
https://travis-ci.org/apcera/gnatsd/builds/66957488

**Comment by dgryski** [comment]
Since the move apcera -> nats-io, all these links are broken.

**Comment by derekcollison** [comment]
Yes I realize that but have most of these addressed. Will do a run through to recreate some on Travis, etc. Thanks though for pointing it out.
