### ISSUE TITLE
Monitor /connz endpoint returns empty reply

### ISSUE THREAD

**Issue by akabos** [nats-io/gnatsd#600]
When I try to query /connz endpoint with offset close to the end of the connections list, I get an empty response from the server. Unfortunately, I wasn't able to find any relevant log entries. 

 - [X] Defect
 - [ ] Feature Request or Change Proposal
 
#### Versions of `gnatsd` and affected client libraries used:

gnatsd v1.0.4

#### OS/Container environment:

Debian 9.2 Stretch

#### Steps or code to reproduce the issue:
```
$ curl -i 'http://127.0.0.1:8222/connz?limit=1'
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 08 Nov 2017 08:46:19 GMT
Content-Length: 695

{
  "now": "2017-11-08T08:46:19.287041042Z",
  "num_connections": 1,
  "total": 4778,
  "offset": 0,
  "limit": 1,
  "connections": [
    {
...
```

```
curl -i 'http://127.0.0.1:8222/connz?limit=10&offset=4710'
curl: (52) Empty reply from server
```

#### Expected result:

Proper response
 
#### Actual result:

Empty reply

**Comment by akabos** [comment]
Update. When I sort query by `idle` endpoint returns empty reply for the beginning of the list instead:

```
$ curl -i 'http://127.0.0.1:8222/connz?sort=idle'
curl: (52) Empty reply from server

Content-Type: application/json
Date: Wed, 08 Nov 2017 09:16:01 GMT
Transfer-Encoding: chunked

{
  "now": "2017-11-08T09:16:01.577141479Z",
  "num_connections": 938,
  "total": 4938,
  "offset": 4000,
  "limit": 1024,
  "connections": [
    {
...
```

**Comment by akabos** [comment]
This is what fixed the issue for me:

```
--- a/server/monitor.go
+++ b/server/monitor.go
@@ -81,6 +81,7 @@ func (s *Server) HandleConnz(w http.ResponseWriter, r *http.Request) {

        auth, _ := strconv.Atoi(r.URL.Query().Get("auth"))
        subs, _ := strconv.Atoi(r.URL.Query().Get("subs"))
+       tlsinfo, _ := strconv.Atoi(r.URL.Query().Get("tlsinfo"))
        c.Offset, _ = strconv.Atoi(r.URL.Query().Get("offset"))
        if c.Offset < 0 {
                c.Offset = 0
@@ -208,7 +209,7 @@ func (s *Server) HandleConnz(w http.ResponseWriter, r *http.Request) {
                }

                // If the connection is gone, too bad, we won't set TLSVersion and TLSCipher.
-               if tlsRequired && client.nc != nil {
+               if tlsinfo == 1 && tlsRequired && client.nc != nil {
                        conn := client.nc.(*tls.Conn)
                        cs := conn.ConnectionState()
                        ci.TLSVersion = tlsVersion(cs.Version)

```

I'm under impression that call to `conn.ConnectionState()` gets blocked for for TLS connections still in handshake process. I don't need that info, so I excluded it from default output.

I'd like someone from core team to comment if this patch has any chances to get into master. If so, I'm ready to prepare proper pull request.

**Comment by kozlovic** [comment]
Thank you for the report, I am looking into this and will get back to you shortly.

**Comment by kozlovic** [comment]
@akabos See PR #603. The issue was related to incorrect setting of a WriteTimeout (this applied also to the Profiler http server). The ConnectionState() could be one reason why the request would take time to process, but the issue would have happened for other endpoints for other reasons (locking of a resource, number of objects to return, etc...).

**Comment by akabos** [comment]
@kozlovic This fix helps in the sense that response is not empty any more. But now response times are ridiculously high when requested offset+limit contains connections currently in handshake. As far as I can tell, for ech such connection execution blocks until handshake is finished. This is especially problematic immediately after gnatsd restart because every client attempts to reestablish connection.

**Comment by kozlovic** [comment]
@akabos Agreed. PR #604 should address the issue without the need for a new parameter in the Connz endpoint.
