### ISSUE TITLE
Require optional fields to begin with a alphabetic character.

### ISSUE THREAD

**Issue by dbeecham** [nats-io/gnatsd#605]
- [ ] Defect
 - [X] Feature Request or Change Proposal
 
#### Use Case:

Parsing protocol (very) quickly and/or parsing protocol "[online](https://en.wikipedia.org/wiki/Online_algorithm)" . (gnatsd *do* want to be the fastest, right? :))
 
#### Proposed Change:

Currently, the `MSG` message has the following syntax:

`MSG <subject> <sid> [reply-to] <#bytes>\r\n[payload]\r\n`

If a client has read the characters `MSG subject `, and the following character read is a `1` - there is no way of knowing if this character is part of the `[reply-to]` or the `<#bytes>`. However, if `[reply-to]` is required to begin with an alphabetic character (or punctuation etc - anything that's not a digit), then a proposed parser would immediately know - if it's a digit, then it's the `<#bytes>`, otherwise it's a `[reply-to]`.

The same thing applies to `PUB`, of course, which needs an alphabetic character in it's `[reply-to]` as well, and `SUB`, which needs a way to differentiate `[queue-group]` and `<sid>` by first characted (e.g. sid's are numbers, queue-groups begin with a letter).

It's a very small change, but I'm not sure how many people it could potentially affect - I guess there are people out there using `uuidgen` or similar to generate `[reply-to]` addresses, and those can indeed begin with a number.
 

#### Who Benefits From The Change(s)?

gnatsd could make an *even faster* parser! (though, of course, it's not clear that parsing is a bottleneck in gnatsd, but nonetheless, it's cool, I think)
I have a personal favorite in parsing, namely [Ragel](http://www.colm.net/open-source/ragel/) - now, Ragel effectively operates within the realms of Ludicrous Speed, and it's possible to imagine a world where gnatsd has a C parsing core using Ragel, and along with this change it's a mathematically safe bet that your parsing, at the very least, would be faster!

Clients could, of course, also parse more quickly, by the same logic. SPEED!
 

#### Alternative Approaches

* Clients decide these rules for themselves - then the clients can parse in ludicrous speed as long as every client obeys by this rule. A publisher that does not obey will create wierd issues in all subscribers.
* The NATS protocol *is* regular - which is great, because it's possible to *validate* any NATS message in a finite state matchine. Thus, if every message is small enough that you can hold the message in a single buffer, you keep pointers into the buffer indicating where the `[reply-to]` and `<sid>` is -  then you can do a "fixup" in constant time - handle `[reply-to]` *as a `<sid>`*, but when you fail to read the `\r\n`. then you know it really was a `[reply-to]`, and not a `<sid>` - and you move the pointers.
* I guess you could keep three buffers, one called `subject`, one called `second`, and one called `third`. Copy characters between the spaces to each group. If you encounter the `\r\n` and `third` is empty, then you know that `second` was a `<sid>` - otherwise it's a `[reply-to]`. I guess this approach makes sense, and it's just as fast, it's online and regular... it's uglier though.
* Who cares about quick parsing anyway? I like walking pace, it's peaceful.

(I get that the protocol is probably final, but I just want to throw this out there and see if it sticks)

**Comment by ColinSullivan1** [comment]
@dbeecham , Thank you for raising this issue.  We're always concerned about performance, and your suggestion sounds like it would speed things up...  

Unfortunately your proposed change would be a breaking change in the protocol and could negatively impact many users.  Subjects often begin with numbers - think VIN numbers, license plates, tax ids, phone numbers, etc.

Your suggestion of using pointers (2nd bullet point) sounds interesting, although I'd think you'd still need a copy of the subjects.  The third bullet point of using buffers is interesting too, but you'd have the same memory copies made as the current code does.  That being said, ugly can be OK if there are big performance gains.

Have you tested the second/third bullet points to see if they are faster?

**Comment by dbeecham** [comment]
I wrote an implementation for number 3 (and number 1) on the client side only. I guess I can try to do some kind of benchmark, if I figure out how. But it should be just as fast, in theory... which essentially makes this issue resolved...

Another thing that came to mind as I've been doing this is that gnatsd could handle publishes to a topic with no subscriber super efficiently with this kind of implementation. As in, it would be doing a single compare-and-jump for each character read, and then return the usual '+OK\r\n'. gnatsd would handle as many publishes as the network can send data to topics with no subscriber. I guess it's a bit of a fringe case, but still.

Anyway, I think I'll close this issue so as to not leave this hanging on your shoulders, but I will keep experimenting and see what I can do.
