### ISSUE TITLE
heart-beat between server and client ,message compress and encrypt

### ISSUE THREAD

**Issue by asialiugf** [nats-io/gnatsd#607]
is there heart-beat between server and client ?

may be, messages need to be compressed  and encrypted.

**Comment by ColinSullivan1** [comment]
@asialiugf , Thank you for using NATS!

There is a heartbeat; see `PING/PONG` in our [protocol documentation](http://nats.io/documentation/internals/nats-protocol/).  

We really haven't found the need to compress messages internally - the NATS protocol is very light. You can always compress your message payload - NATS is payload agnostic.  

Regarding encryption, we do support [TLS](https://github.com/nats-io/gnatsd#tls).

Can you describe your use case?

**Comment by asialiugf** [comment]
thank you for your response.

I want to use NATS in algorithm trading system .  we have a data_server that contain ticks bar data and other useful basic data .  the data_server will pub ticks or bars (( no need to be guarantied  for real time tick , backend test ticks and bars need to be guarantied)) to many clients and sometimes ,some clients will get special data(need to be guarantied )  from data_server.   

can I use PUB/SUB and request/response  in the same TCP/IP connection ?

**Comment by ColinSullivan1** [comment]
@asialiugf , thank you for sharing.  You can use publish/subscribe and request/reply over the same connection.

**Comment by asialiugf** [comment]
thank you so much !
