### ISSUE TITLE
how to close ping timer 

### ISSUE THREAD

**Issue by lxcyha** [nats-io/gnatsd#609]
My application has not been operated for a long time . and then the client does not respond to the server's Ping . causing message loss. so i want to close ping timer .

**Comment by kozlovic** [comment]
@lxcyha Not sure what you are asking here. If your application is running, it should respond to server PINGs. Which client library are you using? I believe that all the Apcera supported ones do that.

You can tune the ping interval and max failed ping on the server side, but that is a server wide parameter, not specific to a client. In configuration file, that would be:
```
ping_interval: <number of seconds>
ping_max: <number of PING without a PONG from client after which the connection will be closed>
```

**Comment by kozlovic** [comment]
Closing due to age. Please feel free to re-open if you have more questions.
