### ISSUE TITLE
Log route creation errors at error level

### ISSUE THREAD

**Issue by ripienaar** [nats-io/gnatsd#610]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
#### Use Case:

Improve debugging route errors and general life cycle.  

It's presently hard to know when routes go up and down and if there are errors in this life cycle since this stuff is all logged at debug level.  Routes are pretty important so raising the visiblity of these will help people figure out they have issues
 
#### Proposed Change:
Log https://github.com/nats-io/gnatsd/blob/b002db4a1c66b883fe308838f8cea42d50aa83a7/server/route.go#L244 and  https://github.com/nats-io/gnatsd/blob/b002db4a1c66b883fe308838f8cea42d50aa83a7/server/route.go#L378 at error level

And in https://github.com/nats-io/gnatsd/blob/b002db4a1c66b883fe308838f8cea42d50aa83a7/server/route.go#L317 once the route connection is established log an info message

#### Who Benefits From The Change(s)?

People who run nats clusters

**Comment by tylertreat** [comment]
Thanks, I will take a look at this.
