### ISSUE TITLE
improve access to Server stats

### ISSUE THREAD

**Issue by ripienaar** [nats-io/gnatsd#612]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
#### Use Case:

when embedding gnatsd into another program I want to be able to access its stats and perhaps expose those to prometheus or whatever

#### Proposed Change:

Today those structures all unexported - and the stats gathering is done kind of ln-line in the http handlers.  So it's very hard to access the stats, you more or less have to reinvent that wheel.
 
The methods https://github.com/nats-io/gnatsd/blob/ee7b97e6ee3068900d39f1fe4ae7b75f358416ab/server/server.go#L868 seems about the only way to get to this information - and the comment there makes me reluctant to use those as thats probably not part of the supported API.

For my personal use case I just want a copy of the Varz structure populated, so extracting the code to build up that structure and making a getter for it would be amazing, but I think the monitoring in general can be greatly improved along these lines
 
#### Who Benefits From The Change(s)?

people who embed gnatsd
 
#### Alternative Approaches

Today the only option is HTTP requests to /varz

**Comment by cdevienne** [comment]
I support this idea, I too am embedding gnatsd (in xbus) and would benefit a lot from it.

**Comment by AshfordN** [comment]
I support this idea. I think more functionalities should be exposed when embedding servers.
