### ISSUE TITLE
is there a recommended maximum number of servers for nats cluster ?

### ISSUE THREAD

**Issue by danlanxiaohei** [nats-io/gnatsd#617]
#### Use Case:
 
i want to know whether NATS is not recommended to be used in a big cluster (For example a cluster which include 100 servers) ? 
as we know NATS clustered servers have a forwarding limit of one hop，so i guess  each server must connect to the others directly. 

if true , is there a recommended maximum number of servers for nats cluster ?
like 10 servers ? 100 servers? or ?

**Comment by ColinSullivan1** [comment]
@danlanxiaohei , Thank you for your interest in NATS.

It depends - can you describe your use case further?

While connections between servers in a cluster are lightweight (not that much different than client connections), the server to server protocol will send messages about cluster topology and subscription interest as required.  So if you have many clients frequently subscribing to unique subjects, or servers frequently joining and leaving, you can generate quite a bit of chatter (https://github.com/nats-io/gnatsd/issues/462 will mitigate this for some use cases) in a very large cluster.  You'll also have some heartbeats between servers adding a small amount of traffic between servers in the cluster.

100 would be large, I'd recommend starting smaller and scaling up as necessary.  For most deployments, a cluster of 3-5 servers will suffice, but again, it depends on your use case.

**Comment by danlanxiaohei** [comment]
@ColinSullivan1  , Thanks for your reply.
Here is my use case.
I am building a IM Server which used in broadcasting live (something like facebook live)
In this condition, a large numbers of viewers in the room (100,000 viewers) , once a member in the room send a message , the others should receive it .
As you can see in my architecture, **Connectors** keep all the user's connections (we got 10*20 connectors ), **Logic Router** receive the message then send it to it's **Logic Worker** , after the Logic Worker finished , it send a message to the **Logic Router** to boardcast this message to all the Connectors. so , we want to use NATS to boardcast this message and NATS can do it well, till now, everything seems ok.
but , now we got 1000 rooms online , each room send 10 messages every second, and we got 200 connectors , so we totally have 200*10*1000=2,000,000 messages through out the NATS cluster each second. 
so, i am not so sure that how many Servers in the cluster can handle this large number of messages each second ?
by the way , as our users increase, in future ,we may got more users online, can i just add more nats servers in the cluster to increase the ability to boardcast? we don't want NATS become the bottleneck of the hole architecture. 
![d15620fe-601e-4478-9683-6ac14d3136ba](https://user-images.githubusercontent.com/3272530/34814565-19f3fbdc-f6e9-11e7-812c-80dee5c24ec8.png)

**Comment by ColinSullivan1** [comment]
@danlanxiaohei , Thank you for sharing!  

You can scale by adding NATS servers, and it's relatively painless to do so from a DevOps perspective - just launch another NATS server using the `--cluster` and `--routes` parameters to pointing to a server in your cluster.  That's it. 

It is difficult to give you a # of servers - you'll want to test in your environment.  Scalability is highly dependent on the hardware resources you have.  Message size and your subject namespace will also affect scalability.

With this architecture, if you need to, bear in mind that you can federate NATS, where instead of one very large NATS cluster, you'd have multiple smaller NATS clusters, each covering a subset of connectors.  The logic router would connect to multiple NATS clusters, then send to the appropriate NATS cluster(s).

**Comment by ColinSullivan1** [comment]
What is your average message size and what does your subject namespace look like?

**Comment by derekcollison** [comment]
I would start with one server and see how it runs at speed. %CPU and %MEMORY(RSS) consumed. Most NATS clusters are 1,3 or 5 servers big.

The other limiting factor can be how many connections you can make to a single server and what memory that consumes as well.

**Comment by danlanxiaohei** [comment]
@ColinSullivan1 the average message size is 300-500 bytes . and my boardcast subject is 'chatroom'
so , which kind of subject is better , long string or short string ?

**Comment by derekcollison** [comment]
The subject in your scenario will not make a difference.
