### ISSUE TITLE
Migrate all NATS Repositories to Apache License 2.0

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/gnatsd#618]
The NATS team will migrate all [nats-io repositories](https://github.com/nats-io) from using MIT licensing to [Apache License Version 2.0](https://www.apache.org/licenses/LICENSE-2.0), as a requirement to join CNCF.

We wanted to open up discussion from the community here; any comments or questions are welcome.

**Comment by qrpike** [comment]
@ColinSullivan1  Would be good to know the reasons for the change. Also what it means for those using NATS.

Thanks,

**Comment by ColinSullivan1** [comment]
@qrpike , Thank you for the comment.  The only reason we are changing licenses is because Apache 2.0 is a requirement to join the [CNCF](https://www.cncf.io/).  We're in the process right now, feel free to check out [our proposal](https://github.com/ColinSullivan1/toc/blob/dbccc77c41534fd565008b80bb80d2cf77d6658d/proposals/nats.adoc).  

We feel NATS is a great fit for CNCF., and joining will be good for NATS and the community.

Regarding usage, this change will not affect how or where NATS can be used.  A good comparison of license types can be found [here](https://exygy.com/which-license-should-i-use-mit-vs-apache-vs-gpl/).

**Comment by ripienaar** [comment]
are you going to do contributor licences? what process do you anticipate for that if you do plan to have those?

**Comment by wallyqs** [comment]
More background on why the CNCF suggests adopting Apache License 2.0 can be found in this post  too https://www.cncf.io/blog/2017/02/01/cncf-recommends-aslv2/

**Comment by laugimethods** [comment]
Take note that this migration might impact other projects based on NATS librairies (like https://github.com/Logimethods/nats-connector-spark ).

**Comment by ColinSullivan1** [comment]
@ripienaar , TBD...  We are looking for guidance from CNCF regarding CLAs and contributions.  Our goal is to find a straightforward process that meets the CNCF’s requirements, but is not burdensome for contributors.  We'll work to keep things easy.

**Comment by ripienaar** [comment]
@ColinSullivan1 ok, thanks! sure its fine anyway, I've signed many CLAs

**Comment by derekcollison** [comment]
Closing, I think they are all moved.
