### ISSUE TITLE
tls

### ISSUE THREAD

**Issue by huangyigui** [nats-io/gnatsd#627]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `gnatsd -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (http://stackoverflow.com/help/mcve)

**Comment by huangyigui** [comment]
apinats@linux:~/nats/bin> ./gnatsd --version
nats-server version 0.9.4

apinats@linux:~/nats/bin> ./gnatsd --help_tls

TLS configuration is specified in the tls section of a configuration file:

e.g.

    tls {
        cert_file: "./certs/server-cert.pem"
        key_file:  "./certs/server-key.pem"
        ca_file:   "./certs/ca.pem"
        verify:    true

        cipher_suites: [
            "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
            "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
        ]
    }

Available cipher suites include:

    TLS_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    TLS_ECDHE_ECDSA_WITH_RC4_128_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_RC4_128_SHA
    TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    TLS_RSA_WITH_RC4_128_SHA
    TLS_RSA_WITH_AES_128_CBC_SHA
    TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    TLS_RSA_WITH_AES_256_CBC_SHA
    TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256

Expected result: server-key.pem should support set password.and password should be encrypted by hash(such as pbkdf2) 
Actual result:currently, server-key.pem does not support set password.

**Comment by derekcollison** [comment]
That is correct. Usually production systems that are automated should not require stdin input before starting.

**Comment by huangyigui** [comment]
I mean, certificate's private key should be encrypted, currently, private key's content is plaintext, this do not satisfy security specification.

**Comment by derekcollison** [comment]
I understand. If the key is encrypted, either you have to prompt a user for the password or supply the password on the command line. Most automated systems prefer to secure the private_key.pem file.
