### ISSUE TITLE
Feature Request: Draining on maintenance/upgrade

### ISSUE THREAD

**Issue by bmcstdio** [nats-io/gnatsd#628]
- [ ] Defect
 - [X] Feature Request or Change Proposal
 
#### Use Case:

Under certain circumstances (rolling version upgrade, maintenance, etc.) it may be necessary/desirable to take down a clustered `gnatsd` server without losing messages yet undelivered to subscribers (or at least minimizing the losses).

#### Proposed Change:

The `gnatsd` server to be taken down should perhaps be able to receive a new type of [signal](https://github.com/nats-io/gnatsd/blob/master/server/signal.go#L20) and

- stop accepting new connections.
- close all active connections.
- drain itself (i.e., move all messages contained in the server to other servers in the cluster).
 
#### Who Benefits From The Change(s)?

Users needing to perform maintenance or updates in a given `gnatsd` clustered server.

#### Alternative Approaches

None that I am aware of.

---

I understand that this use-case may be better suited for NATS Streaming, but we'd like to be able to take nodes down for maintenance (mostly to cover a rolling version upgrade scenario, but this would also work in basic maintenance) and support for this in NATS would come in really handy. Is there any possibility of having this land in a future version?

**Comment by derekcollison** [comment]
Agree, we need to formalize lame duck mode and have clients intelligently switch to new server.

**Comment by bmcstdio** [comment]
That's great! I am not all that familiar with the `gnatsd` codebase, but PLMK if there is some way I can contribute.

**Comment by derekcollison** [comment]
Eventually we will also support hot swap of binaries on certain platforms.

**Comment by gedw99** [comment]
Thanks @derekcollison !

This is a big issue for us. Any ideas of progress ?

I came here to ask about Config updates actually and in many ways this issue might also support the requirement for doing config changes as part of operations also ?

**Comment by derekcollison** [comment]
Draining is also on my list. However, just note that the server part is easy, its the client mechanics that will be more complicated to provide the best experience. We already do well on published messages and hold them for the new connection. The trick is on subscriptions and forming the new connection while the draining one is still connected, and understanding as a complete set over all subscriptions when the new connection is good to go.

**Comment by derekcollison** [comment]
I believe this has been addressed with #780.

We still want to add in more intelligence to the clients in the future.
