### ISSUE TITLE
Windows Log Rotation catch-22: cannot rename old file because it is locked

### ISSUE THREAD

**Issue by acadiant** [nats-io/gnatsd#630]
- [X] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `gnatsd -DV` output
 - [X] Included a [Minimal, Complete, and Verifiable example] (http://stackoverflow.com/help/mcve)
 
#### Versions of `gnatsd` and affected client libraries used:
nats-server 1.0.4

#### OS/Container environment:
Windows Server 2008R2

#### Steps or code to reproduce the issue:
(1) Configure gnatsd as a Windows service, log to a file [WINDOWS ONLY]
(2) Attempt to rotate the log: ren (cmd.exe) or Move-Item (PowerShell) fails because log file is in active use.
 
#### Expected result:
Rename or Move allowed; then gnatsd.exe -sl reload should restart logging to the (now empty) log file 

#### Actual result:
No way to rotate the existing log file out of the way.
 
#### Proposed Change:
Possibility 1: Close log file through gnatsd.exe -sl command
Possibility 2: Include FILE_SHARE_DELETE flag when calling CreateFile. This might allow renaming of the file. See URL below.
https://msdn.microsoft.com/en-us/library/windows/desktop/aa363858(v=vs.85).aspx

#### Who Benefits From The Change(s)?
Anyone running gnatsd.exe on Windows logging to file
 
#### Alternative Approaches
Log to syslog (syslog:true in .cfg or --syslog on gnatsd.exe command line)

**Comment by ColinSullivan1** [comment]
Just making a note that I'm aware of this, and will try to take a look in next few days.
