### ISSUE TITLE
Defect: messages lost with non-zero max_msgs in 2-node cluster (bi-directional routes)

### ISSUE THREAD

**Issue by vkhorozvs** [nats-io/gnatsd#632]
### Versions of `gnatsd` affected:
Found in v0.9.4, reproduced in v1.0.4.
Most probably affects all versions.

### OS/Container environment:
Linux CentOS 7

### Steps or code to reproduce the issue:
1. Setup a NATS cluster of 2 (or more) nodes with bi-directional routes.
2. Connect 2 (or more) queue subscribers with max_msgs set to non-zero value to different NATS server nodes.
3. Have 2 (or more) publishers connect to different NATS server nodes.
4. Let publishers publish as many messages as needed to feed all subscribers.
    E.g. with 2 nodes, 10 subscribers, and max_msgs set to 1 need to publish 20 messages.
 
### Expected result:
All messages are delivered
 
### Actual result:
Some messages are lost.
An exact number differs from test to test, sometimes all messages are delivered.

### Test Code:
I've created the following bash script to reproduce this issue:
```
./gnatsd -p 4001 --cluster nats-route://localhost:4011/ --routes nats-route://localhost:4012/ &
./gnatsd -p 4002 --cluster nats-route://localhost:4012/ --routes nats-route://localhost:4011/ &
sleep 1
for i in `seq 100`; do
    ( echo "sub foo bar $i"; echo "unsub $i 1"; sleep 5; ) | nc localhost 400$(($i % 2 + 1)) -C &
done
sleep 1
for i in `seq 0 9`; do
    ( sleep 1; for n in `seq 0 9`; do echo 'pub foo 6'; echo "test$i$n"; done ) | nc localhost 400$(($i % 2 + 1)) -C &
done

sleep 5

kill %1 %2
```

A test script is sending 100 messages from 10 publishers to 100 subscribers with 2 NATS server nodes.

**Comment by vkhorozvs** [comment]
I've run a test script 20 times for each NATS version and got below results:
```
[vkhoroz@localhost gnatsd]$ for t in `seq 20`; do ( cd ~/work/cis/brokers/gnatsd-v0.9.4-linux-amd64/ && bash ~/work/cis/opensource/go/src/github.com/nats-io/gnatsd/test.sh 2>&1 | grep test | wc -l ) && sleep 1; done
97
100
99
99
97
98
99
99
95
100
100
100
92
96
98
96
94
100
99
100
[vkhoroz@localhost gnatsd]$ for t in `seq 20`; do ( cd ~/work/cis/brokers/gnatsd-v1.0.4-linux-amd64/ && bash ~/work/cis/opensource/go/src/github.com/nats-io/gnatsd/test.sh 2>&1 | grep test | wc -l ) && sleep 1; done
94
99
96
100
99
95
100
95
94
100
90
100
96
100
100
99
91
96
93
98
```

**Comment by vkhorozvs** [comment]
A problem is a race condition inside server/client.go in processMsg related to how unsubscribe is broadcasted between routes.  I've created a patch to fix this issue (will create a pull request in short).

With patched NATS server no messages were lost:
```
[vkhoroz@localhost gnatsd]$ for t in `seq 20`; do bash ./test.sh 2>&1 | grep test | wc -l && sleep 1; done
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
100
```

However, I'd like to ask somebody from NATS core developers to assess if all use cases are covered.
I would appreciate if a patch is included in some of upcoming releases.

**Comment by derekcollison** [comment]
Thanks, looking forward to the PR. Much appreciated.

**Comment by derekcollison** [comment]
This worked better but had a possibility of duplicates. PR #680 fixes.
