### ISSUE TITLE
Gnatsd application crashed when started on Network service

### ISSUE THREAD

**Issue by ManojGopan** [nats-io/gnatsd#637]
I have downloaded Nats server "gnatsd-v1.0.4-windows-amd64.zip". 
I have an application that starts all processes in Network service. When I started the gnatsd 1.0.4 on Network service account, gnatsd is crashing showing exit code 1.

This was working for the version gnatsd 0.9.4. 
Could you please help to fix the issue in 1.0.4?

**Comment by kozlovic** [comment]
I know you are not running a docker image, but we had this issue: https://github.com/nats-io/gnatsd/issues/543
May I ask you to try running gnatsd with the following environment variable set?
```
NATS_DOCKERIZED=1
```
and see if it fails? Thanks!

**Comment by ManojGopan** [comment]
It worked.
Thank you so much!
