### ISSUE TITLE
Develop project governance (GOVERNANCE.md)

### ISSUE THREAD

**Issue by caniszczyk** [nats-io/gnatsd#649]
Each CNCF project is expected to declare it's governance model and abide by it.

You can look at our other projects for examples: https://github.com/envoyproxy/envoy/blob/master/GOVERNANCE.md
https://prometheus.io/governance/

**Comment by derekcollison** [comment]
@ColinSullivan1 We have this for all projects correct?

**Comment by ColinSullivan1** [comment]
All NATS projects will fall under the same governance, I like Prometheus' model where it is on the website.  We have one today under our [contributing](https://nats.io/documentation/contributing/) page, but need to revisit and get maintainer buy-in.

**Comment by gcolliso** [comment]
Main GOVERNANCE.md added to nats-io/general all other public repositories updated to include GOVERNANCE .md with reference to original.
OWNERS has been renamed to MAINTAINERS.md and updated to reflect maintainership per project.
