### ISSUE TITLE
configure topic separator

### ISSUE THREAD

**Issue by guanqun** [nats-io/gnatsd#652]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
## Feature Requests
Is it possible that we can configure the topic's separator using "/" instead of "." ? Dot means "match one character" in regular expression, so it's a bit counter intuitive to be a separator, while "/" is similar to path's separator. 
 
#### Proposed Change:

allow a config to set the topic separator to be "/" 

#### Who Benefits From The Change(s)?
 
More friendly to new users.

**Comment by derekcollison** [comment]
Dot is historic and is baked into the server and all clients. I would suggest that for your client you write an abstraction layer that does the translation.
