### ISSUE TITLE
Feature Request: Extended monitoring

### ISSUE THREAD

**Issue by Sergey-Terekhin** [nats-io/gnatsd#654]
- [ ] Defect
 - [x] Feature Request or Change Proposal
  
#### Use Case:
We're using NATS as integration bus between our services. While developing new service it would be very useful to know not only about existing subscriptions but also about published topics too.

For example, Service1 waits messages published by topic "Messages-For-Service1", but Service2 publishes messages with topic "Messages-From-Service2". And, as expected, Service1 never receives any message/ But discrepancy of message topics can be found only from logs (if any) or debugger must be attached to both services.
It is possible to get name of subscription but no information about published messages
 
#### Proposed Change:
Add new monitoring endpoint that will show all topics of messages published to the NATS (possible with some TTL to delete old inactive topics)
 
#### Who Benefits From The Change(s)?
Developers of services using NATS as integration bus
 
#### Alternative Approaches
I don't know how to get information about topics of published messages using NATS.

**Comment by derekcollison** [comment]
This one can be tricky for sure. The way I go about it would be to place a server into debug and verbose mode and run a test. Use the -DV flag. We have thought about ways to do this dynamically as well on a per connection basis such that a server restart is not needed. We could keep "published to" subjects for the last minute, but not sure that would help since we could get quite a bit of noise distortion based on usage, e.g. think inboxes. I have also thought it might be good to query a system for a subject and ask if there is any interest for that subject. Will keep thinking about it, thanks for bringing this issue up.

**Comment by derekcollison** [comment]
We could also allow a detailed view of the subsz endpoint to include subscriptions and matching connections.

**Comment by maksimenko-stanislav** [comment]
@derekcollison, could you tell me if you have plans to implement this feature in near future?

**Comment by derekcollison** [comment]
The cataloging and reporting of all published subjects? Probably not. But what I think you may want is to know what interest for any given subject exists. Is that correct?

**Comment by Sergey-Terekhin** [comment]
We would like to know all subscribers and publishers of the subject - it will simplify development and resolve integration issues without writing and reading tons of logs.
In the production environment it would be useful to know if 'dead' topics exist (without subscribers and/or publishers) to alert system administrators

**Comment by ripienaar** [comment]
Without publishers or subscribers the topic is deleted. There’s no such thing as a dead topic

I would be curious how having this will help development. You mean as a debug aid or some other way?

**Comment by Sergey-Terekhin** [comment]
> Without publishers or subscribers the topic is deleted
Ok. But if topic has only subscribers or publishers, we never knows about it without logging - we will see that two services are not connected via NATS, but reason will be hidden from us. At the development stage it will be very useful to know anything about internals of NATS cluster (even if performance will degrade)
In the production knowledge about topics without subscribers or publishers can be useful to notify sysadmins about problems in some services (I know, it would be better to have other health-check mechanism, but it can be yet another point of monitoring)

**Comment by derekcollison** [comment]
We have been looking into this and trying to understand what is needed to help developers and operators. I group this into circuit observability. Meaning, if I send to subject "foo", who will receive that message? I am looking at this and other observability patterns to add to NATS.

**Comment by derekcollison** [comment]
Does the group feel strongly that we need the server to track published subjects, or that we just need a server to have an endpoint that says, if I publish to X, who would receive it?

**Comment by Sergey-Terekhin** [comment]
I think endpoint will be enough
The data structure might be following:
```
- <subject>
   - <publishers>
   - <subscribers>
```
And in the UI (if it will be some) mark by red color subjects without any publisher or subscriber

**Comment by Sergey-Terekhin** [comment]
I think, as API-endpoint it will be OK, but as UI - so so. But it will be much more better than nothing )

**Comment by derekcollison** [comment]
This is now in master and will be part of the 1.2 release.
