### ISSUE TITLE
Route behavior in high fan-out

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#659]
Setup: server A has a route to server B.
B has thousands of subscriptions.
When A sends a message to B, B in turn matches all subscriptions and send. This may result in a bit of time spent doing this. While doing so, socket between A and B is not drained. A may continue to send to B. When socket buffer is full, A will disconnect B as a slow consumer.
If all subscriptions were to be on a single server, and each individual send is not blocking for more than the write deadline, everything would work fine.

**Comment by derekcollison** [comment]
As an update I have been digging into this quite heavily. Hope to have something soon.
