### ISSUE TITLE
Authorization documentation ( _INBOX.* permission )

### ISSUE THREAD

**Issue by nuhamind2** [nats-io/gnatsd#662]
When using request API, reply-to is set to, for example **_INBOX.OpIh338NswuirQdUdmrX77.OpIh338NswuirQdUdmrXX9**
Shouldn't the documentation mention permission for _INBOX.> or _INBOX.\*.\*  instead of _INBOX.*?

```Note that _INBOX.* subscribe permissions must be granted in order to use the request APIs in Apcera supported clients. If an unauthorized client publishes or attempts to subscribe to a subject, the action fails and is logged at the server, and an error message is returned to the client.```

**Comment by nuhamind2** [comment]
setting the allowed subscription to _INBOX.* cause authorization violation

`[575] 2018/04/02 14:03:33.405087 [ERR] 10.0.3.1:59018 - cid:4 - Subscription Violation - User "nuha", Subject "_INBOX.w7Xgr1Gjd12sZgsoDrZIvM.*",`

but changing to _INBOX.*.* does not create said error message

**Comment by derekcollison** [comment]
The new request/reply uses multiple tokens so yes we need to update the docs since _INBOX.* will no longer match. _INBOX.> should do the trick. Thanks for the report!
