### ISSUE TITLE
Hard to debug slow consumers

### ISSUE THREAD

**Issue by derekcollison** [nats-io/gnatsd#663]
Want a better way to debug slow consumers, possible send client identifier in INFO message which can then be used for a closure on logs? Maybe do async notifications.

**Comment by ColinSullivan1** [comment]
Imo log is simplest.  One could watch the /varz slow_consumers to bump and check out the the logs when it does.

That being said, another option could be to add to `/connz`.  Something like a `slow_consumers` array with a subject and a count, name is there.  Not great to hold the state, but imo would provide better info for triggering alerts in something like Prometheus.

```text
  "connections": [
    {
      "cid": 2,
      "ip": "::1",
      "port": 58239,
      ...
      "subscriptions": 1,
      "name": "nats-sub",
      "lang": "go",
      "version": "1.3.1",
      "subscriptions_list": [
        "global.alert"
      ]
      "slow_consumers": [
        "global.alert" : 2
      ]
    }
  ]
```

**Comment by derekcollison** [comment]
I have been thinking about it, possibly have a /slowz which can be an array of slow consumer events with time, client id etc.

**Comment by derekcollison** [comment]
Closing this since more info in #520.
