### ISSUE TITLE
Kubernetes headless shuffle connect

### ISSUE THREAD

**Issue by jsenon** [nats-io/gnatsd#672]
- [ ] Defect
 - [x ] Feature Request or Change Proposal
 
## Feature Requests
 
DNS resolution with Kubernetes headless before shuffle in urls

#### Use Case:
 
We have deployed Nats on Kubernetes with [k8s-deployment]( https://github.com/pires/kubernetes-nats-cluster) composed by 3 k8s nodes. Deployment provide headless service: nats.namespace. We use it when we build our application in the url to connect.
Gnatsd normally shuffle on urls to provide random loadbalancing, in our case I think that gnatsd random on nats://nats.namespace url only, and after, made DNS resolution (and with random DNS retrieve IP of a pod nats-0 or nats-1 or nats-2)

#### Proposed Change:
 
Does implementation of DNS resolution before shuffle into urls, is something interesting?

#### Alternative Approaches

Inform client about broker name and change urls to nats://nats-0,nats://nats-1,nats://nats-2

**Comment by wallyqs** [comment]
Closing since it was recently added to the client to lookup a host before connecting: https://github.com/nats-io/go-nats/pull/410
