### ISSUE TITLE
IPv6 only listener

### ISSUE THREAD

**Issue by tomponline** [nats-io/gnatsd#676]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [ ] Included `gnatsd -DV` output
 - [ ] Included a [Minimal, Complete, and Verifiable example] (http://stackoverflow.com/help/mcve)
 
## Feature Requests
 
We have a 2 node GNATS cluster, with clients that connect over the Internet from multiple different data centers. We use IPv6 across all nodes. However the GNATS server seem to be publishing the IPv4 local private address to clients, which then causes them to try and connect over a non-routable private IPv4 address - which doesn't work.

Is there a way to tell NATS either to listen only on the IPv6 stack (but without specifying an individual listen IP for each gnatsd node), or tell it to advertise only IPv6 addresses to clients?

I'm not sure what info the gnatsd servers pass to the clients about the other servers in the cluster.

#### Use Case:
 
Nats Client on external machine
2x Gnatsd servers listening on private IPv4 addresses, and public IPv6 address
Nats client set to connect to Gnatds servers using IPv6 addresses.
Nats client connects to 1 server over IPv6 and then tries to connect to the private IPv4 address.

**Comment by ripienaar** [comment]
You might have luck with various combinations of `--client_advertise`, `--cluster_advertise` and giving a ipv6 address to `--addr`

Can't say I tried it but these settings seem to exist to achieve what you want @tomponline

**Comment by tomponline** [comment]
cheers @ripienaar those look like promising options :)

**Comment by tomponline** [comment]
The "--no_advertise" looks good too https://github.com/nats-io/gnatsd/commit/82dbb3a5ab15ae38caa2db7d2e3c360b9eb21bdc

**Comment by ripienaar** [comment]
@tomponline yeah that will disable it entirely which make sense if you have other ways to configure its urls or your cluster isnt dynamic.  There's a cluster equiv too

**Comment by tomponline** [comment]
@ripienaar yep, we use puppet to deploy all the cluster addresses to clients.

We'll try that and report back here if it works. Thanks.

**Comment by ripienaar** [comment]
@tomponline disabling is good then, I too disable it, it's a mine field with NAT and so forth

**Comment by tomponline** [comment]
This works great thanks!
