### ISSUE TITLE
Unable to remove route with config reload if remote server not running

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#681]
Say you have server A with a route to server B. A connects to B. B is stopped. A's config is changed to remove route to B. A is sent the signal to reload its config. A still continues to try to connect to B.

PS: If B were to be restarted just for a moment (until A connects to B), then it after B is stopped again, A would indeed stop to reconnect to B.

**Comment by derekcollison** [comment]
Do we have a test to demonstrate?

**Comment by kozlovic** [comment]
Not yet. This has been reported on Slack and did a quick manual test and noticed the issue. Will add a test later.

**Comment by ahoneggar** [comment]
I did some looking around. Seems [this for loop](https://github.com/nats-io/gnatsd/blob/5598d5c71162657cc16f244110a9a7d7874a54df/server/route.go#L982) (in connectToRoute() in server/route.go) doesn't check that the route is still in `s.opts.Routes`, so config reloads have no effect. 

As a work around, I tested the following code, with success:
route.go
```
...

// Makes sure that route is still explicitly defined
func hasRoute(routes []*url.URL, route *url.URL) bool {
	for _, r := range routes {
		if r == route {
			return true
		}
	}
	return false
}

...

func (s *Server) connectToRoute(rURL *url.URL, tryForEver bool) {

...

	if !tryForEver {
		if opts.Cluster.ConnectRetries <= 0 {
			return
		}
		attempts++
		if attempts > opts.Cluster.ConnectRetries {
			return
		}
	}
	// Test that route is still explicitly defined
	if !hasRoute(s.opts.Routes, rURL) {
		s.Debugf("Route was manually removed, no further attempts will be made to connect.")
		return
	}
	select {
	case <-s.quitCh:
		return
	case <-time.After(DEFAULT_ROUTE_CONNECT):
		continue
	}
	
...
```
