### ISSUE TITLE
Color syntax on logs

### ISSUE THREAD

**Issue by derekcollison** [nats-io/gnatsd#70]
This should not be present when redirecting to a file.

**Comment by mcuadros** [comment]
+1

**Comment by derekcollison** [comment]
There are some other bugs in the logging stuff, should be fixed today or tomorrow.

**Comment by BinaryTweedDeej** [comment]
The code to check whether STDERR is being redirected doesn't work for me on 64 bit Windows, running either through MinGW or the MS DOS command prompt.

```
C:\Users\A561788\workspace\gnatsd>gnatsd.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x4021cc]

goroutine 1 [running]:
main.configureLogger(0xc082023040, 0xc0820703c0)
        c:/Users/A561788/workspace/gnatsd/gnatsd.go:139 +0x23c
main.main()
        c:/Users/A561788/workspace/gnatsd/gnatsd.go:103 +0xcc3

goroutine 5 [runnable]:
text/template/parse.lexText(0xc082084000, 0x8ac0d8)
        c:/go/src/text/template/parse/lex.go:228 +0x382
text/template/parse.(*lexer).run(0xc082084000)
        c:/go/src/text/template/parse/lex.go:198 +0x64
created by text/template/parse.lex
        c:/go/src/text/template/parse/lex.go:191 +0x1b3

goroutine 6 [runnable]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:19
created by os/signal.init┬À1
        c:/go/src/os/signal/signal_unix.go:27 +0x3c

goroutine 7 [runnable]:
github.com/apcera/gnatsd/server.func┬À007()
        c:/Go/gopath/src/github.com/apcera/gnatsd/server/server.go:148
created by github.com/apcera/gnatsd/server.(*Server).handleSignals
        c:/Go/gopath/src/github.com/apcera/gnatsd/server/server.go:155 +0x163
```

**Comment by derekcollison** [comment]
Thanks will take a look. Is the gnatsd executable also 64bit compiled?

**Comment by derekcollison** [comment]
I will get the next version running properly on windows with 1.5. Stay tuned, sorry for the delay..

**Comment by ColinSullivan1** [comment]
I've been unable to reproduce this problem in a windows 7 64 bit environment - perhaps I'm doing something different.  @BinaryTweedDeej, can you verify your go version and share any build flags you used (if any)?

**Comment by derekcollison** [comment]
Maybe this has been fixed.

**Comment by ColinSullivan1** [comment]
Thanks - I've been meaning to get back to this.  Looks like it was - hat
tip to Matias Lahti.

https://github.com/nats-io/gnatsd/commit/03d14478a23d3d4b3a5558eccd1b195c1c869ac6



On Tue, Dec 8, 2015 at 9:41 AM, Derek Collison <notifications@github.com>
wrote:

> Maybe this has been fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nats-io/gnatsd/issues/70#issuecomment-162940281>.
>



-- 
*Colin Sullivan* | Principal Engineer
colin.sullivan@apcera.com <brian@apcera.com>  | @ColinSullivan01
