### ISSUE TITLE
Feature: Define TTL for queues / messages

### ISSUE THREAD

**Issue by linux-support** [nats-io/gnatsd#713]
- [ ] Defect
 - [X] Feature Request or Change Proposal
 
 
#### Use Case:

When crating a messaging solution with gnatsd as backend system it would be great to be abe to define TTLs on basis of queues and optionally on message level.

The intended messaging solution could handle custom message formats, too. But it is not possible to separate valid massages from the ones with expired TTLs when requesting the queue size. So handling the TTL should be an (optional) feature vof the core system (Gnatsd). 
 
#### Proposed Change:

TTLs should be applied in the following order:

* message based TTL property 
* global definition of max_age
* individual TTL queue property 
 
#### Who Benefits From The Change(s)?

Every project that is interested in the definition of individual TTL settings and the need to the request consistend queue sizes.

#### Alternative Approaches

n.n.

**Comment by ripienaar** [comment]
gnatsd has no concept of persistence, message storage or anything like that.  There are no queue size concept here.

This kind of makes sense in the NATS Streaming project to me?

**Comment by linux-support** [comment]
When it makes sense to move the feature request to the streaming project, this is ok. 
I am missing this core feature in gnats.

**Comment by wallyqs** [comment]
@linux-support as R.I. mentions this feature would not fit very well to how NATS is used, the NATS Streaming though already has `max_age` and `max_inactivity` for messages and queues: https://github.com/nats-io/nats-streaming-server#configuration-file

**Comment by kozlovic** [comment]
Closing this. Check #175 for details.
