### ISSUE TITLE
Feature: Define maximum message size per queue / subject

### ISSUE THREAD

**Issue by linux-support** [nats-io/gnatsd#714]
- [ ] Defect
 - [X] Feature Request or Change Proposal
 
 
#### Use Case:

When crating a messaging solution with gnatsd as backend system it would be great to be abe to define individual max. message sizes based on queues / subjects.

#### Proposed Change:

Add a configuration setting to subjects / queues to provide an additional information for the max. message size. Additionally add a global configuration item similar to --max_bytes in the streaming server.

If this feature request is considered to be implemented into the core system (gnatsd), the individual limitation of the max. message count for subjects and queues would be helpful, too.

 
#### Who Benefits From The Change(s)?

Every project that is interested in the definition of individual message size settings based on subject / queues.

#### Alternative Approaches

n.n.

**Comment by ripienaar** [comment]
Isn't this the existing `max_payload` setting? Given there is no concept of queues or message persistence its not a per queue size you could mean, the only thing is a message

**Comment by linux-support** [comment]
When it makes sense to move the feature request to the streaming project, this is ok. 
I am missing this core feature in gnats.

**Comment by kozlovic** [comment]
Closing this. Check #175 for more details. You may be looking at NATS Streaming instead.
