### ISSUE TITLE
Some config values cannot start with a number unless quoted

### ISSUE THREAD

**Issue by alexplischke** [nats-io/gnatsd#716]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 
gnatsd is unable to parse the config when certain values start with a number (unless it's quoted). In this example, the cluster password starts with a number and gnatsd fails to start. If the password value is quoted, the example will run just fine. Same is true for the username. Other fields may be affected as well. Not critical, but a little surprising.
 
#### Versions of `gnatsd` and affected client libraries used:
gnatsd: 1.1.0

#### OS/Container environment:
Mac OSX 10.13.5

#### Steps or code to reproduce the issue:
Start gnatsd with the following config:
```
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

# Authorization for client connections

# Logging options
debug: false
trace: false
logtime: false

# Pid file
pid_file: "/tmp/gnatsd.pid"

# Some system overides


# Clustering definition
cluster {
  listen: 0.0.0.0:6222

  # Authorization for cluster connections
  authorization {
    user: nats_cluster
    password: 2Tybceg8yj
    timeout:  1
  }

  # Routes are actively solicited and connected to from this server.
  # Other servers can connect to us if they supply the correct credentials
  # in their routes definitions from above
  routes = [
    nats://nats_cluster:2Tybceg8yj@nats-nats-cluster:6222
  ]
}
``` 
#### Expected result:
 NATS starts successfully.

#### Actual result:
```
./gnatsd -DV -c gnatsd.conf
Parse error on line 24: 'Expected a map value terminator "," or a map terminator "}", but got 'T' instead.'
```

**Comment by aricart** [comment]
The workaround is to enclose such values with a string. The configuration parser interprets values starting with a number as a number. Or as best practice write all string values enclosed in quotes.

`password: "2Tybceg8yj"`
