### ISSUE TITLE
Slow message throughput compared to TCP server

### ISSUE THREAD

**Issue by swdee** [nats-io/gnatsd#718]
## Issue

During our testing of NATS we found the message throughput to be slower than expected compared to messages received by a simple TCP server.  Whilst we would expect some overhead due to the functionality that NATS is providing we are only achieving around 1.8k messages per second through NATS.  When the same sized 32 byte messages are sent direct to a TCP server the throughput is around 9k/sec on the same hardware.

### Software
gnatsd: 1.2.0-beta4
golang: go1.10.1 linux/amd64

## Method

With reference to our test Producer and Worker programs here; https://github.com/swdee/natsbench

### Test 1

We configure three Linode 2048 instances in the same datacenter with each program running on its own instance, producing a message flow of;

Producer -> NATS -> Worker

The Producer and Worker start up HTTP /metrics endpoints that are scraped by Prometheus and a Grafana dashboard is used to monitor the message through put of Producer and Worker.

The NATS server is started with
```
./gnatsd
```

Worker is started with
```
./worker2 -n nats://<nats-server-ip>:4222
```

The Producer is started and sends 10k msgs/sec at 32 byte size using
```
./producer2 -d nats://<nats-server-ip>:4222 -r 10000
```

### Test 2

Using the same Linode instances we change the topology and replace NATS with HAproxy to flow through with the Worker acting as a simple TCP server to receive the messages directly.

Producer -> HAProxy -> Worker

Worker is started and listens on port 8095
```
./worker2 -s :8095
```

The Producer is started with same 10k msgs/sec rate at 32 byte size
```
./producer2 -d worker://<haproxy-server-ip>:8095 -r 10000
```

## Result

The attached graph shows throughput of Test 1 sending and receiving around 1.8k msg/sec when using NATS.

![nats-thruput-graph](https://user-images.githubusercontent.com/8000937/43773639-77f47a22-9a9a-11e8-81e7-80d84d1261c3.png)

Test 2 on the other hand achieves ~9k msg/sec

We did not expect NATS to have a throughput rate of approximately 20% of that when sending to a simple TCP server.  Is there some error we have made in the Producer/Worker code that explains the poor performance with NATS?

**Comment by kozlovic** [comment]
You need to remove this [line](https://github.com/swdee/natsbench/blob/master/pkg/producer/producer.go#L105). Calling `Conn.Flush()` causes the library to send a `PING` protocol to the server and synchronously wait for a `PONG` response from the server. I assume that your intent was to flush the underlying buffer, but this is way more than that.

The library automatically flushes the buffer that is used to improve throughput. You don't need to call any API. You *could* call `Flush()` before a connection Close() if you were to measure the publish rate for instance in a for loop performing Publish() calls and then measuring the before/after. Then yes, I would do a Flush() after the last message is sent to make sure that all messages have been received by the server. This is what we do in our bench program [here](https://github.com/nats-io/go-nats/blob/master/examples/nats-bench.go#L130).

**Comment by kozlovic** [comment]
Also a note on your workers. It seem that you have a mode "shard" where you create subscriptions on a unique subject such as `txn.a.>`, `txn.b.>`, etc.. and in that mode then send randomly to those subjects.

If the intent is to distribute the load, then you should really look at queue subscription using `QueueSubscribe()` (https://github.com/nats-io/go-nats#queue-groups). You would use a single subject and group name, and in that mode, all members of the same group share the load. That is, if they subscribe on `foo` on group `bar`, then a message published on `foo` is given to only one of the member of that group. The distribution is random and is done by the server.

**Comment by swdee** [comment]
Thanks for taking a look, I did assume Conn.Flush() was just flushing the underlying buffer.  With that removed performance is now comparable in the 9k msg/sec mark. 

![nats-thruput-noflush](https://user-images.githubusercontent.com/8000937/43801729-0424dfd0-9ae8-11e8-8b4f-33395fad9847.png)

**Comment by kozlovic** [comment]
Glad to know. Can we close the issue or do you have more questions?

**Comment by swdee** [comment]
Issue can be closed thanks.
