### ISSUE TITLE
Server documentation is sparse

### ISSUE THREAD

**Issue by thedrow** [nats-io/gnatsd#74]
There's no troubleshooting section and no clustering tutorials.

**Comment by franklinwise** [comment]
The performance numbers on [bravenewgeek.com](http://www.bravenewgeek.com/tag/nsq/) look awesome.  Really interested in using the platform, however, some basics on how clustering works and some key points about running the servers in production would be really helpful.

**Comment by franklinwise** [comment]
This [slide share](http://www.slideshare.net/derekcollison/nats-a-new-nervous-system-for-distributed-cloud-platforms) is a helpful start

**Comment by yonah-codefresh** [comment]
+1

**Comment by bjflanne** [comment]
Hi all,

I am on the Apcera team, and would value your input on what sort of documentation would be useful to you. Would also be interested to learning more about what/how you are using NATS for. Can you drop me a brief email on both to brian at apcera dot com?

Cheers

Brian

**Comment by mackross** [comment]
@bjflanne The config could do with a full explanation for each parameter. There is also not a lot of information around clustering unless you read through the groups list. It would also be nice to see some pub/sub resources -- perhaps some typical problems you solve at apcera using gnats. How do you build robust distributed systems with at-most-once delivery?

**Comment by bjflanne** [comment]
@mackross Thanks for your feedback on what might be more helpful. This is much appreciated. What does your architecture look like? (what sort of systems do you have, what do they do, and what are you trying to accomplish with distributed messaging etc.?). If you can provide me some more details would be great to understand that and discuss best practices and where NATS might be able to help. If you prefer to drop me that via email rather than here it's brian@apcera.com -- thanks again for the suggestions on documents this is helpful.

**Comment by bjflanne** [comment]
@franklinwise thanks for posting the slide share. These slides accompanied a presentation at SCALE 13x by our founder (@derekcollison): https://www.youtube.com/watch?v=5GcAgMPECxE

Great for understanding why NATS was created, where it excels, what the inherent design principles are, why it is different to other messaging systems, and all that good stuff. That being said, if you have questions or comments/feedback about it would love to hear it.

**Comment by franklinwise** [comment]
@bjflanne - glad to help. I'm focused on some other projects currently, however, I will swing back around to NATS probably in a month.

**Comment by derekcollison** [comment]
I am working on NATS all this week, and agree docs are not where they need to be. Will be working on them. Thanks.

**Comment by mcqueary** [comment]
@thedrow @franklinwise @yonah-codefresh @mackross - hi there! This past Friday we released our open source website on [nats.io](http://nats.io). Lots of documentation has been added at [nats.io/documentation](http://nats.io/documentation).

The documentation has its own separate [repo on GitHub](http://github.com/nats-io/nats-docs/). Please feel free to contribute or raise any doc issues there. Thanks!
