### ISSUE TITLE
Server doesn't start with bcrypt passwords in routes section

### ISSUE THREAD

**Issue by tompizmor** [nats-io/gnatsd#750]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
#### Versions of `gnatsd` and affected client libraries used:

```
$ gnatsd -DV
[33] 2018/09/13 14:34:20.615593 [INF] Starting nats-server version 1.3.0
[33] 2018/09/13 14:34:20.615659 [DBG] Go build version go1.11
```

#### Steps or code to reproduce the issue:
 Create a NATS cluster and configure the routes section inside the cluster section with bcrypted passwords. For example:

```
cluster {

  listen: localhost:4244 # host/port for inbound route connections

  # Authorization for route connections
  authorization {
    user: route_user
    # ./util/mkpasswd -p T0pS3cr3tT00!
    password: $2a$11$xH8dkGrty1cBNtZjhPeWJewu/YPbSU.rXJWmS6SFilOBXzmZoMk9m
    timeout: 0.5
  }

  # Routes are actively solicited and connected to from this server.
  # Other servers can connect to us if they supply the correct credentials
  # in their routes definitions from above.

  routes = [
    nats-route://user1:$2a$11$xH8dkGrty1cBNtZjhPeWJewu/YPbSU.rXJWmS6SFilOBXzmZoMk9m@127.0.0.1:4245
    nats-route://user2:$2a$11$xH8dkGrty1cBNtZjhPeWJewu/YPbSU.rXJWmS6SFilOBXzmZoMk9m@127.0.0.1:4246
  ]
}
```

#### Expected result:

The gnatsd server starts successfully. 

#### Actual result:

Gnatsd server does not start properly and it logs error like this:

```
2018/08/31 03:35:14.616494 [ERR] Error trying to connect to route: dial tcp: address tcp/$2a$10$pu3tmi8HDmqqBF5OJftln.Q5cdft9HI: unknown port
2018/08/31 03:35:15.616674 [ERR] Error trying to connect to route: dial tcp: address tcp/$2a$10$pu3tmi8HDmqqBF5OJftln.Q5cdft9HI: unknown port
2018/08/31 03:35:16.617854 [ERR] Error trying to connect to route: dial tcp: address tcp/$2a$10$pu3tmi8HDmqqBF5OJftln.Q5cdft9HI: unknown port
2018/08/31 03:35:17.619660 [ERR] Error trying to connect to route: dial tcp: address tcp/$2a$10$pu3tmi8HDmqqBF5OJftln.Q5cdft9HI: unknown port
2018/08/31 03:35:18.621928 [ERR] Error trying to connect to route: dial tcp: address tcp/$2a$10$pu3tmi8HDmqqBF5OJftln.Q5cdft9HI: unknown port
```

**Comment by aricart** [comment]
On nats urls, the password is the actual password. In the case above the password used is the encoded (armored) version of the password which will never match the password. 

Effectively, the route configuration cannot really have an encrypted password for routes, because the same configuration that specifies the encoded password must use it.

**Comment by derekcollison** [comment]
Bcrypt does not work that way, it allows the recipient to not store a plaintext password and to attach a 'cost' to checking if a password is correct. In the section you are referencing that is where your server is acting like a client to the remote server, so it needs to be the actual password. I don't like plaintext passwords in config files at all, so you could assign it to a variable or we will introduce nkey support soon.

**Comment by aricart** [comment]
The solicited route URL cannot embed an encrypted credential in the url. You have to provide the clear text credential. The cluster authorization user credential for the current server is encrypted and will be honored. The only way to not embed the clear text version of the credential is to provide it as an argument as a command line when you start the server. You'll have to be careful or that credential can be leaked as well.

**Comment by tompizmor** [comment]
I see! Thanks for the response. The problem passing the password as an argument is that it can be seen with a `ps` command.

**Comment by derekcollison** [comment]
The password can be an environment variable that is de-referenced inside the config file.

**Comment by gabrieltnishimura** [comment]
Thank you very much!
Solved the route in plain-text problem by creating a environment variable like so:

`export ROUTE1=[nats-route://nats-cluster:password@127.0.0.1:4222]` 

With the config file as below:

```
cluster {       # cluster configuration
  listen: localhost:6223
  routes = $ROUTE1
}
```

Running the server only with the config file:

`gnatsd -c cluster1-nats.conf`

**Comment by derekcollison** [comment]
Great!
