### ISSUE TITLE
Introduce a grace period for resubscriptions after server start

### ISSUE THREAD

**Issue by Imaskar** [nats-io/gnatsd#754]
- [X] Feature Request or Change Proposal

#### Use Case: 
When some producers continuously publish messages and server goes down, they keep messages in their buffers. As soon as server goes up, clients reconnect and producers flush their buffers. But the order of reconnects is not determined. So consumers may reconnect and resubscribe later than producers flush their buffers.
 
#### Proposed Change:
Introduce a server parameter that would specify time to wait for resubscriptions before starting to send out messages.
 
#### Who Benefits From The Change(s)?
Ones who wish to loose as few messages as possible in the case of server crash/restart, but do not wish to spend additional resources for nats-streaming.

#### Alternative Approaches
Tell those to use nats-streaming.

**Comment by ripienaar** [comment]
If you care for this kind of thing you should use nats-streaming.  

gnatsd cannot make a promise like this - it does not keep messages in memory to defer sending later, it's not a kind of middleware that has buffering and things like that.

**Comment by Imaskar** [comment]
What about not buffering, but blocking on publish?
I don't suggest to introduce any guarantees, just improve QoS.

**Comment by derekcollison** [comment]
I am very interested in making NATS systems as resilient as possible when clients do the right thing but there are changes or interruptions in the NATS fabric itself. Continuing to research some ideas so nothing definitive yet.

**Comment by derekcollison** [comment]
We have introduced lame duck mode for the server which controls how clients are disconnected over a given period of time. Still looking into some issues here but will close for now. Feel free to open back up if needed.
