### ISSUE TITLE
embed nats server in own app

### ISSUE THREAD

**Issue by vtolstov** [nats-io/gnatsd#758]
I have grpc app (golang) that provide auth and some services to end users (human and robot).
I want to use nats as pub/sub inside my app. But i don't want to expose it port to end users and systems.
So basically i want to catch pub/sub requests via grpc (already have queue service for this) and after auth stream responses to clients.Main question - as i understand to operate gnatsd need to connect to other servers in case of cluster mode via plain tcp. How to not expose it open port to all the world and place behind own grpc app?

**Comment by derekcollison** [comment]
So are all pub/subs for NATS inside your single app?

**Comment by derekcollison** [comment]
If say the server with gRPC and NATS where gRPC is exposed to outside world, have NATS on loopback, 127.0.0.1 for that machine and then have it cluster to another server.

**Comment by vtolstov** [comment]
Thanks,but nats cluster need external addresses of other servers, that behind  grpc

**Comment by derekcollison** [comment]
Connections between clusters can be initiated by either side, and do not have to be symmetric. So the server that listens for client connections and route connections can all be loopback, but it will be configured to connect back to server B on its non-loopback addr:port.

**Comment by vtolstov** [comment]
@derekcollison thanks, but how server B knows does it need to accept conn or reject? So my questions is - if i have untrusted env (non local area network) how can i check incoming conn and accept/reject it ?
In my grpc app i simple check oauth2 token

**Comment by derekcollison** [comment]
Route connections between servers can use TLS with certs and/or username/password combinations, so server B can be configured only to accept a connection from Server A.

**Comment by vtolstov** [comment]
@derekcollison ok, but if someone reverse engine my app malicious user can get user/pass or tls certs.
So as i understand i need to wait external auth?

**Comment by vtolstov** [comment]
And as i understand i can't work with server without send/recv data via tcp? Do you plan to add methods to direct send/recv messages from server without tcp loopback workaround?

**Comment by vtolstov** [comment]
Oh, i see that i can use custom client auth and custom router auth. So i can use my token for auth, and check it via my app. Can you provide comments for Options struct?
For my use-case and loopback server i need to host and port for local addr, and pass external add for route connections? How can another server knows that it also needs for route to bind to external address?

**Comment by derekcollison** [comment]
Yes you can use the custom auth if needed. Are you concerned that the app with both gRPC and NATS will be compromised? You could have that app simply be a NATS client to a remote server instead of embedding the server as well. In terms of disguising auth in the app in case of a compromise there are several Google results that could help. However, if the NATS user connects remotely to another server and that server has well defined permissions on what subjects it can publish and subscribe to it can limit any exposure IMO.

**Comment by vtolstov** [comment]
In my case each remote app (client) subscribe to some topics and push back to another topic updated/depended tasks. So  each app need read/write perms on many topics... Also some app works as event proxy. It receives events for own segment and translate to local area clients.

**Comment by vtolstov** [comment]
my use-case:
```
                               cc01                      (central server with grpc+rest api)            cc02
                                                            /                                                     \
                                                          /                                                        \
                                                cc01.z1                                                   cc02.z1
                                                    | |
                                node01 node02 node03

```

So i have main grpc+rest api server what manages queue, for each managed zone it pushes to corresponding topic tasks for specific zone. cc01.z1/cc02.z1 managed per zone tasks that pulled from main grpc+rest server. After that each zone cc server push needed task to topics of it zone.
Also i'm read about delivery of messages and check etcd for my use-case. Can you also share benefits of using nats vs etcd for message queue?

**Comment by derekcollison** [comment]
Have not used etcd myself too much. Lots of complexity that I don't think you need. 

So in your diagram you would want a NATS client also inside the central server and have that publish and subscribe NATS messages as needed? Or do you require an embedded NATS server to avoid tromboning to a remote server when not needed?

**Comment by vtolstov** [comment]
yes, in central server i'm also need nats client (i'm happy if nats server have ability to inject messages without tcp overhead in my case and client usage, but...) to publish and subscribe (grpc app have method to subscribe that stream messages to grpc clients)

**Comment by derekcollison** [comment]
The overhead of the connection should not be too bad. Not sure its worth it to do a single Go client for embedded server use, but others have asked as well, but usually they do not have a performance issue.

**Comment by derekcollison** [comment]
So the embedded server would not have any client connections via tcp/ip, only a route connection to another NATS server, correct?

**Comment by derekcollison** [comment]
Have you looked at STAN (NATS Streaming)? Not sure if we have LevelDB store plugin though.

**Comment by derekcollison** [comment]
We have considered a Go client with direct connect to an embedded server but currently have no plans. Will close this for now but feel free to open back up if needed.
