### ISSUE TITLE
Password obfuscation in trace does not work properly

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#762]
If username and password are the same, or simply if the password text is present in the trace before actual location of the password, that string would be replaced.
For instance, trying to connect with URL `nats://ivan:ivan@localhost:4222` would produce this trace:
```
[TRC] ::1:49797 - cid:1 - ->> [CONNECT {"verbose":false,"pedantic":false,"user":"[REDACTED]","pass":"ivan","tls_required":false,"name":"","lang":"go","version":"1.6.1","pr
```

**Comment by kozlovic** [comment]
Moreover, this prevents actual connection since it seem that the code doing obfuscation is altering the incoming CONNET protocol!

**Comment by derekcollison** [comment]
Wally can you take a look at this for me?

**Comment by derekcollison** [comment]
This will not be an issue with nkeys.. Just wanted to not have passwords in the logs for plaintext.
