### ISSUE TITLE
User with no account unable to receive messages from account exporting a stream

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#763]
Suppose we have the following configuration:
```
authorization {
    users [
        {user: ivan, password: bar}
     ]
}
accounts {
    synadia {
        users [{user: derek, password: foo}]
        exports = [
             {stream: "foo.*"}
        ]
    }
}
```
If you start a subscription on `foo.bar` for user `ivan` and `derek` publishes a message on `foo.bar`, that message is not received.

**Comment by derekcollison** [comment]
But if you define the import on $G, then why not just define ivan under there too? Then why would it need to be $G?

**Comment by kozlovic** [comment]
The original issue is to specify what happens when you have a mix of users defined in accounts and not. If `export` with no specified account says "it's public", we should make it clear that users not part of an account cannot receive those messages. Again, not saying that there is a bug but we need to specify the behavior.

**Comment by kozlovic** [comment]
Closing this since it works as expected. Users without account should not be able to receive. You need to specify an import. Will just need to document that.
