### ISSUE TITLE
Dev: shadow sub not removed when original sub is

### ISSUE THREAD

**Issue by kozlovic** [nats-io/gnatsd#772]
Suppose there is 2 accounts, A that exports foo and B that imports foo.
If a client from B creates a subscription on foo, the server will create a shadow subscription in account A to allow messages published on A's foo to be routed to B's foo.
However, when B's foo subscription is removed, that shadow subscription is not.

**Comment by derekcollison** [comment]
You mean when B's subscription is unsubscribed the shadow subscription in A is not removed, correct?

**Comment by kozlovic** [comment]
Correct, I edited the initial comment.
