### ISSUE TITLE
Nats cluster unable to handle high messaging throughput 

### ISSUE THREAD

**Issue by boristunity** [nats-io/gnatsd#773]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
 `gnatsd -DV` output:  
~~~
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [45B blob data]
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [21B blob data]
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [248B blob data]
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [66B blob data]
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [182B blob data]
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [36B blob data]
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [10B blob data]
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [169B blob data]
Oct 07 15:29:27 tu-nats-group-p-p3lq gnatsd[23441]: [23441] 2018/10/07 15:29:27.098021 [TRC] 1
~~~  
 
#### Versions of `gnatsd` and affected client libraries used:
1.0.4

#### OS/Container environment:
Ubuntu 16.04

#### Steps or code to reproduce the issue:
 We are using a base cluster of 5 nodes, which receives 11.4 MB/1 Sec (950 messages of 12kb each), with 190 topics,  and we have minimum of 12 clients- each client subscribes to all 190 topics.

Once we add more than 100 clients, the amount of messages that NATS receives decreases, and after scaling up the cluster to 15 nodes, the received messages by NATS is still low.. 
We have tried gradually adding clients, but still the amount of received messages is decreased.
We expect the NATS cluster to be able to handle that throughput, and cant decide if we have reached the limit of NATS or if it's something else. 
 
Attached is our graphs with the above behavior,
Once adding more clients the amount of messages received decreased:
![screen shot 2018-10-07 at 18 40 03](https://user-images.githubusercontent.com/20415463/46583525-6af6d580-ca61-11e8-8a3f-0de377bed4b4.png)

**Comment by derekcollison** [comment]
Thanks for the information. Its it possible to describe where the publishers and clients were connected, to which servers, and what the fanout was for the baseline message rate above?

Also it might be good to run this test with the latest released server to see if there are improvements.

When the new connections were introduced, did they also publish and subscribe? Where there any interactions between the baseline publishers and subscribers?

And last question, were any queue subscribers involved?

Thanks.

**Comment by kozlovic** [comment]
To add to this, if you add more subscriptions (to those same topics) and there is no queue involved, the server has to send more. Say if there is 10 subs on "foo", for a given published message the server has to send it 10 times. If you add 10 more subs, then now it has to send 20 times. What I find interesting is that prior to add more clients, the bytes IN is close to 3.7G and bytes OUT is close to 10GB (difficult to say with the picture) and when you add more clients, the IN drops to 1.9G and OUT to  37G, so it looks like some network saturation, and makes me think that you just added more subscriptions (no queues) which just increase the fanout.

**Comment by boristunity** [comment]
@derekcollison 
The amount of publishers is the same, and never changes- 4 publishers.
The amount of subscribers is changing- the above graphs show what happens when we scale up large amount of subscribers,
No queues at all- its live streaming, and any lost message is being ignored.


----



@kozlovic 
Well that's what I'm experiencing, and trying to understand if that behaviour is expected in NATS or not, 
Because I though NATS should be able to handle this kind of traffic and load.
I dont think that I have network saturation- the whole setup is running inside GCP.

**Comment by derekcollison** [comment]
Any additional information on whether or not this was saturating the network?

**Comment by boristunity** [comment]
@derekcollison The graphs were false positive, the in messages are ok, the nodes just rebalanced the clients between them- and the messages they were sending to each other (the cluster nodes) were also rebalanced,

We are still trying to understand why we are experiencing the messages drops on the clients.

This issue can be closed until we figure out the real issue

**Comment by derekcollison** [comment]
Thank you for the feedback. Please feel free to re-open as new information surfaces. And let us know if we can help debugging the issues. I believe network saturation played a role.
