### ISSUE TITLE
Parsing The Config to JSON

### ISSUE THREAD

**Issue by eymkey2** [nats-io/gnatsd#807]
Hi, I would like to change the config of my nats-servers dynamically through a nodejs backend. To do that I need to parse the config to something like JSON and vice versa. How can I do this?

Sincerely, Emre

**Comment by eymkey2** [comment]
Hi Derek,
thanks for your reply and sorry for my dumb questions, but I didn't get it. If I put JSON in the config file the parser throws an error.

config.json:
{
    "net": "127.0.0.1",
    "port": "1000"
}

gnatsd -c config.json -> output:
panic: interface conversion: interface {} is string, not int64

goroutine 1 [running]:
github.com/nats-io/gnatsd/server.(*Options).ProcessConfigFile(0xc000083680, 0xc000058090, 0x9, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nats-io/gnatsd/server/opts.go:227 +0x1d0e
github.com/nats-io/gnatsd/server.ConfigureOptions(0xc00008c240, 0xc0000540d0, 0x2, 0x3, 0x864a40, 0x864cb0, 0x864a48, 0xc00009f950, 0x0, 0x0)
        /home/travis/gopath/src/github.com/nats-io/gnatsd/server/opts.go:1158 +0x13c4
main.main()
        /home/travis/gopath/src/github.com/nats-io/gnatsd/main.go:84 +0xd7

**Comment by kozlovic** [comment]
Why do you put value of port between double-quotes? this is supposed to be an int, not a string.

**Comment by derekcollison** [comment]
We can make the parser not panic if you don't give us a number (int) for port.

**Comment by eymkey2** [comment]
thank you really much guys, these little tips helped me a lot.
I tried it know with a more complex config file and it did work.
Have a nice weekend.

best regards, emre

**Comment by derekcollison** [comment]
Great! Have a nice weekend as well.
