### ISSUE TITLE
Error occurs if queue name contains white space

### ISSUE THREAD

**Issue by nguyendangminh** [nats-io/gnatsd#84]
Hi,
If the queue name contains white space, e.g. "job worker", the gnatsd will return an error "processSub Parse Error". There's nowhere in the document mentions queue name.
```go
...
nc.QueueSubscribe("foo", "job worker", func(msg *nats.Msg) {
        log.Printf("Received on [%s]: '%s'\n", msg.Subject, string(msg.Data))
    })
...
```

**Comment by derekcollison** [comment]
Yes we can be better at that for sure, queue names cannot contain spaces.

**Comment by stevenvegt** [comment]
Hi, I just spend a few hours of debugging this problem. I had a `subject` with a space in it.
The subscribe did not error, but the events did not arrive either. 

It's obviously a newby mistake 👋 but some kind of hint for me it would have been a huge timesaver. Maybe you can add a check when the debug option flag is set?

**Comment by derekcollison** [comment]
The server can be put into pedantic mode where it does more checking on the subjects. However we do have a few newcomers run into this issue.

**Comment by derekcollison** [comment]
Which client were you using?

**Comment by stevenvegt** [comment]
Thanks for the quick response! I'm using the streaming stan.go client.

**Comment by derekcollison** [comment]
Will look to add some processing to those clients.
