### ISSUE TITLE
Docker go get will need an additional flag for 1.4x+

### ISSUE THREAD

**Issue by composer22** [nats-io/gnatsd#85]
If you are planning to upgrade the docker build script to utilize 1.4x golang compiles, you will most likely need to add an additional flag to the go get command:

from 

RUN CGO_ENABLED=0 go get -a -ldflags '-s' github.com/apcera/gnatsd

to

RUN CGO_ENABLED=0 go get -a -ldflags '-s' **--installsuffix cgo** github.com/apcera/gnatsd

Although I didn't test this with your code, I did use your build scripts for my own model. I found issues with both FROM scratch and FROM busybox images. Binaries would not launch and docker would report back "file or directory" missing etc.

This is noted as a workaround:

https://github.com/golang/go/issues/9344

See context in golang build:

http://golang.org/pkg/go/build/#Context

and is implemented in this script:

https://github.com/CenturyLinkLabs/golang-builder

which implements everything as published in this article:

http://blog.xebia.com/2014/07/04/create-the-smallest-possible-docker-container/

**Comment by derekcollison** [comment]
Thanks I saw that as well earlier on. Will do an upgrade to Docker image this week so will address then.

**Comment by derekcollison** [comment]
Fixed in latest.
