### ISSUE TITLE
Is it OK to send SUB with same topic twice?

### ISSUE THREAD

**Issue by Sergey-Terekhin** [nats-io/gnatsd#859]
Hi!
Is it OK to send SUB message with same topic from one connection? Will NATS ignore second subscription request (expected)? Or should I manually avoid such collisions in the client?

**Comment by derekcollison** [comment]
A server will ignore subscriptions with the same SID (Subscription ID) which is a simple closure that the server tracks for subscription interest. The clients use the SIDs to route traffic locally in their application to the correct callback/function etc.

**Comment by Sergey-Terekhin** [comment]
Thanks :)

**Comment by intech** [comment]
@derekcollison I would like to bring this up again.
Now, when we are working with regular pub/sub with non-guaranteed delivery (without stan or jetstream), we are receiving broadcasts not by clients (tcp socket), but by subscriptions within sid.

**Problem №1.** All sid control is entirely in the client library, which can lead duplicate subscriptions to the same subject. Then nats starts sending 2 messages for each subscription, while on the server we see that there is only one client id and has 2 identical subscriptions with different sid.
It can be controlled on client without following the same topics. Below I will explain why this is bad - doing this on client.

**Problem №2.** With the wildcard subscriptions `a.*.c` and `a.b.*` we will receive `a.b.c` messages 2 times. It is impossible to control this on the client, messages will still come and occupy the network. On the server, wildcard intersection is not difficult to define and deduplicate by every client.

**Problem №3.** Potential DoS-attack. The client can emulate many identical subscriptions (within the limit) with the largest data packets over ws and create many different ws connections, thus the channel will be filled with illegal traffic that nats will try to send.

**Comment by derekcollison** [comment]
Agree with you, but alternative is to have every client support full blown routing and sublist functionality which is non-trivial at best and a decision I made over 10yrs ago not to force the clients to deal with.

**Comment by derekcollison** [comment]
I am open to suggestions, and again understand the issues, but asking all 46+ clients now to support full blown sublist matching and functionality to avoid duplicate delivery for the last mile to a client feels to burdensome. Of course from server to server in all topologies the messages are only sent once.

**Comment by intech** [comment]
@derekcollison thanks for the quick reply, appreciate it!
Could we change this behavior by adding a options or header for deduplication in subscriptions? Similar to mutex

**Comment by derekcollison** [comment]
It could theoretically be possible for the server to only send a message once to a client, however, which SID should it select? How can I client realize why one callback fired but not another that should have matched?

Do you really not want the message processed by different callbacks/subs? Is the message large and you're worried about bandwidth across the last mile?

**Comment by intech** [comment]
> It could theoretically be possible for the server to only send a message once to a client, however, which SID should it select? How can I client realize why one callback fired but not another that should have matched?
> 
Do not take into account sid at all, only subject.  Define subjects per client, and deduplicate per client, including wildcard intersection.

> Do you really not want the message processed by different callbacks/subs? Is the message large and you're worried about bandwidth across the last mile?
> 
I have both of these cases.  We often change subjects of subscription in real time from one to another - this is the trading terminal.  I am worried that in the event of any error on the client, the developers will have a duplicate message problem and we will overflow the channel.

**Comment by derekcollison** [comment]
That was my point, a subject routing system that we have in the servers is non-trivial and not something I wanted to require clients to have to write. Simple cases are easy, but wildcards etc and maintaining that state on client side properly was more then I wanted to burden client writers with.

My suggestion would be tag all source messages with UUID's and de-duplicate as needed for your application.

**Comment by intech** [comment]
Any custom deduplication solution is an implementation of double data processing on the server, which requires additional costs.
On the client, as I wrote earlier, this cannot be solved, ws packages will load cpu regardless of the client's implementation.

**Comment by derekcollison** [comment]
You will burn quite a bit more cpu per message with a subject routing architecture vs hash map lookup of a simple sid, especially as in most clients that is a uint64.

The subject distributor in the server is a modified Patricia tree with a shared cache and a per Go routine fast cache that uses generation uint64s using atomics to invalidate.
