### ISSUE TITLE
Is this a bug? fasthttp/websocket doesnt work with nats.io

### ISSUE THREAD

**Issue by hiqbn** [nats-io/gnatsd#867]
fasthttp/websocket doesnt work with nats.io

my code is here:
https://pastebin.com/raw/hURatUqs

failed at 

         conn.WriteMessage(websocket.TextMessage []byte(s))

i would like the msg.Data to replace "s"

if will work if i comment 

               nc.Subscribe(subj, func(

so i don't understand why they cant work together

===================

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x75e3b2]

goroutine 61 [running]:
github.com/valyala/fasthttp.(*hijackConn).SetWriteDeadline(0xc007ef0a00, 0x0, 0x0, 0x0, 0xc0000aa000, 0x203001)
        <autogenerated>:1 +0x32
github.com/fasthttp/websocket.(*Conn).write(0xc0067dc420, 0x1, 0x0, 0x0, 0x0, 0xc007efa90c, 0x3, 0x402, 0xc0075156b1, 0x0, ...)
        /go/src/github.com/fasthttp/websocket/conn.go:376 +0xfb
github.com/fasthttp/websocket.(*messageWriter).flushFrame(0xc00680fec8, 0xc007515601, 0xc0075156b1, 0x0, 0x7, 0x8, 0xc0075156b0)
        /go/src/github.com/fasthttp/websocket/conn.go:601 +0x23d
github.com/fasthttp/websocket.(*Conn).WriteMessage(0xc0067dc420, 0x1, 0xc0075156b0, 0x1, 0x8, 0x8, 0x0)
        /go/src/github.com/fasthttp/websocket/conn.go:753 +0x24b
main.requestHandler.func1.1(0xc007f2c000)
        /usr/local/src/programs/r/r.go:496 +0xd1
github.com/nats-io/go-nats.(*Conn).waitForMsgs(0xc007f04000, 0xc0044003c0)
        /go/src/github.com/nats-io/go-nats/nats.go:2024 +0x258
created by github.com/nats-io/go-nats.(*Conn).subscribe
        /go/src/github.com/nats-io/go-nats/nats.go:2789 +0x460

**Comment by kozlovic** [comment]
Not sure what you are trying to do since NATS Server does not natively supports websockets. Anyway, this error appears to be in the `valyala/fasthttp` code, so will be difficult for us to help.
But it looks like you use the `conn` websocket connection in the NATS message callback which is invoked from a different go-routine. So it is possible that `conn` is no longer valid when `upgrader.Upgrade()` returns.
