### ISSUE TITLE
tls connection client options and gossiped servers

### ISSUE THREAD

**Issue by aricart** [nats-io/gnatsd#868]
- [x] Feature Request or Change Proposal
 
## Defects 

Currently (some?) clients require a `tls` option to be set in a connection order to enforce whether a server connection should be requiring TLS or not. This however doesn't scale, because regardless of cluster correctness, it is possible to have a cluster where some members require a TLS connection while others don't.

The main issue is that gossiped hostports for other cluster members don't provide a protocol, so some of the clients have to sanitize the received hostports into urls, and add a `nats://` or `tls://`.

The requirement for a client to only connect to a tls or bare server should be implicit by the protocol in the url. This means that any `tls` connection option should only be to provide additional options such as CA certificates, or additional tls options required by the connection.

### Proposed Solution

* The protocol in the nats server url, should dictate the requires tls or not.
* The gossiped hostports should include the protocol exposed by the server
* Any client TLS connection option becomes additional TLS configuration options and only used if the server is sporting a secured connection.
* Since gossiped servers are notified to the client, the client could remove implicit servers that don't comply with their required connection policy from the submitted list.

While at it, it would be great if the protocol for tls connections was `nats-tls`

**Comment by kozlovic** [comment]
I don't think that any change is required and if client libraries follow the Go library implementation, it works seamlessly. It does not matter what the protocol in front of the URL is, actually most languages would fail if trying to dial to anything but an `host[<ip>]:port`. The INFO protocol sent from the server to the client after accepting the TCP connection does contain the information regarding the need or not for the client to switch to TLS.

The client library logic should be as follow:
- If the user configures TLS for the connect, he/she wants to create a secure connection, so if the server is not configured for TLS, the connection to *this* server should fail.
- If the server is configured to use TLS but the client has not specifically specified TLS, then the library should try to switch automatically to TLS. In some languages, it is possible to do a TLS handshake without the user specifying any certificates (especially if the server is not configured to verify client certificate). So here the user does not require TLS, but there is nothing wrong making the connection secured. If the user has not provided any TLS configuration and the automatic switch to TLS is not possible, then the connection to *this* server will fail.

If there are servers in the cluster with different client TLS settings (some require, some not - although I doubt that this is common), a client may be able to connect to a server while failing to (re)connect to others with the above logic. Again, I don't think the heterogenous setup will be common, but if it happens, the library will still do the right thing with the current protocol.
