### ISSUE TITLE
Sublist multithreaded performance

### ISSUE THREAD

**Issue by tylertreat** [nats-io/gnatsd#88]
I noticed that the `Sublist` tree which manages subscriptions uses a mutex for thread-safety, so every lookup and insert locks the tree. While I haven't looked through the gnatsd code extensively to see what the workload might normally look like, I imagine there is a lot of lock contention on the tree.

I recently implemented a similar, [lock-free mechanism for managing subscriptions](https://github.com/workiva/matchbox) with wildcards so, out of curiosity, I benchmarked the two to see how they compare. Again, I'm not sure how the workloads compare in practice, but for my purposes, it's fairly parallel.

Here are the results of the [benchmarks](https://github.com/tylertreat/gnatsd/blob/multithreaded_benchmark/sublist/sublist_test.go#L509-L700) I ran. The first is a 1:1 insert-to-lookup workload. The second is a 1:3 insert-to-lookup workload. Each insertion goroutine is inserting 1000 items. Each lookup goroutine is looking up 1000 items. The timings correspond to the complete insert and lookup workload. `GOMAXPROCS` was set to 8; 2.6 GHz Intel Core i7.

![benchmark_1_1](https://cloud.githubusercontent.com/assets/552817/8266229/05395d2e-16e8-11e5-8687-e3f809690084.png)
	
| goroutines | sublist (ms) | matchbox (ms) |
| -------------- | --------------- | -------------------- |
| 1 | 0.140295 | 0.375199 |
| 2 | 34.164212 | 2.427285 |
| 3 | 35.300207 | 3.018856 |
| 4 | 67.377877 | 3.166839 |
| 5 | 71.946041 | 3.908559 |
| 6 | 104.820086 | 4.147633 |
| 7 | 102.255676 | 4.930233 |
| 8 | 141.170446 | 4.895257 |
| 12 | 206.446077 | 7.528176 |
| 16 | 270.715069 | 10.086031 |

![benchmark_1_3](https://cloud.githubusercontent.com/assets/552817/8266231/0dc02090-16e8-11e5-871f-d1acc8a3c41b.png)

| goroutines | sublist (ms) | matchbox (ms) |
| -------------- | --------------- | -------------------- |
| 1 | 0.425787 | 0.506438
| 2 | 34.532406 | 2.403753
| 3 | 35.66657 | 2.951643
| 4 | 36.015616 | 3.622817
| 5 | 69.265923 | 3.847979
| 6 | 69.915697 | 4.684678
| 7 | 70.707467 | 6.088789
| 8 | 70.569563 | 6.408932
| 12 | 107.247048 | 10.814583
| 16 | 146.281991 | 15.254943

As you can see, the lock-free approach scales a lot better under contention. This is also without a cache in front of its tree. I'm curious to hear your thoughts and if such a technique could be beneficial to gnatsd.

**Comment by derekcollison** [comment]
Tyler, will enjoy taking a look. Sublist has needed some love for awhile, since Go maps now are so much faster than when Go was in development. I also agree the locking was crude at best, but most of the workload patterns are for high throughput reads and less updates/inserts so was happy with the performance with the front end caching mechanism.

I will definitely take a deep dive into yours. The wildcards are a bit different but interested in your approach.

**Comment by derekcollison** [comment]
I have used the generation trick before in extreme high performance and concurrent data structures for snapshotting, etc as you did. I have also used dirty bits etc..

**Comment by tylertreat** [comment]
There's still a lot of optimization I want to do with matchbox, both performance and memory. The Ctrie-style structure is not very compact when applied to this type of trie. I've thought about ways to roll up the branches and expand them lazily when necessary or maybe using a bloom filter to avoid descending the trie when there are no matches. The wildcards throw a pretty big wrench in a lot of those ideas though. I haven't spent enough time thinking through optimizations though.

**Comment by derekcollison** [comment]
Wildcards are the hard part for sure. By the way, you can cache empty results as well, anything that is a high rate, including no results. Been thinking about another way to possibly optimize. Will be fun to play with when I get some free time.

**Comment by derekcollison** [comment]
I am seeing this now with the new nats-bench program for the Go client. Its on my list to redo, thanks again for one of the best issue writeups.. ;)

**Comment by derekcollison** [comment]
Fixed this with df02bc0bcf90717889aa9ab9189162fb43d6dc3a and pending PR that allows clients to maintain an L1 non-contended result set.
