### ISSUE TITLE
Not handled error in test maxpayload_test.go

### ISSUE THREAD

**Issue by valichek** [nats-io/gnatsd#883]
Test needs correction to handle error on `write`
```go
pub := fmt.Sprintf("PUB bar %d\r\n", size)
conn.Write([]byte(pub))
if err != nil {
	t.Fatalf("Could not publish event to the server: %s", err)
}
```
https://github.com/nats-io/gnatsd/blob/master/test/maxpayload_test.go#L56-L60

**Comment by wallyqs** [comment]
Fixed at https://github.com/nats-io/gnatsd/commit/530b63a5dd08a8350a1fff2b084e46a7a26e19be
