### ISSUE TITLE
Server reads whole PUB message even when length of payload is bigger than size arg

### ISSUE THREAD

**Issue by valichek** [nats-io/gnatsd#884]
- Defect
 
#### Versions of `gnatsd` and affected client libraries used:
all

#### Steps or code to reproduce the issue:

add more tests to https://github.com/nats-io/gnatsd/blob/master/server/parser_test.go#L212

```go
        // Clear snapshots
	c.argBuf, c.msgBuf, c.state = nil, nil, OP_START

	// note this is the case when data has more bytes than expected by size
	pub = []byte("PUB foo.bar 11\r\nhello world hello world\r")
	err = c.parse(pub)
	t.Logf("%s", err) // nil, no error means that it reads all the data from connection until \n
	t.Logf("%d", len(c.msgBuf)) // 24

	// Clear snapshots
	c.argBuf, c.msgBuf, c.state = nil, nil, OP_START

	// note this is the case when data has more bytes than expected by size,
	pub = []byte("PUB foo.bar 11\r\nhello world hello world\r\n")
	err = c.parse(pub)
	// ensure that it reads all the data from connection until \n\r
	t.Logf("%d", len(c.msgBuf)) // 25
	t.Logf("%s", err) // Client parser ERROR, state=30, i=39: proto='""...'
```

#### Expected result:
 
Parser should detect too big payload before reaching end of payload

#### Actual result:
 
Server reads whole PUB message payload even when length of payload is bigger than size arg. So it's easy to load the server's memory with long PUB messages without `\n`. 

Here is simple example with increasing memory

```go

func TestMaxPayload2(t *testing.T) {

	opts := LoadConfig("./configs/override.conf")
	opts.MaxPayload = server.MAX_PAYLOAD_SIZE
	srv := RunServer(opts)
	_ = srv.StartMonitoring()

	endpoint := fmt.Sprintf("%s:%d", opts.Host, opts.Port)

	defer srv.Shutdown()

	size := opts.MaxPayload * 10
	big := sizedBytes(size)

	conn1, err := net.DialTimeout("tcp", endpoint, time.Millisecond*500)
	defer conn1.Close()
	if err != nil {
		t.Fatalf("Could not connect to server: %v", err)
	}
	t.Logf("MaxPayload: %d, Big: %d", opts.MaxPayload, len(big))
	pub := fmt.Sprintf("PUB bar %d\r\n", opts.MaxPayload)
	_, err = conn1.Write([]byte(pub))
	if err != nil {
		t.Fatalf("Could not publish event to the server: %s", err)
	}

	for {
		time.Sleep(time.Second)
		_, err = conn1.Write(big)
		if err != nil {
			break
		}

		varz, _ := srv.Varz(nil)

		log.Println(fmt.Sprintf("%d", varz.Mem))
	}

}

```

**Comment by valichek** [comment]
Fix could be here:

https://github.com/nats-io/gnatsd/blob/master/server/parser.go#L264-L268

```go
                       default:
				if c.msgBuf != nil {
					c.msgBuf = append(c.msgBuf, b)
				}
				if len(c.msgBuf) > c.pa.size {
					goto parseErr
				}
				continue
```

**Comment by derekcollison** [comment]
I will take a look, thanks.

**Comment by valichek** [comment]
@derekcollison also, have not found parser tests for exceeding MAX_CONTROL_LINE_SIZE

**Comment by valichek** [comment]
@derekcollison And I think that `argBuf` is also not well-protected, read buffer can be increased (it is variable) so MAX_CONTROL_LINE_SIZE limit won't be applied

**Comment by derekcollison** [comment]
Will review all your concerns sometime this week. Thanks again for the feedback.

**Comment by derekcollison** [comment]
MAX_CONTROL_LINE is enforced but on a split buffer, which will naturally occur in normal operations, meaning we will only be reading about 65k max. We would already have the buffer and the read is a single IO call. When we fall out without the parser knowing what to do we check argBuf for the violation.
