### ISSUE TITLE
CPU hits 100% if there is a config parse error

### ISSUE THREAD

**Issue by legg** [nats-io/gnatsd#886]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

Make sure that these boxes are checked before submitting your issue -- thank you!

 - [x] Included `gnatsd -DV` output
 - [x] Included a [Minimal, Complete, and Verifiable example] (http://stackoverflow.com/help/mcve)
 
#### Steps or code to reproduce the issue:
Edit the config: `${PWD}/nats/gnatsd.conf` with a missing ` }`
```
# Client port of 4222 on all interfaces
port: 4222
debug: true
trace: true
log_file: "/logs/gnatsd.log"

# HTTP monitoring port
monitor_port: 8222

# This is for clustering multiple servers together.
cluster {

  # Route connections to be received on any interface on port 6222
  port: 6222

  # Routes are protected, so need to use them with --routes flag
  # e.g. --routes=nats-route://ruser:T0pS3cr3t@otherdockerhost:6222
  authorization {
    user: ruser
    password: T0pS3cr3t
    timeout: 2
  }

  # Routes are actively solicited and connected to from this server.
  # This Docker image has none by default, but you can pass a
  # flag to the gnatsd docker image to create one to an existing server.
  routes = []
```
Run nats via docker
```
docker run --rm -p 4222:4222 -p 6222:6222 -p 8222:8222 -v "${PWD}/nats/gnatsd.conf:/gnatsd.conf" -v "${PWD}/nats/logs:/logs" -ti --name nats nats:1.4.0-linux --debug --trace
```
To fix add the missing `}` in the `gnatsd.conf` and re-run docker

#### Expected result:
 `e6099dccacbe        nats                0.05%               2.375MiB / 5.818GiB   0.04%               1.46kB / 0B         0B / 0B             10
`
#### Actual result:
 `b5c510a8bdad        nats                100.10%             6.129MiB / 5.818GiB   0.10%               1.32kB / 0B         12.3kB / 0B         7`
 Doesn't output logs or debug info so hard to know what is wrong

#### Proposed Change:
Config errors should print to stdout and process to fail

**Comment by ripienaar** [comment]
I verified this using `gnatsd -c broken.conf` too
