### ISSUE TITLE
Listen on multiple addresses

### ISSUE THREAD

**Issue by lenovouser** [nats-io/gnatsd#911]
I want to listen on multiple IPv4 and IPv6 addresses, it doesn't seem to me like this is possible currently?

Configuration:

```
listen: [ '10.xx.xx.50:4222', '10.xx.xx.51:4222', '[xxxx:xxxx:xxxx:xxxx:100a::]:4222', '[xxxx:xxxx:xxxx:xxxx:100b::]:4222' ]

http: 'localhost:8222'

# cluster
cluster {
  listen = [
    '10.xx.xx.50:4244',
    '10.xx.xx.51:4244',
    '[xxxx:xxxx:xxxx:xxxx:100a::]:4244',
    '[xxxx:xxxx:xxxx:xxxx:100b::]:4244'
  ]

  routes = [
    'nats-route://server-2:4244',
    'nats-route://server-3:4244'
  ]
}
```

I tried different variations like using `listen = [` or comma-separated values like `listen = a, b, c`

**Comment by derekcollison** [comment]
Currently a single server only binds one port for client connections. However, if the port is the same but you want all interfaces you can use 0.0.0.0 for listen or addr, or simply set port = 4222 and that will allow connections on all interfaces.

**Comment by lenovouser** [comment]
Ah, okay. I want to run multiple instances on the same server though. How would I go about that? I need them to listen to a specific IPv4 and IPv6 address.

**Comment by derekcollison** [comment]
Help me understand what you are trying to achieve and why?

You could use different servers on different ports cluster together over loopback. 
You could also use port mapping if on linux like socat or ncat.

**Comment by lenovouser** [comment]
I want to run different clusters for different environments but with the same setup (so that I can test things on non-prod clusters that run on the same machines for maximum similarity) on my roots and thus would need them to bind to only specific IP addresses, but at least two of them because I'd like to support IPv4 and IPv6. I have split up my other services like MongoDB like this too last week but I am struggling with NATS. Another thing I have thought about was using a docker image and proxying the ports to only the IPs I need - but I currently don't use docker on my machines and would rather not for now because of issues with IPTables rules and Docker circumventing them when proxying ports that they never really fixed (https://github.com/moby/moby/issues/29312).

**Comment by ripienaar** [comment]
It's a bit of a drag and general this kind of multiple purpose machines - especially multi purpose cross environments is a bad idea - but if you insist I would suggest using ip netns to make a namespace with your chosen ips and running your instance in there.

You can read outage reports from so many people who have done this including GitHub - it always goes bad with traffic for development ending up in production by accident.  The investment in a extra VM is well worth it.

**Comment by derekcollison** [comment]
in NATS 2.0 (on master, release soon) has support for accounts which can separate out your traffic as well based on auth. 

You can read a bit on NATS 2.0 features here: https://synadia.com/ngs/how-it-works/

Proper docs coming..
