### ISSUE TITLE
Is there a client for erlang/elixir ?

### ISSUE THREAD

**Issue by mrkaspa** [nats-io/gnatsd#93]

**Comment by cosmicnag** [comment]
+1

**Comment by bjflanne** [comment]
There is not currently, but many clients have been added recently. Lots of great community activity on clients ongoing. How do you use erlang currently, and how are you using NATS (or expecting to use NATS)?

**Comment by bjflanne** [comment]
Would you both mind voting in our client support survey? Just takes a quick second, would like to make sure to include your input: 

https://www.surveymonkey.com/r/JGZRYWN

**Comment by chendo** [comment]
+1

**Comment by cosmicnag** [comment]
Sorry for the late response @bjflanne ... I am using NATS as the main communication channel for my microservice architecture (its the best and simplest from a lot of options)... We mostly use NodeJS services , but are also experimenting with Elixir. Whether we can actually go ahead with Elixir or not largely depends on NATS support.
Thanks. Did the survey with the obvious choice for me :)

**Comment by railsmechanic** [comment]
+1

**Comment by sammccord** [comment]
+1

**Comment by railsmechanic** [comment]
I think there is a client for Elixir...

https://github.com/aforward/elixir_nats

**Comment by derekcollison** [comment]
We are also working on one. /cc @camros

**Comment by bjflanne** [comment]
Hello everyone -- the Elixir client is now available in alpha: Please let us know what you think, questions, et al! https://github.com/nats-io/elixir-nats
