### ISSUE TITLE
mkpasswd until does not work on Windows 10

### ISSUE THREAD

**Issue by Ryner51** [nats-io/gnatsd#934]
- [X] Defect
 - [ ] Feature Request or Change Proposal
 
#### OS/Container environment:
Windows 2010
go version go1.11.5 windows/386

#### Steps or code to reproduce the issue:
 go run mkpasswd.go -p
OR
mkpasswd.exe

#### Expected result:
 Enter in password and obtain bcrypt hash

#### Actual result:
Does not allow to enter in a password and provides a random bcrypt hash

**Comment by derekcollison** [comment]
What version of `golang.org/x/crypto/ssh/terminal` do you have on your system?

**Comment by Ryner51** [comment]
I used the following command to install `golang.org/x/crypto/ssh/terminal`
go get -u golang.org/x/crypto/ssh/terminal

**Comment by derekcollison** [comment]
ok thanks, will check it out.
