### ISSUE TITLE
confusion about  cluster upgrade

### ISSUE THREAD

**Issue by peng-w** [nats-io/gnatsd#939]
Hi：
    This article wrote [Cluster Upgrade](https://nats.io/documentation/managing_the_server/upgrading/)：

![GIF](https://user-images.githubusercontent.com/6479081/55939181-b63bac00-5c6f-11e9-82a7-d18c54cfbaf7.gif)
   Are you sure this code will work？

**Comment by wallyqs** [comment]
Hi, the issue seems to be that `localhost` is not resolving on your computer.

**Comment by peng-w** [comment]
> 
> 
> Hi, the issue seems to be that `localhost` is not resolving on your computer.

@wallyqs ：Thank you，you are right。Used ip is ok，:smile:。
