### ISSUE TITLE
Change the project description to optimize searching in Github

### ISSUE THREAD

**Issue by h12w** [nats-io/gnatsd#94]
I was trying to search "message queue" built with Golang on Github but only get a few client wrappers (ordered by most stars). Later a friend on social network recommends NATS and I realize what's wrong with the searching:

Please just change the project description to something like: "NATS: an open-source, high-performance, lightweight cloud message queue system".

**Comment by derekcollison** [comment]
Is it important to have the word "queue"?

**Comment by h12w** [comment]
I have noticed that the description has been improved since I submitted the issue.

I think it depends on what key words people are searching. If people are searching for "messaging system", the description is good enough now, but if "message queue" is searched, gnatsd still cannot be found.

**Comment by mcqueary** [comment]
Hi there! In our experience, 'messaging' tends to be the more general/common term used for message-based publish-subscribe systems like NATS. A cursory search on GitHub for 'golang messaging' nets 68 repositories, with NATS topping the list (1448 stars and 174 forks as of this writing). A similar search for 'golang message queue' nets 8 repositories, all of which seem to be experimental or individual projects with 0 or 1 forks or stars. 

We'll close this for now. Thank you for your feedback!
