### ISSUE TITLE
Reusing the same certificate for NATS cluster doesn't scale

### ISSUE THREAD

**Issue by JensRantil** [nats-io/gnatsd#944]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

My configuration:
```
listen: 0.0.0.0:4222
http: localhost:8222 # HTTP monitoring port

cluster {
  listen: 0.0.0.0:6222

  tls {
    cert_file: "/etc/tls/tls.crt"
    key_file:  "/etc/tls/tls.key"
    timeout: 2
    ca_file:   "/etc/tls-ca/ca.crt"
  }

  # Routes are actively solicited and connected to from this server.
  # Other servers can connect to us if they supply the correct credentials
  # in their routes definitions from above.
  routes = [
    nats://nats:6222
  ]
}
```
The DNS record `nats` resolves to the IP addresses of my NATS instances.

My (self-signed, used for dev only) certificate looks as follows:
```
openssl x509 -in nats.pem -text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 11098888726640716153 (0x9a072c7e1101e979)
    Signature Algorithm: sha1WithRSAEncryption
        Issuer: CN=kube-ca
        Validity
            Not Before: Apr 12 16:46:22 2019 GMT
            Not After : Apr  9 16:46:22 2029 GMT
        Subject: CN=nats
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:b4:9f:c1:5a:40:6c:ff:c9:e7:5f:5a:05:98:f6:
                    2e:5d:e9:97:84:e5:4c:0a:61:d7:8d:03:62:a2:7f:
                    5b:b8:e7:82:96:c1:01:23:41:32:6d:09:98:69:57:
                    b9:f2:2d:d2:6c:ff:c7:61:0b:e6:8d:38:b0:3b:01:
                    4f:03:98:a2:94:8b:8b:f2:e8:9b:bf:9e:99:8c:37:
                    f6:dd:07:13:a7:3c:74:bb:25:89:8e:32:53:c7:7c:
                    20:79:a8:ee:cf:dc:0e:94:b9:52:ab:21:39:d5:dd:
                    a2:12:81:13:c5:21:43:bd:78:9e:e2:85:a0:e7:27:
                    69:5d:a1:e0:09:c9:3c:53:d4:3b:5a:6d:d8:8b:60:
                    d2:bf:70:6c:8f:13:a4:22:d3:c2:38:24:80:3e:d5:
                    d8:fb:c1:44:d7:83:dc:4c:6c:d7:15:4d:d3:9e:71:
                    b4:4f:74:bc:0c:c7:53:3e:ae:c7:d8:ad:85:bd:23:
                    ce:51:97:d2:e3:8d:ee:13:2a:05:22:4a:ec:6e:68:
                    7b:ba:43:73:02:f3:75:16:62:d3:8a:96:eb:0e:70:
                    13:51:c3:bd:a3:a5:6a:65:3a:11:f8:e2:01:dc:d6:
                    12:12:13:f4:09:60:a4:60:52:c6:64:8a:ea:e6:96:
                    db:6a:03:4c:78:94:da:78:30:35:bf:8b:5d:b3:b5:
                    ba:77
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Basic Constraints:
                CA:FALSE
            X509v3 Key Usage:
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Subject Alternative Name:
                DNS:nats
    Signature Algorithm: sha1WithRSAEncryption
         5f:1d:7c:a0:3b:6b:c4:4b:c2:fc:fe:cf:df:9e:d0:51:ae:9e:
         bf:6f:6b:7d:a4:a4:7c:79:91:78:f2:59:7c:f0:ed:3f:b3:43:
         a5:31:41:80:9e:dd:d4:a1:d8:27:b6:13:04:6d:d3:e4:f4:ca:
         be:03:f1:a5:1a:e8:25:54:4d:8a:bc:8c:d7:90:7d:54:96:35:
         e0:e8:1c:06:62:70:5b:d9:e0:73:f8:47:6b:dc:8f:e9:46:58:
         1c:9a:52:89:33:60:8d:45:d2:9d:17:db:df:13:51:93:73:f4:
         cd:79:a0:4a:df:f0:fc:6d:d8:c6:59:28:5f:22:0a:6f:50:4c:
         29:b6:e7:b7:1b:ee:29:24:e6:d2:be:a8:4c:60:c2:7d:6a:b8:
         4e:fc:47:25:7c:96:bf:0f:26:a6:9c:b9:89:27:ad:3e:6b:e6:
         2c:3b:21:6f:b5:3f:c5:dd:fd:2c:97:ec:87:55:56:ed:bf:d8:
         65:f7:14:97:2e:5b:18:f1:06:78:57:f6:db:2b:a0:1d:27:b6:
         ff:e0:2b:3b:42:2f:81:53:a1:cc:34:51:96:fb:0e:ef:df:17:
         ab:9c:f2:3e:e7:ae:c9:b6:ea:fa:2f:a6:d9:de:cb:3c:d1:8b:
         15:7c:85:b8:ea:e2:b2:f0:74:9e:c6:9a:74:79:d4:92:1c:4d:
         be:48:48:1a
```

#### Versions of `gnatsd` and affected client libraries used:

1.4.1

#### OS/Container environment:

Linux.

#### Steps or code to reproduce the issue:

I am starting the three NATS instances one at a time:

1. The first one (1) starts without any issue.
2. The second one (2) starts, resolves `nats` DNS record and connects to (1). TLS validation is succesful since our expected common name is `nats`. I can also see they are connected in since both are listed in `connect_urls` on `/varz`.
3. The third one starts. It successfully connects to one of (1) and (2) by randomly selecting one of the IPs that `nats` resolves to. It then fetches a full list of all instances, and tries to connect straight to them using IP.

#### Expected result:

I expect 3) to be able to connect to all instances and the cluster be fully formed with every instance connected to all other.

#### Actual result:

TLS validation fails with something like

    Error flushing: x509: cannot validate certificate for 172.17.0.4 because it doesn't contain any IP SANs

because my certificate does not include an IP SAN and auto-discovery of additional NATS cluster instances is commonly done by announcing IP addresses.
 
## Feature Requests / Proposed Change

Being able to set force which host that TLS validation should be using. That is, I'd like all nodes to be validated against the same hostname. My proposal is that an additional `tls` configuration setting is introduced, `hostname_whitelist` which is an array of common/subject alternative names that are accepted when validating a certificate.

This would mean [custom hostname validation](https://stackoverflow.com/a/44296206) would need to be put in place in case the array is defined.

### Who Benefits From The Change(s)?

Operators who'd like to operate a NATS cluster in a larger subnet where IP allocation is non-deterministic (AKA "Cloud", "Kubernetes" etc.)
 
### Alternative Approaches

 * Using the `insecure` flag introduced in 83aefdc71449484d0b1a57a6c57c7ba6eabd8ef2. This is bad security practise.
 * Having one DNS record and certificate (with equivalent common name) per NATS instance.
   * It might be worth pointing out here that I'm setting up NATS as a Kubernetes deployment. For K8s workloads, this would likely mean that I would need to use something like a statefulset which would complicate things a bit.
 * IP range in SSL subject alternative name [does not seem possible](https://security.stackexchange.com/questions/91368/ip-range-in-ssl-subject-alternative-name), however I guess for smaller networks you could add one alternative name per IP address.

### Additional information

 * It looks like I'm [not the first one](https://github.com/pires/kubernetes-nats-cluster/blame/master/README.md#L20) to hit this issue.
 * Looks like #712 and/or #868 are related.

**Comment by wallyqs** [comment]
```
For K8s workloads, this would likely mean that I would need to use something like a statefulset which would complicate things a bit.
```

You don't have to use a statefulset necessarily, but rather have to use A records as part of the pods definitions as well as using a wildcard certificate that matches a headless service, something like:

```
kind: Pod # or Deployment, etc...
metadata:
...
spec:
  hostname: "$(POD_NAME)"
  subdomain: "headless-nats-service" # name of a headless service that matches via labels
```

Not sure if there are good docs from k8s to cover how to do this, but this is the approach that we take in the nats-operator. Here is a small guide on using cfssl to create wildcard certs and an example k8s deployment: https://gist.github.com/wallyqs/696b81427df7c239fb34946eb1ae9f92

**Comment by JensRantil** [comment]
Excellent! 🎉  I got this working locally in minikube. Just curious, is gnatsd announcing its `${HOSTNAME}.${SUBDOMAIN}` or its IP. If IP I assume there is a reverse DNS lookup that maps the announced IP address to `*.headless-nats-service`?

**Comment by wallyqs** [comment]
When using the nats-operator it announces the A record, if not using you need to look at cluster_advertise and client_advertise settings, otherwise it will be announcing the ips via gossip

**Comment by JensRantil** [comment]
Thanks!
