### ISSUE TITLE
Feature request: Fail on startup for unrecognized configuration file options

### ISSUE THREAD

**Issue by JensRantil** [nats-io/gnatsd#951]
- [ ] Defect
 - [x] Feature Request or Change Proposal
 
#### Use Case:

This is a usability improvement.

I am learning NATS and picking up the configuration options. [Sometimes I'm unsure about where certain options should be placed](https://github.com/nats-io/gnatsd/issues/950#issuecomment-483711238). Sometimes I simply mistakenly put them in the wrong place.
 
#### Behaviour today

Create a file:
```bash
$ cat > some.conf
dfskhjsdfkhfsdkjfh: 42
```
then execute `gnatsd -c some.conf`. Notice that gnatsd doesn't complain about my weird option.

```bash
$ gnatsd --version
nats-server version 1.4.1
```

#### Proposed Change:
 
I propose that something like this will happen:
```bash
$ gnatsd -c some.conf
Unknown configuration file option: dfskhjsdfkhfsdkjfh
```
and that it exits with non-zero.

#### Who Benefits From The Change(s)?

Newcomers as well as people who sometimes mistypes configuration files ;)
 
#### Alternative Approaches

N/A

**Comment by kozlovic** [comment]
Current server on master (soon released as 2.0) would fail to start with this config. Also, in that release, there is the `-t` option to just check and report errors about a configuration file.

**Comment by kozlovic** [comment]
The changes are too big to back-port to 1.4.1..

**Comment by wallyqs** [comment]
Should we close this issue since already addressed in master? @JensRantil this is how it works in master right now: 

```sh
 gnatsd -c some.conf
nats-server: some.conf:1:0: unknown field "dfskhjsdfkhfsdkjfh"
```

**Comment by JensRantil** [comment]
Oh, great! Backporting isn't important.
