### ISSUE TITLE
Out of memory panic (nats 2.0)

### ISSUE THREAD

**Issue by azrle** [nats-io/gnatsd#954]
- [x] Defect
 - [ ] Feature Request or Change Proposal
 
## Defects 

When we starts a cluster with 100+ servers with one single route (to a certain NATS server), we observe out of memory panic (because of error)?

https://gist.github.com/azrle/d3107f44d944b8ffddf4aeb106fb3612
 
#### Versions of `gnatsd` and affected client libraries used:

2.0 RC-5 (a4af582dfb2a9a8a6dc7b0f11da91f25da763410)

**Comment by wallyqs** [comment]
Thanks, could you explain a bit more about the network topology? Do you mean 100 nats client connections to a nats cluster of 2 nodes (so a single route to each other)?

**Comment by azrle** [comment]
Sorry for lack of explanation.
The network topology is that, we first have a gnatsd server `SEED`.
And we started 100+ gnatsd server with config like this:
```
listen: $SERVICE_BIND
http: $HTTP_BIND

cluster {
  listen: $CLUSTER_BIND
  routes = [
    $IP_ADDRESS_OF_SEED
  ]
}
```
Thus, finally it became a cluster with 100+ nodes (less than 200).

Without any connections, memory of some of gnatsd nodes has been already climbed upon 2 GB.
And I believe sometimes out of memory has already occurred.

When the connections comes in (at around 20:38:30), each gnatsd node had 15~18 connections. And the memory grew up again. And after we sent out the traffic (at around 20:40:30), the memory just went out of control.

![image](https://user-images.githubusercontent.com/2177709/56286840-b6e3af00-6155-11e9-9244-8074f85371ab.png)

By the way, it does not happen with gnatsd 1.4 with same settings and traffics.

**Comment by derekcollison** [comment]
Thanks we will take a look. In general people run smaller clusters, but regardless this behavior should not be what it is.

**Comment by derekcollison** [comment]
Master branch now has better memory profile on startup for large clusters. If possible run same setup against master. Thanks again.

**Comment by kozlovic** [comment]
and let's wait for fix for #955. About to submit PR which will address this.

**Comment by kozlovic** [comment]
Ok, fix for #955 is in, so @azrle you can have a go with master.

**Comment by azrle** [comment]
Cool! Thanks for the quick fix. We will give it a try.

**Comment by derekcollison** [comment]
Thank you for the detailed report, much appreciated.

**Comment by azrle** [comment]
Looks like memory problem solved. Thanks again!
