### ISSUE TITLE
The window service wont start

### ISSUE THREAD

**Issue by xeroxstar** [nats-io/gnatsd#972]
Hello, i was trying to install nats as service on win2016 but it doesn't start and give me an error - the service did not respond to the start or control request in a timely fashion. 

Here is my line:
sc.exe create gnatsd binPath="c:\gnatsd.exe gnatsd -a 127.0.0.1 -p 4222 --auth 12345" 

Is there any idea why?

**Comment by kozlovic** [comment]
Can you try with adding double quotes around the exe? I have these instructions for nats streaming server:
```
sc.exe create nats-streaming-server binPath="\"<streaming server path>\nats-streaming-server.exe\" [NATS Streaming flags]"
sc.exe start nats-streaming-server
```
notice the use of `\"` around the exe name. I think this is required. So that that would be this in your example:
```
sc.exe create gnatsd binPath="\"c:\gnatsd.exe\" -a 127.0.0.1 -p 4222 --auth 12345"
```

**Comment by xeroxstar** [comment]
I was doing it wrong and some how missed that, i added gnatsd after gnatsd.exe.
sc.exe create gnatsd binPath="c:\gnatsd.exe gnatsd -a 127.0.0.1 -p 4222 --auth 12345" 

I had to remove the gnatsd after gnatsd.exe so now it is working: 
sc.exe create gnatsd binPath="c:\gnatsd.exe  -a 127.0.0.1 -p 4222 --auth 12345" 

Anyway thanks for quick response.

**Comment by kozlovic** [comment]
I missed that too ;-) Glad it works now!
